### ISSUE TITLE
New game mode: Duel

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo#10]
dodsoN made a suggestion to have a Duel mode, whereupon you join the server, you either join into the game, are set in spectator mode, or in the queue. Two players duel until one loses (timelimit) and the next person in the queue joins in (no map change) and the loser goes to the back of the queue. If you do not join the queue, you are always spectating. To join the queue, type /join (or something along those lines) to be entered to the end of the queue. Maybe even something you click on to join the queue, like holding down tab to see the scoreboard and have a Join Queue and Leave Queue button?

Static limits:

timelimit to 15 minutes

2 players max playing at once (everyone else spectates)

Lowered ammo limits to all guns (50% less ammo on all guns except for Rocket Launcher and Railgun, which are reduced to a maximum of 20 rockets / 10 slugs

**Comment by jdolan** [comment]
@jar3817 @WickedShell Any interest in taking this on?

**Comment by jar3817** [comment]
Yup
