### ISSUE TITLE
Use LLVM/clang for automated native and cross compiled binaries

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo#105]
We could use LLVM to generate binaries for Windows, OSX and Linux on the same platform.
An alternative would be setting up an OSX VM which is always reachable.
But switching to LLVM should be done regardless.

For windows builds: https://github.com/tpoechtrager/wclang
For OSX builds: https://github.com/tpoechtrager/osxcross

**Comment by jdolan** [comment]
+1

**Comment by WickedShell** [comment]
I've used clang to do the static analysis in the past of q2w with pretty
favorable results (it solved something I couldn't figure out how it was
happening with gdb). Ironically there are a couple of warnings that clang
gives that GCC would rather you didn't fix and vice versa.

**Comment by jdolan** [comment]
Just an update on this one: as of late, I've been cutting Mac, Linux and Windows builds from my OS X host. I have a Fedora VM for mingw-cross, and Debian for Linux native builds. This all works surprisingly well; it's just a bit tedious to do.

**Comment by jdolan** [comment]
http://ci.quetoo.org is now a Jenkins instance running on the quetoo.org server. It has 2 slaves that live in EC2: Debian Jesse for Linux builds, and Fedora for MinGW. I still cut the Mac builds from my Macbook, but I don't always remember to do this, so an automated solution would of course be better.

**Comment by maci0** [comment]
At one point I had Mac builds working on Fedora using https://github.com/tpoechtrager/osxcross just generating the .dmg with an icon etc didn't work. The actual binaries produced worked just fine.
There is also http://www.macincloud.com/pricing/compare but that is somewhat pricey though.
Virtualizing macos on unsupported hardware using qemu/kvm, while in possible is against apples EULA.
