### ISSUE TITLE
Hand grenades

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#108]
Assets required for hand grenades:

 * Grenade prime sound
 * Grenade fly sound

**Comment by jar3817** [comment]
Hey, give this a try. There should be a public server called "claire grenade test", give it as shot. If you don't see it in the browser try to connect to "buf2.packetflinger.com:1998"

You'll need these assets in your share folder: http://quetoo.packetflinger.com/dl/grenade-assets.pk3

**Comment by jar3817** [comment]
Oh yeah, when you grab some nades "use grenades" to start tossing

**Comment by jdolan** [comment]
Pretty freaking sweet! A couple notes:

 * The velocity ramp for holding / priming a nade is very steep. I think maybe the max velocity should be scaled down a hair, and the min velocity brought up just a bit. Right now, they're very sensitive and it's difficult to gage how far a nade will travel based on priming it.
 * The link.cfg for the hand grenade model should use a slightly smaller scale. The grenade currently looks like a cantaloupe in the player's hand.
 * The prime sound could be amplified just a little. I'm not sure you'd hear it over combat noises.
 * Grenades currently come after the BFG when cycling through weapons. We should insert them just before the GL, just like in Q2.

This is great work, tho. Nicely done. I have not reviewed the code itself yet, but the functionality is sweet.

I'm headed to the keys this morning. Will be afk for most of this week, tho Friday I should be able to code review :)

**Comment by jar3817** [comment]
I knew about most of those notes (except for the cycling order) and I forgot about MOD messages... but just something that functions. 

I was basing the velocity off of the launcher which yesterday finally realized how pathetically weak it is. Like standing at the bottom of the stairs near LG on edge you can't get a nade on the level above the LG by the ramp. In the right scale that's like 10 feet...

Hf in the keys!
