### ISSUE TITLE
MAX_ENTITIES shortcomings

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#113]
The game module doesn't clamp g_max_entities to MAX_ENTITIES, which could very easily result in a crash. Also, MAX_ENTITIES is 1024, but MAX_CLIENTS is 256. At 256 clients, we could very easily burn through all 1024 entity slots. Since entity numbers are transmitted over the protocol as unsigned shorts, why not increase MAX_ENTITIES to something like 8192? There would be a memory footprint increase, as some entity state arrays are hard-coded to MAX_ENTITIES. Worth experimenting with.

**Comment by jdolan** [comment]
Moving this to low-priority enhancement. I've added clamping code to keep g_max_entities within acceptable bounds. More entities is really not a high priority at this point.

**Comment by kaadmy** [comment]
IMO 32 or 64 clients it easily enough, or make it a CVar?

**Comment by jdolan** [comment]
I think `MAX_CLIENTS` is `256` because we use a `byte` for "client id" in the network protocol. I agree that, practically speaking, `MAX_CLIENTS 64` would be adequate.

**Comment by jdolan** [comment]
To reiterate, I'd rather refactor the code so that `MAX_ENTITIES` is `INT16_MAX` or, if possible `UINT16_MAX`. And the right way to do this would be to dynamically allocate certain state buffers on the server. But none of this has any pressing need right now :)

**Comment by kaadmy** [comment]
Is this issue stale/closed or still needs further discussion?

**Comment by jdolan** [comment]
It is not closed, and doesn't really require further discussion, either. It's just a rainy day item. We currently overflow the net channel long before we approach `MAX_ENTITIES`, so I'm not worried about fixing this.
