### ISSUE TITLE
Replace g_teams and g_ctf with g_gametype cvar?

### ISSUE THREAD

**Issue by dmitripot** [jdolan/quetoo#116]
It would make it way easier to add game types, such as Clan Arena, Harvester, Jailbreak, Domination, etc. I'm tired of game modes spawning whole new gamedirs (which require code merging, etc, mind you). IMHO, separate game and cgame is only worth it if one were to make a major modification to the game style itself on a whole other level. For example, that superheroes mod for Quake 3, or that racing one. Now THAT is mod-worthy.

Separate cvars should prevail only for pan-gametype settings. For example, starting weapons, starting ammo, infinite ammo bool, health, etc.

**Comment by jdolan** [comment]
Yea, I totally agree with your overall assertion. I'm not sure that combining the cvars that we have in different ways can't yield the same thing -- perhaps even with more flexibility, tho.

These cvars don't load different game modules or gamedirs. The idea is that you can have instagib CTF, arena TDM, etc. I love the idea of adding new game types either way, tho :)

**Comment by dmitripot** [comment]
Ha, I was just going to say, I realized that insta is implemented already. Instagib is actually cvar-worthy for sure, since it works with any gamemode in the history of quake that comes to mind. Short of instagibbing overload bases :P
