### ISSUE TITLE
Armor logic is too simple, not fun

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#123]
Right now, armor just acts as additional health, which is silly. Study how Q2 handled the 3 armor types, and re-implement that or something similar.

**Comment by jar3817** [comment]
I like how q2 does armor. Off the top of my head (which is probably wrong) it was jacket took 30% of damage, yellow took 60% and red took 80%. And energy weapons (hb, bfg, blaster) cut through armor like a class above (cuts through ya, like it's jacket, ra like it's ya, jacket like you have none).

**Comment by jdolan** [comment]
Well with all that knowledge.. WE HAVE A WINNER!

**Comment by jar3817** [comment]
Sometimes I feel like Red is way overpowered in Q2 though. Like on maps that aren't balanced perfectly the player who gets red first wins. Maybe this is just in duel though. So perhaps making Red a special item (like MH) where it only spawns when the player who got it last runs out of it. Just a thought.

**Comment by jdolan** [comment]
Thanks @jar3817 for taking care of this.
