### ISSUE TITLE
Atomic jump

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#125]
Standing perfectly still, jumping in succession yields 2 increasingly higher jumps (approximately 1 entire jump higher, each time). While kind of fun / funny, most players would probably see this as a bug.

**Comment by jar3817** [comment]
This is really cool actually. This is unintentional current behavior? I may have to put something like this in qtjump.

**Comment by jdolan** [comment]
Hah. When I figure out _why_ it's happening, I'll send ya the diff ;)
