### ISSUE TITLE
Corrupt loading background image on r_restart

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#126]
The first r_restart while actively in-game will use a random texture from the current map as the loading background.

**Comment by jdolan** [comment]
@jar3817 Can you confirm that you see this on Linux or Windows as well?

**Comment by jar3817** [comment]
I do not see this on linux (Fedora 23), but I do on windows (7 pro). I tried updating and still got it. I didn't try building my own for windows...

**Comment by jdolan** [comment]
I discovered, in gutting AntTweakBar in the `jdolan/nuclear-option` branch, that this is actually ATB's fault. It goes away when we don't init AntTweakBar. So, I'm going to close this out, as we're moving away from ATB anyway.
