### ISSUE TITLE
UI / Menu improvements

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#132]
For the 1.0 release, the menus need some work:
- Servers list
  - Show map image when selecting a server
- Ability to create a listen server
  - Choose map from drop-down
  - Show mapshot image
  - Set hostname
  - Set max clients
  - Set CTF, Teams, Instagib, etc..
- Ability to set skin
  - Choose model from drop-down
  - Show player model
  - Choose effect color from drop down

**Comment by jdolan** [comment]
Tons of work has been done here. The major task left is finishing the *Create Server* menu.

**Comment by kaadmy** [comment]
Any progress on this lately?

**Comment by jdolan** [comment]
I did some work on Create Server a week or two ago. What remains is somehow handing off the map list the user has selected to the game module. I haven't decided how to do this yet.. Is this something you're interested on working on? It requires using Objectively/MVC.

**Comment by kaadmy** [comment]
I could give this a try, but don't expect anything working from me :D

**Comment by kaadmy** [comment]
After some cleanup, https://github.com/jdolan/quetoo/commit/ff3e9fd3fa86 should cover this issue, along with a new ingame material editor.
