### ISSUE TITLE
Demo file extension

### ISSUE THREAD

**Issue by jar3817** [jdolan/quetoo#134]
The current file extension for demos (.dem) is used for other games like Quake, Hexen II and others. It might not be a bad idea to change it to something unique so you can simply double-click on the file and have it open Quetoo. 

Perhaps .qtd or even .qtdemo. Thoughts?

**Comment by jdolan** [comment]
`.fap`. You won't do it.

**Comment by jdolan** [comment]
I'm fine with changing the file extension. The bulk of the work here would be to add some `argv` parsing to detect and play demo files when the OS launches us as such. Your call. Feel free to push this out of the milestone if you'd like to defer.

**Comment by jar3817** [comment]
Let's try .demo for a while

**Comment by jdolan** [comment]
👍

**Comment by jdolan** [comment]
a17733ac84766c03a55ee973c766ed99e30e22ca

**Comment by jar3817** [comment]
I looked how to link this to a commit but couldn't figure it out...newb...
