### ISSUE TITLE
History file not saved on Windows?

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#138]
Pan reports that the history file is not saved on his system. He said he can manually edit the file and insert lines to it, and those lines will be available when he launches the game (so reading the history file works). But every time the game exits, he said the file is blank. Can you verify this?

**Comment by jdolan** [comment]
First thing to try might be adding an `Fs_Flush` to `Con_WriteConsole` -- and if that works, we should probably add `Fs_Flush` to `Fs_CloseFile`. I don't expect this to work, tho. PhysicsFS and POSIX state that `fclose()` already invokes `fflush()`. But still worth investigating as low-haning-fruit.

**Comment by WickedShell** [comment]
Might be a fix. I've noticed that the linux build will sometimes crash on
quit for me. (Another thing I had fixed in the past! WHOOOO) so it's
possible windows is doing that at the moment.

**Comment by jar3817** [comment]
Yeah I looked at a few things like that with no success. I have a vague
recollection of trying and failing to get physfs to write in windows
previously...still looking though

**Comment by jdolan** [comment]
That's crazy. Maybe we should hit up the PhysicsFS mailing list, then.

http://icculus.org/mailman/listinfo/physfs

The author / maintainer, Ryan Gordon (Icculus) is @ryan in #icculus.org on Freenode, too. Side note, he's also one of the SDL core maintainers. A lot of this game runs on his code!

**Comment by Paril** [comment]
The history file is an odd one. It does load properly, but won't write. After reading through Con_WriteHistory I don't see how it could work for anybody unless you sent more than 64 lines of text.

It starts reading from the history at hist->index + i, which will always be blank _unless_ you wrap back around to index 0 from the modulo. I'm guessing that it should just be i, not hist->index + i.

**Comment by jdolan** [comment]
Ugh. Because I had a long-enough history file going into the console subsystem rewrite, I never noticed that this was broken. New code, just tested with no existing history, and it works now. Can you please confirm and close?
