### ISSUE TITLE
High framerates cause slow player movement

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#139]
Pan and Butane have reported intermittent slow player movement. Basically, in parts of the map, the players max speed will drop to 100ups. What we determined is that this happens when the user's framerate spikes (> 500fps). We discovered that setting a framerate cap (`cl_max_fps` or `r_swap_interval 1`) alleviates the issue. What must be happening is that the `cmd_t.time` value is too small for the movement to correctly accumulate. This needs a fix.

CCing @jar3817 just 'cause you'll probably find this interesting.

**Comment by jar3817** [comment]
Slow is lame!

**Comment by jdolan** [comment]
I can't reproduce this :| For some reason, even with `r_programs 0` and the smallest `cl_view_size`, I can't get over 310fps, and the bug does not materialize. I can still take a crack at fixing it, but I may need some help.

**Comment by InFerYes** [comment]
What specs do you have? I could try to reproduce this if you can tell me what map allows for easy speed accumulation.

**Comment by jdolan** [comment]
I'm on a Macbook Pro Retina (late 2013). It's an i7 quad at 2.3, which, for some insane reason, isn't fast enough to get > 500fps under any circumstances. I'm guessing most desktop-flavor systems can hit > 500. Lemme know what you find. Also, if you are able to reproduce it, please add `pm_debug 1` to your console and then attach the log here :)

**Comment by jar3817** [comment]
I saw some slow down a while ago on my desktop. I could only run at 200
instead of 300. It was on tokay's a few months ago.

I have a brand new laptop that should be able to get the framerate that
high, I'll check it out when I get home tonight.

**Comment by jar3817** [comment]
I can confirm this on linux, between 500 and 700fps the max speed seems limited to around 200. At 1000fps limited to 100. You can briefly get more speed by strafe/circle jumping.

![quetoo006](https://cloud.githubusercontent.com/assets/4224353/16898142/7f53ea26-4b98-11e6-9746-c0a7219fa8ec.jpg)

![quetoo004](https://cloud.githubusercontent.com/assets/4224353/16898143/89567a98-4b98-11e6-8e0c-0f2ecdc1ac2d.jpg)

**Comment by jar3817** [comment]
oh and pm_debug 1 doesn't do anything, the player just says it

**Comment by jdolan** [comment]
Ah, sorry. `PM_DEBUG` is a macro that adds both client- and server-side debug messages for player movement. It looks like `PM_DEBUG` is `1` in the current builds, so simply setting `debug 1` at the console should produce some player movement information. However, I think the `cmd_t.msec` information for `Pm_WalkMove` is not currently printed. I'll make sure that it is.

**Comment by jdolan** [comment]
Also, I am able to reproduce this (sort of) on my Macbook. I can get up to about 325fps in some areas, and when I do, I've noticed that my maximum speed is about 285ups (just shy of 300). If I drop my framerate to under 300fps, I'm right back up to 300ups. So I can debug this locally 👍

**Comment by jdolan** [comment]
Side note, this is (in my estimate) a very old problem with either `cl_cmd.c` or `bg_pmove.c` that was masked for ages with the old `cl_max_pps` logic, which enforced a hard packet rate clamp of 120Hz. I removed that clamp over the winter to give the user more control over their actual packet rate, and my hunch is that is when this bug materialized. But the underlying cause is likely much older.

**Comment by jdolan** [comment]
@Panjoo

**Comment by jdolan** [comment]
Also, screw you guys and your 1000fps rigs. Must be nice :P

**Comment by jdolan** [comment]
Jesus Christ. So the fix here is that, sometime ages ago, I thought default values of `200` for `cl_foward_speed` and `cl_right_speed` looked silly, and `100` would be a much nicer round number. Turns out, for very high framerates, this matters a lot.

Several other fixes came out of this bug, tho:

 * We now have an 'immediate packet' trigger, so that jump or fire commands are sent to the server as soon as possible. This actually has a noticeable positive affect on firing at 60Hz refresh, even on a local server.
 * Some timestamp logic in `Cl_UpdateCmd` was clearly wrong.

**Comment by jar3817** [comment]
Dude, I had to go windowed at 300x200 to get that...

**Comment by Panjoo** [comment]
The first time I noticed the slower movement was some months ago when I mentioned to Jay that I couldn't do some of the trickjumps (eg. the strafejump from YA ladder to opening on fragpipe). 
But _the best map to reproduce the slow movement with high fps is slimyplace (dm7)_ which is the simplest in terms of layout and line-of-sight. Lol, I could barely jump across the little slime pit near the RA because of this. Glad you found the problem so quick:)
