### ISSUE TITLE
Game rules need controlling cvars

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo#14]
The following list of game specific things should be broken out into cvars that allow the server operator to control settings. This is a more full list then #209. We may not want all of these
-g_respawn_protection - default 0 - protection from inital damage after respawning, the value is delay before damage
-g_rounds - already exists but very buggy and doesn't work right (ammo spawns, and what to do when in DM for example).
-g_deadchat - 0|1- default 1 - whether dead players can type to live ones (mostly intended for conjunction with g_rounds and competitive play)
-g_deadhealth - 0|1 - default 1 - tells a player the health/armor of their killer

Clients should be able to set some specific to themselves as well
-cg_autoswap - 0|1|2 - default 1 - swap weapons on pickup according to the best weapons list on the server (1 being the server list, 2 being always swap to last picked up, probably not a popular option but might as well have it as one) 

Changed 13 months ago by jdolan

    g_spawn_protection Should introduce a new shell effect (yellow?) 

    g_rounds Actually is (and should be) independent of g_gameplay arena, which will disable item spawns -- so I don't think this is as much broken as it is just missing countdown sounds and other queues. 

    g_spectator_chat Good idea, we should leverage the team chat facilities for this. 

    g_show_attacker_stats Also a nice idea. 

    cg_switch_weapon I'm less inclined to care about this one, let's treat it as lower in priority than the rest. 

Changed 13 months ago by wickedshell

r1635 provides g_show_attacker_stats (which is a much better name then g_deadhealth) currently only provides health/armor of the attacker as we haven't built up any more complicated stat logging.
Changed 13 months ago by wickedshell

r1637 g_spectator_chat, renders dead_chat uneeded

r1642 g_respawn_protection defaults to 0, takes seconds

**Comment by kaadmy** [comment]
Isn't all this functionality existing now?

**Comment by jdolan** [comment]
Sure. Let's close this out. Specific new features should be tracked in new issues.
