### ISSUE TITLE
Player name in scoreboard sometimes shows as 'newbie'

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#140]
At some point, named players will begin showing up as `newbie` in the scoreboard. Not sure why.

**Comment by jdolan** [comment]
I looked at this for quite a while today. The scores themselves are transmitted in binary, and the client's name to draw is resolved from the configstrings (CS_CLIENT). So this might go quite a bit deeper..

If a player's userinfo fails to validate, they could receive the default userinfo, which would identify them as "newbie". We should keep an eye out for this happening again. I'm demoting this to a minor bug for now.

**Comment by jar3817** [comment]
I've never actually seen this in the wild before, but I'll keep an eye out
for it.

**Comment by kaadmy** [comment]
Shouldn't the userinfo just use the last available state instead of the default when recieving an invalid userinfo?

**Comment by jdolan** [comment]
Oh. You think what's happening is that the client sends the server an invalid userinfo and they then become "newbie"? Maybe. This might not be directly from that, tho. There is some inconsistency at play here. It's very rare, and I have not seen it in some time. If you can run multiple instances of the client locally, I'd love to know if you can reproduce this.

**Comment by kaadmy** [comment]
I haven't seen this for months either, should this just be closed until someone can reproduce it/find it?

**Comment by jdolan** [comment]
Nah. Minor bug is the correct designation. If we don't see it again before 1.0, so be it.
