### ISSUE TITLE
Modify the damage inflicted sound to vary with damage inflicted

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#143]

**Comment by InFerYes** [comment]
Is this a sound you hear when you hit someone regardless of distance, not the sound from the character? Quake Live has it in a few flavours, like high pitch/low pitch for high/low damage, or just a simple hitbeep regardless of damage. I kinda like it. Can it be made configurable?

**Comment by jdolan** [comment]
Yea, I think we need several different samples for the amount of damage inflicted, you're right.

**Comment by jar3817** [comment]
Make it a fart sound

**Comment by jdolan** [comment]
@Panjoo Would you want to provide different hit sounds for damage inflicted? I'd suggest 3 different sounds, but.. it could be your call.

**Comment by jdolan** [comment]
Done. Went with just hit_1 and hit_2. I think 3 would actually be weird / distracting.
