### ISSUE TITLE
Player swings weapon model far away from body when changing weapons

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#145]
I'm not exactly sure when this happened, but I'm fairly sure it wasn't always the case. When changing weapons, the animation swings the weapon far away from the player's body. It looks pretty ridiculous. This is in the 3rd person view. In 1st person view, it looks acceptable.

On a related note, I've noticed that this animation is *not* smooth or fluid in the 1st person view when running at higher `sv_hz` values. I think we need to enhance the way this animation is handled on the client. Maybe we need to scale the weapon model down towards 0 on the downswing, and up to 1.0 when the new weapon is raised? Something like that.

The best way to test this in with `cg_third_person 1`.

@jar3817 I assigned this to you, but feel free to kick it back my way if you don't feel like working on it.

**Comment by jar3817** [comment]
lol, it looks like the player is playing with a yo-yo

**Comment by jdolan** [comment]
Yea, I swear, it didn't always do this. But I have no idea when or how it broke.

**Comment by jdolan** [comment]
It affects qforcer and gork, so it's not the player model.. Some weapons are worse than others, tho, which leads me to believe it's something wrong with the `link.cfg`'s. Very weird.

**Comment by jdolan** [comment]
Some relevant bits from ioq3:
https://github.com/ioquake/ioq3/blob/master/code/cgame/cg_players.c#L1290

**Comment by jdolan** [comment]
@Panjoo When you fixed our model files, do you know if you updated the `link.cfg`'s? I wonder if that's all this is.. fixed weapon models with stale link.cfg files?

**Comment by jdolan** [comment]
I've figured out what's wrong and will be addressing this in the nuclear-option branch.

**Comment by jdolan** [comment]
Oh, @Panjoo it was nothing you did with the `link.cfg`'s. It's my shit code ;)

**Comment by jdolan** [comment]
The code fix for this is in, but link.cfg's and view.cfg's require tweaking. When the menus are ready to go, I'll get to that.

**Comment by jdolan** [comment]
Fixed.
