### ISSUE TITLE
No self damage is inflicted in duel mode

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#146]
@jar3817 Take a look at `G_Damage` in `g_combat.c`, like `221`. Some logic is needed there to account for `GAMEPLAY_DUEL`. Maybe something like:

    if (target == attacker) {
        switch (g_level.gameplay) {
            case GAME_DEATHMATCH:
            case GAME_DUEL:
                break;
            default:
                 dmg = 0;
                 break;
        }        
    }

Or the inverse of this.

**Comment by jdolan** [comment]
(I would have just fixed this, but I'm elbow deep in menus work, and was just browsing this code because it showed up in static analysis.)

**Comment by jar3817** [comment]
I voted for the inverse, makes more sense (to me) to make a special case for arena and insta...
