### ISSUE TITLE
Server is using protocol minor 1009

### ISSUE THREAD

**Issue by jbest2015** [jdolan/quetoo#147]
Hi I am trying to connect from my MAC to a Linux Server running quetoo-dedicated 
The client keeps dropping the following error. 

![image](https://cloud.githubusercontent.com/assets/16674743/17047301/a2c52a92-4f99-11e6-90e1-ff125f1b7d2e.png)

and this is the server side. 
xBIG connected                                                                                                                                                                                           x
xG_ClientUserInfoChanged: \active\0\message_level\0\name\BIG\rate\0\skin\qforcer/default\ip\50.183.201.35:37582                                                                                          x
xSv_New_f: 50.183.201.35:37582                                                                                                                                                                           x
xSv_ConnectionlessPacket: Packet from 50.183.201.35:44200: get_challenge                                                                                                                                 x
xSv_ConnectionlessPacket: Packet from 50.183.201.35:44200: connect                                                                                                                                       x
xSv_Connect_f: Svc_Connect()                                                                                                                                                                             x
xG_ClientUserInfoChanged: \active\0\message_level\0\name\BIG\rate\0\skin\qforcer/default\ip\50.183.201.35:44200                                                                                          x
xBIG connected                                                                                                                                                                                           x
xG_ClientUserInfoChanged: \active\0\message_level\0\name\BIG\rate\0\skin\qforcer/default\ip\50.183.201.35:44200                                                                                          x
xSv_New_f: 50.183.201.35:44200   

Thanks!

**Comment by jdolan** [comment]
Hi there,

Yep, you've caught us in a busy week, and I've not kept the Mac build up with the Linux and Windows builds. I will update the Mac build in just a few minutes. Standby ;)

**Comment by jdolan** [comment]
Should be all set! Please close this out if everything works for you. Thanks for trying Quetoo, and feel free to drop by #quetoo on Freenode as well.

**Comment by jbest2015** [comment]
HI Jay, I am sure this will work , thank you so much for all of your work on this, my friends and I in our late 20's and early 30's would play this all the time and I thought i would set up a server for fun. Real quick I made the mistake of exiting full screen on the MAC and now I have a screen that is 1pixel by 1pixel.I know there is a config file somewhere.. but I can't find it. Can you point me in the direction so I can delete it?

**Comment by jdolan** [comment]
Yes! That's another bug that should be fixed in the latest build, actually. But the file resides in `~/.quetoo/default/quetoo.cfg` -- that's `/Users/your_user/.quetoo/default/quetoo.cfg`

**Comment by jar3817** [comment]
You can also just launch from the command line with `+set r_fullscreen 1` option set...

**Comment by jbest2015** [comment]
All, thank you the new version works I did notice i had to implement the connect command as a string Connect "x.x.x.x" where as x.x.x.x worked previously. Not a big deal, I saw the issue. but in case some one else asked. Great work on the game, can't wait to play with my friends. Do you know a good place to find all of the old skins? we used to have some hillarious ones like a sheep with a rocket on it and homer... 
thanks again for your quick response!

**Comment by jdolan** [comment]
Haha, oh, I remember those skins..

Quetoo actually uses Q3 player models, tho, with a slightly modified animation definition. Adopting Q3 models to Quetoo is not hard. Take a look at `player-qforcer.pk3` and `player-gork.pk3` inside of `Quetoo.app/Contents/Resources/default`. They are just ZIP files.

**Comment by jbest2015** [comment]
Awesome, I will check it out, also I think you have the same problem with the Windows 10 build. I wish I was a better coder, I would help.
