### ISSUE TITLE
Player respawns with non 0 velocity they had when they died

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#148]
If you were stuck in a wall (or falling/shooting up) when you respawn you will still have a velocity component causing you to shoot up or down when you respawn.

**Comment by jdolan** [comment]
I can't reproduce this. I bound a key to `kill`, and killed myself while plummeting *down* onto the large `trigger_push` on Gehenna. This threw my corpse back up in the air. But by the time I could respawn, my velocity was zilch. Still going to put a fix in.

**Comment by WickedShell** [comment]
I was doing it by RJing on tokays to kill myself and respawning before I
hit the ground. I would spawn with my previous velocity and hit the ground
and take fall damage. Will test the fix in a bit.
