### ISSUE TITLE
Add "hand" CVAR_USERINFO for positioning the view weapon

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#151]
Seems it would be easy enough to add a `Y` translation on the view model of `6`, `0` or `-6` based on the value of a cvar. We'd have to update the game code so that `G_InitProjectile` took this into account. Players could even setup binds to quickly change this, enabling them to fire around corners, etc.

**Comment by WickedShell** [comment]
cg_draw_weapon_y or some such does this already doesn't it?

**Comment by jdolan** [comment]
It does, but that's more of a developer tool for tweaking `view.cfg` It does nothing server-side to change the origin of your projectiles, which is what's really needed to make this feature look and behave as expected.

**Comment by jdolan** [comment]
Donez0r.
