### ISSUE TITLE
Re-introduce pak command line utility

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#153]
There's no option for Mac and Linux users to manipulate legacy game data files. We used to have one, but I threw it away when we moved to PhysicsFS. It wouldn't be that hard to re-introduce it, using PhysicsFS (I think?).

Here's the old code:
https://github.com/jdolan/quetoo/blob/6de5f55175ee326b97204cf32877529cc785be87/src/tools/pak/main.c
https://github.com/jdolan/quetoo/blob/05696bf7c6a2da4b39c2991cd17ea1e008047619/src/pak.c

**Comment by kaadmy** [comment]
Is  this still a wanted feature or is it unnecessary now?

**Comment by jdolan** [comment]
It's ultra low priority. We don't deal in pak, really, but we do support it, because PhysicsFS gives it to us for free. A few times a year, I find myself wanting or needing to peek inside a legacy Quake2 .pak file, and wish that we still had that tar-like executable I wrote years ago.

This should be like, last priority. We should focus on all issues labeled 1.0-release, then all major bugs, and then look at enhancements.

**Comment by jdolan** [comment]
PhysicsFS actually comes with `test_physfs` that does this (and then some). Closing this out.

**Comment by kaadmy** [comment]
PhysFS actually supports almost any archive types, include Descent data files, Quake1/2 .pak files, Doom WAD files, etc.

I think it still has to be enabled when initializing PhysFS data paths though.
