### ISSUE TITLE
Lighting and texture alignment bugs

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo#16]
Lighting and texture alignment, especially for non-axial surfaces, is not very reliable at all. This could have something to do with negative angle values? 

Changed 15 months ago by jdolan

```
priority changed from major to minor
```

Downgrading to minor. There are only two instances of this on all of our maps (Aggressor and Fractures each have one -- both on similar sloped-ceiling brushes. It's possible to work around the problem by adjusting the textures in Radiant, so I'm not sure we need to focus on this bug right now.

**Comment by jdolan** [comment]
This is actually fixed now, since we moved to texture matrices with code adopted from EricW's tools.
