### ISSUE TITLE
Player and corpse bounding boxes are not clipping correctly

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#160]
Collision with projectiles, and possibly (probably?) with other players is incorrect. Hopefully this is just a matter of bounding boxes not being set correctly.

**Comment by jdolan** [comment]
![quetoo009](https://cloud.githubusercontent.com/assets/643118/18609928/39760d16-7cdc-11e6-8e26-2383d8fff597.jpg)

New cvar `r_draw_entity_bounds` and major protocol change to send over bounding boxes for all mesh entities reveals that the bounds are correct. There's something else going on here.

**Comment by WickedShell** [comment]
Still a nice debug tool!

**Comment by jdolan** [comment]
This is halfway fixed. Projectiles now use a new solid type, `SOLID_PROJECTILE`, which encapsulates similar logic to Quake2's old `SVF_DEADMONSTER` hack. That is, projectiles can interact with `SOLID_BOX` (players) without clipping their movement.

What is still broken is hit-scan weapons. See #172.

**Comment by jdolan** [comment]
\o/ fixed.
