### ISSUE TITLE
Weapon delay problems

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#162]
Firing a weapon that has a delay time you can swap away from the weapon and it will still shoot after the timer has expired, even if the player has died or is on a different weapon.

Firing should block weapon swaps as well.

**Comment by jdolan** [comment]
Yep, this is a good one.

**Comment by jdolan** [comment]
I disagree with disabling weapon swaps. So right now, you can prime your BFG, but then change weapons. The fire sound is not heard. 

I like to think of it has holding down a long trigger on the BFG: if you die, it doesn't go off. If you stop holding the trigger (by changing weapons), it also doesn't go off.

**Comment by WickedShell** [comment]
It's a bit weird as you can prime the BFG before going around any corner with impunity but not waste the ammo. I'm of the opinion it should lock you into shooting it, and if you die it should emit a explosion in place (messed up firing sequence).

Also it's hard to address the swap thing if you fix it while I'm still trying to get a server to compile :D

**Comment by jdolan** [comment]
We're talking about a 1s priming interval. Not a lot of time to change your mind unless you're already looking at the opponent. I'm inclined to call this one fixed.

**Comment by WickedShell** [comment]
I can just see it being like q1 where everyone runs around with the shotgun out all the time except when firing so that they don't drop a better weapon :) I'm happy to try it first, as long as it doesn't shoot after a swap (or a swap and swap back) I'm fine with it :)
