### ISSUE TITLE
Allow giblets, corpses and nades to use teleporters

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#163]
Nade's should be able to teleport like people. Maybe rockets as well, although that one seems a bit more abuse prone?

**Comment by jdolan** [comment]
Agreed on 'nades, and agreed on not rockets.

**Comment by jdolan** [comment]
A check on `G_IsMeat` could allow gibs and corpses to pass through. Delta angles would have to be applied manually.

**Comment by jdolan** [comment]
Attached is a little .map for testing this out. It works well! I tried adding support for grenades, but I can just see this getting abused way too much. Jump pads are one thing.. Also, it was very strange to be able to shoot a grenade through a teleporter, but not a rocket. Felt inconsistent. So the code now allows for giblets and corpses to pass through. Funny as hell.

[teletest.map.zip](https://github.com/jdolan/quetoo/files/490716/teletest.map.zip)

**Comment by WickedShell** [comment]
Fair enough, darkzones is inconsistent, one teleporter allows shooting
rockets through it and hitting players on the other side, the other one
causes then to explode in contact instead of traveling through and hitting
the player on the far side

On Sep 23, 2016 14:28, "Jay Dolan" <notifications@github.com> wrote:

Closed #163 <https://github.com/jdolan/quetoo/issues/163>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/jdolan/quetoo/issues/163#event-800986397>, or mute the
thread

**Comment by jdolan** [comment]
Thanks for pointing that out. I went ahead and fixed Dark Zone. In the future, if you wouldn't mind logging issues for these follow-up issues, that'd be a big help. Thanks again.

**Comment by WickedShell** [comment]
Yeah, was out flying a plane though, email was easier :) but wilco
