### ISSUE TITLE
Rocket effects are too small

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#164]
Rocket trails look to much like a blaster (and are actually a skinnier trail) which makes it hard to distinguish which is coming at you (a larger rocket model might help as well), and the explosion effect needs to cover a larger area to both give you a better sense of where the damage is occurring as well as giving it more weight. The damage it does is all out of proportion to the visual impact of the rocket.

**Comment by Panjoo** [comment]
^ Agreed :)
And the newer sound is nice in itself but it does feel a bit tame now. I think it would be better if the rockets sound like they have some more explosion force behind them.

**Comment by jdolan** [comment]
CC @anthonywebb1

**Comment by jdolan** [comment]
I think there's an issue with the particle effects in general and network latency. The effects become very sparse the worse your connection is. I think that alone would alleviate this issue.

I pushed a commit that makes the smoke trail more visible, which definitely helps discern rockets from blaster projectiles. I think the larger issue here is the particle trail diminishing with lag.

CC'ed Anthony in case he wants to tune the RL fire sound some more.

**Comment by anthonywebb1** [comment]
Hi Jay


I'll take a look at this when I can, I was thinking that the RL sounds a bit quiet too, so I was planning on adjusting it anyway.


Unfortunately my audio interface decided to completely die, meaning I can't do any more work until the new one arrives on Monday [☹]


________________________________

**Comment by kaadmy** [comment]
Heh, we both reverted to the same commit.
Is the visual half okay now with 3485815?
