### ISSUE TITLE
No package 'ObjectivelyMVC' found

### ISSUE THREAD

**Issue by tapir** [jdolan/quetoo#167]
The build instructions are out of date.
`./configure --prefix=/usr` gives the error in the title.
I think this should be included in the source since no distro will have that package.

**Comment by jar3817** [comment]
I built it last night without an error...

**Comment by tapir** [comment]
What I mean is that, it's not documented that Objectively and ObjectivelyMVC should be installed anywhere

**Comment by jdolan** [comment]
Right. We *just* merged the new menus (which introduced the dependencies on Objectively and ObjectivelyMVC) this week. I agree that we need some documentation to reflect this. We will not be including them in the source tree, tho.

**Comment by tapir** [comment]
That's a shame since anybody willing to compile quetoo now has to compile 2 more libraries beforehand. Anyway I'm creaying AUR packages right now for making it easier for at least arch users.

**Comment by jdolan** [comment]
Awesome! Thanks for packaging these. Objectively and ObjectivelyMVC are reusable, general purpose libraries. I'd rather encourage the packaging of them by distros, than bundle them in the source. That said, maybe we could add some `./configure` magic that looks for them and, if not installed, fetches them via Git submodules?

**Comment by tapir** [comment]
Objectively and ObjectivelyMVC are successfully built with these PKGBUILDS
https://aur.archlinux.org/packages/objectively-git/
https://aur.archlinux.org/packages/objectivelymvc-git/

Though, I'm having this error while compiling quetoo from git:
```
/usr/bin/ld: ../client/.libs/libclient.a(libviewcontrollers_la-MainViewController.o): undefined reference to symbol '_cast'
/usr/lib/libObjectively.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Any ideas?

**Comment by tapir** [comment]
A quick google search shows this has something to do with the order of the linked libraries. So it's possible that it should be fixed from autoconf files.

**Comment by jdolan** [comment]
Strange! I've never see that error anywhere before, nevermind with Quetoo. I looked at your Pkgfile and it looks perfectly sane / vanilla. I'm stumped!

**Comment by jdolan** [comment]
Okay, I see this: http://stackoverflow.com/questions/19901934/strange-linking-error-dso-missing-from-command-line

**Comment by tapir** [comment]
So from what I understand it's looking for the symbol '_cast' and it can't find it because the link order is not correct.

**Comment by jdolan** [comment]
Maybe it's because I'm not even explicitly adding -lObjectivelyMVC, let's try that.

**Comment by jdolan** [comment]
See 57c5493.

**Comment by jdolan** [comment]
(It's really strange that OS X, Fedora and Debian don't have this issue -- not even MinGW-w64 on Fedora has any problem linking Quetoo.)

**Comment by tapir** [comment]
Unfortunately didn't fix the problem.

**Comment by tapir** [comment]
I'm also concerned about this line `/usr/lib/libObjectively.so.0: error adding symbols: DSO missing from command line` why is there a libObjectively.so.0 error? Maybe something wrong with the compiled so library?

**Comment by jdolan** [comment]
This is really strange, tho. Why haven't we seen this on any other system? What compiler are you using?

**Comment by jdolan** [comment]
Also, the fact that ObjectivelyMVC built and linked against libObjectively.so implies that Objectively is fine. Just curious, did you try building and running the Hello example in ObjectivelyMVC?

**Comment by tapir** [comment]
I'm using gcc 6.2.1 
I'll try to build the Hello example

**Comment by tapir** [comment]
Tried to build Hello app with this
```
gcc -o hello Hello.c HelloViewController.c -lGL -lGLU -lSDL2 -lObjectivelyMVC
```
I get this error
```
/usr/bin/ld: /tmp/ccLuJ7Wa.o: undefined reference to symbol '_Date'
/usr/lib/libObjectively.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
Then I try this
```
gcc -o hello Hello.c HelloViewController.c -lGL -lGLU -lSDL2 -lObjectivelyMVC -lObjectively
```
And it compiles successfully.

BUT... The app segfaults with `INFO: View:bindView: Instantiating View of class Panel`

**Comment by jdolan** [comment]
Okay. I've made a couple fixes to the Pkgconfig files for Objectively and ObjectivelyMVC based on your findings. This is helpful. Thanks for putting up with it.

I'm hoping that the crash you're seeing in the example is indicative of something simple, and not some strange bug unique to GCC 6.x.

Any chance you could run it in `gdb` and post a backtrace? Also, it might be time we move this issue to the ObjectivelyMVC Issues list.

**Comment by tapir** [comment]
Now it compiles and works. Thank! I'll close this and come up with a backtrace for mvc
