### ISSUE TITLE
func_plats are blocked by players when they should crush them

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#170]
Really noticeable on Edge.

**Comment by Panjoo** [comment]
Ehm? Do you mean that if a player gets in between the ceiling and the lift or under the lift when it comes back down, it should keep pressing until the player moves away or even until he dies? 
On the q2 dm maps the lifts are not supposed to crush you but just move back up so you can deny players from dropping down the shaft, it's a tactical thing. I wouldn't change that behaviour as it's always been like this on The Edge and other maps like Tokays. Imagine that the lift in the Red Armor room on The Pits would crush you, then you can no longer try to prevent opponents from dropping down after you and keep them out of that room.

**Comment by jdolan** [comment]
👍 I think the plats are not even attempting to come down / inflict damage, even when they are set to. I'm with you, tho.

**Comment by WickedShell** [comment]
The real problem is that you can shoot yourself into a wall, then the plat
won't move as it can't push you. At a minimum we should cause damage here
to get out of the situation, but we really just need to avoid it. The
collision stuff is the real source of this one.

**Comment by jdolan** [comment]
Okay, so collision bugs aside. Assuming the plats collided correctly with players, and could push them or inflict their configured damage, what's wrong here? Is it that the `func_plat`s on Edge do not inflict damage? (They are not set to in the entity definition). Is it that `func_plat`s should crush / kill `CONTENTS_DEADMONSTER`? What's the fix here?

**Comment by jdolan** [comment]
I'd argue that giblets should never block a func_plat *unless* that giblet is actually the dead client (gibbed and not yet respawned). Corpses, on the other hand, could / should block a func_plat. It's up to the other players to obliterate that corpse.

**Comment by WickedShell** [comment]
I'd think the plat should smash the corpse into a beautiful pile of gibs!
(If the lift is commanded to move).

I think the giblets need to be consistent though, IE there shouldn't be one
special one that blocks a plat. The plat should just pulp the giblet into
blood, if the giblet was the player respawn them in the end map view as
spec or something until they command a respawn.

The only time I think you should incur damage from the plats really is if
they are trying to move and you are blocking them. IE you get your head in
the way and it can't finish it's push to the spot, you should take damage
while blocking it, or the plat is designed to push flat into the ceiling or
similar.

**Comment by jdolan** [comment]
Fixed. Plats decimate corpses and giblets. If a client is bound to a giblet (not yet respawned), they are made `SOLID_NOT` after blocking the platform.
