### ISSUE TITLE
Sound spatialization code still sucks

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#171]
The sound mixing is fucking horrible. Either rewrite it, or replace it when OpenAL.

**Comment by tapir** [comment]
:+1:  for OpenAL. Good 3D mixing is a very hard job to do correctly.

**Comment by jdolan** [comment]
I found some definite bugs here around channels never being freed up for new voices to play on them. With some initial play testing with 5 players, I didn't notice any missing samples. Marking this one fixed. We can revisit OpenAL when we have time / specific interest in it.
