### ISSUE TITLE
Players interpentetrate

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#172]
No telefragging, if 2 clients jump at each other they will hang in air where ever they meet, even if the ground isn't there. When they randomly slide apart one player can be pushed into the floor.

**Comment by WickedShell** [comment]
Demo from KaadmY https://usercontent.irccloud-cdn.com/file/XmiquUz2/collisionbug_1.demo

**Comment by jdolan** [comment]
Yea, I spent a while tracking this one down tonight. I *think* that this one, and the quirky behavior of hit-scan weapons only impacting the lower half of players, are related. Specifically, I think there is something wrong with `Cm_InitBoxHull`, `Cm_SetBoxHull`, or `Cm_TransformedBoxTrace`. Is this something you could take a look at?

**Comment by jdolan** [comment]
Here's the rev where this shat the bed: 16cc24165a4fcb3129b810306b53159df0106c22

**Comment by jdolan** [comment]
@WickedShell please re-test. This is fixed now.

**Comment by jdolan** [comment]
Aside from minor pmove issues with respect to standing on each other's heads and crouching, I don't see this as a bug anymore. Closing.
