### ISSUE TITLE
Player box is to big

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#173]
Players can be considered standing on a ledge when their entire model is in free space

**Comment by jdolan** [comment]
I know, but we're using Quake2's bbox. Changing the bbox is a huge fail, trust me. Btw, on an offline server (`sv_max_clients 1`), you can now see exactly what the bbox looks like with `r_draw_entity_bounds 1`.

**Comment by jdolan** [comment]
We're just not going to fix this, sorry.
