### ISSUE TITLE
Collision bug

### ISSUE THREAD

**Issue by tapir** [jdolan/quetoo#176]
Here is a demo I've recorded on a test map
[collision_bug.demo.zip](https://github.com/jdolan/quetoo/files/478483/collision_bug.demo.zip)

Player sticks to the walls

**Comment by jdolan** [comment]
Yep, we're well aware ;)

**Comment by jdolan** [comment]
I think this is actually fixed in the latest build. Please retest!

**Comment by tapir** [comment]
It's actually worst now. It doesn't slide at all. The player is forever stuck
[collision.r2758.demo.zip](https://github.com/jdolan/quetoo/files/478600/collision.r2758.demo.zip)

**Comment by jdolan** [comment]
I don't have your `test.bsp` :)

**Comment by tapir** [comment]
ahh sorry I knew I forgot something. Will send it tomorrow

**Comment by jdolan** [comment]
We did some play testing this evening after a major collision fix (4701bac) and there were no hangups / weird clipping issues. Could you please re-test this and let us know if it's fixed for you?

**Comment by jdolan** [comment]
I'm actually going to close this out as it is a duplicate of #149. Also, I can still get stuck in a few very select places (e.g. lava pit in middle arena of The Frag Pipe). So this issue is still valid, but let's track it in that older ticket.
