### ISSUE TITLE
Windows updater fails to run on paths with spaces (e.g. C:\Program Files\Quetoo)

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#177]
Not sure how `cygwin` / `rsync` handle quoting, but we should figure this one out.

**Comment by jdolan** [comment]
Just doing a little reading.. it sounds like, even tho we're passing `argv` to the process explicitly, we still may have to quote paths that contain spaces. I think we could just always quote the target directory.

**Comment by jdolan** [comment]
@WickedShell could you update your install, then try moving your install to `C:\test spaces\Quetoo` and run the new updater? I'd like to make sure we're okay in e.g. `C:\Program Files\Quetoo`.

**Comment by WickedShell** [comment]
Works. The updater not updating itself needs to be addressed, will open an issue.
