### ISSUE TITLE
Windows build fails to start

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#179]
It looks like, at least on some systems, MinGW's onexit wrapper is unhappy. This mechanism is used by Objectively to teardown the class hierarchy when the application terminates:

```
Starting program: C:\Users\jay\Desktop\Quetoo\bin\quetoo.exe
[New Thread 2900.0xa48]
[New Thread 2900.0x9a4]
[New Thread 2900.0x310]
[New Thread 2900.0xcfc]
warning: HEAP[quetoo.exe]:
warning: Invalid address specified to RtlSizeHeap( 0000000002DD0000, 000000000010ED30 )

Program received signal SIGTRAP, Trace/breakpoint trap.
0x00007ff8c7cdfa56 in ntdll!RtlpNtMakeTemporaryKey () from C:\Windows\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ff8c7cdfa56 in ntdll!RtlpNtMakeTemporaryKey () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00007ff8c7cb1075 in ntdll!memset () from C:\Windows\SYSTEM32\ntdll.dll
#2  0x00007ff8c7cdf7c0 in ntdll!RtlpNtMakeTemporaryKey () from C:\Windows\SYSTEM32\ntdll.dll
#3  0x00007ff8c799a620 in msvcrt!.dllonexit () from C:\Windows\system32\msvcrt.dll
#4  0x000000006c28c91d in mingw_onexit () from C:\Users\jay\Desktop\Quetoo\bin\libObjectively-0.dll
#5  0x000000006c28c979 in atexit () from C:\Users\jay\Desktop\Quetoo\bin\libObjectively-0.dll
#6  0x000000006c28ca09 in __do_global_ctors () from C:\Users\jay\Desktop\Quetoo\bin\libObjectively-0.dll
#7  0x000000006c28136a in __DllMainCRTStartup (hDllHandle=0x6c280000, dwReason=1, lpreserved=0x25afb00)
    at ../crt/crtdll.c:200
#8  0x00007ff8c7c04fc8 in ntdll!RtlActivateActivationContextUnsafeFast () from C:\Windows\SYSTEM32\ntdll.dll
#9  0x00007ff8c7c61d7a in ntdll!RtlAreBitsSet () from C:\Windows\SYSTEM32\ntdll.dll
#10 0x00007ff8c7c61bbf in ntdll!RtlAreBitsSet () from C:\Windows\SYSTEM32\ntdll.dll
#11 0x00007ff8c7c61bdd in ntdll!RtlAreBitsSet () from C:\Windows\SYSTEM32\ntdll.dll
#12 0x00007ff8c7c7fd6d in ntdll!EtwEventProviderEnabled () from C:\Windows\SYSTEM32\ntdll.dll
#13 0x00007ff8c7cb14f3 in ntdll!memset () from C:\Windows\SYSTEM32\ntdll.dll
#14 0x00007ff8c7c66a0e in ntdll!LdrInitializeThunk () from C:\Windows\SYSTEM32\ntdll.dll
#15 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)
```

**Comment by jdolan** [comment]
Took this one to StackOverflow:
http://stackoverflow.com/questions/39560050/mingw-cross-compiled-application-atexit-mingw-onexit-crashes-on-windows-10

**Comment by jdolan** [comment]
I think it might depend on which flavor of the MSVC runtime your system has on it. I can't think of why else this would work for some people and not for others.

**Comment by jdolan** [comment]
CC @Paril @tapir

**Comment by tapir** [comment]
Update on this: I can now run windows build fine except when I try to run in under gdb, it crashes with the backtrace above.

**Comment by Paril** [comment]
Reproduced on the Ming build but does not happen on MSVC. Really can't explain this one. I have a feeling it might be GCC-related based on the Googling I did, but definitely way out of my expertise here.

**Comment by jdolan** [comment]
Crazy idea.. Using clang instead of GNU gcc for the MinGW build?

**Comment by tapir** [comment]
I tried it briefly. Got it to compile OK without much hacking after Paril's msvc updates

**Comment by jdolan** [comment]
I wonder if it's less-crashy when built with clang. That's the question. Unfortunately, that might also preclude us from cross-compiling, so it's not a whole lot better (for me) than the Visual Studio approach (that is -- I can't run a build easily).

**Comment by tapir** [comment]
2 weeks ago there were no more crashes for me on the mingw build. I could debug, start, quit without heap corruption. Did the situation change? Didn't test on windows for a while

**Comment by jdolan** [comment]
I have no idea, but that's great news. I guess if we can get a small consensus @WickedShell @Paril @Panjoo if the MinGW build is now stable, we could close this one out.

I'd like to continue to offer both builds (MinGW and VS) on the website, and push people towards VS. But the MinGW will be our fallback.

**Comment by Paril** [comment]
So long as we have AppVeyor working and somebody to update project files, shouldn't be too difficult to keep the VS build up to date.

**Comment by jdolan** [comment]
Closing this out for now. If new reports of the crash on start show up, we'll reopen.
