### ISSUE TITLE
Windows: net_interface doesn't select a working interface

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#182]
If there are multiple connected adapters then the network won't always work if the wrong one is selected. I'm not sure if there is a way to ask windows which one is connected or not though.

A easy workaround would be to try to reach the master server, if no response after 2 seconds, try the next connected interface etc.

Marking as major, as this is a really subtle bug on Windows that isn't obvious to the user whats happening.

**Comment by jdolan** [comment]
I like the idea. Why not broadcast to master on all interfaces, and see which one comes back [first]?

**Comment by WickedShell** [comment]
Sounds even better, I'm not sure from a code side how the interfaces are
found at the moment but this is definitely the better approach.

**Comment by jdolan** [comment]
I realized this morning that we were passing `""` to `Net_Socket`, from `Net_Config`. I've fixed this so that, if `net_interface` is not set, it will pass `NULL`, which will result in binding the socket to any / all interfaces. Could you re-test? I bet this is fixed.

**Comment by WickedShell** [comment]
That fixes the bug :)
