### ISSUE TITLE
On Windows, when Keys menu is open the game exits on ` (backquote) followed by Escape.

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#188]
Probably different key combination on a Mac, but when I'm in the Keys menu and hit ` (backquote or ~tilde) and then Escape the game exits, no warnings or errors just exits. Only happens while the Keys menu is open. Like magic!

**Comment by jdolan** [comment]
Sounds like a crash! Thanks!

**Comment by jdolan** [comment]
This doesn't happen on OS X or Linux. @Panjoo are you still seeing this crash?

**Comment by Paril** [comment]
The issue here is heap corruption, potentially of BindTextView. On MSVC, this menu crashes in View::updateBindings here:

`	free(textView->defaultText);`

**Comment by jdolan** [comment]
Er, okay. Is `free(NULL)` a crash case on Windows?

**Comment by jdolan** [comment]
@Paril do you mind testing the potential fix I pushed for this?

**Comment by Paril** [comment]
Freeing null is not a crash case - however, calling free() instead of g_free() when you request memory from glib -is- a crash case ;)

**Comment by jdolan** [comment]
Ah, yes indeed.

**Comment by jdolan** [comment]
Great catch. That is fixed now. Please re-test when you have a chance.

**Comment by Panjoo** [comment]
> @Panjoo are you still seeing this crash?

No :+1: 
I really tried hammering on those buttons to make it choke but it just wouldn't crash anymore!

**Comment by jdolan** [comment]
Woo!
