### ISSUE TITLE
Rocketjump has too much supa powaz now that air friction has been reduced:)

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#189]
I mean, on Tokays I could even rocketjump from the lower GL all the way up to the SSG bridge!

**Comment by WickedShell** [comment]
Related note: Hyperblaster climb should cause some self damage

**Comment by jdolan** [comment]
Yea, sorry. Will fix :)

**Comment by jdolan** [comment]
@WickedShell separate ticket if you want that plz.

**Comment by jdolan** [comment]
@Panjoo I dropped self-knockback gain from `1400` down to `1200`, and other-. Q2 used `1000`. This makes our RJ's feel a little more like Q3, which I always thought were better.

I've also increased the knockback your damage has on other players, from Q2's `500` to `800`. One of my favorite aspects of Quake / QuakeWorld gameplay was landing a rocket at someone's feet, and seeing them get tossed into the air. Such good fun.
