### ISSUE TITLE
Windows build crashes in certain map areas

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#192]
@WickedShell was able to consistently crash the x86_64 build by entering the lower room on _Stress Fractures_. @anthonywebb1 is able to consistently crash it by leaving the main outdoor area on _Lava Tomb_. We don't have backtraces for their crashes yet.

CC @Paril @tapir

**Comment by tapir** [comment]
I could only reproduce this with Nvidia GPU. When switch my laptop to intel I don't get an crashes. Can you confirm this @WickedShell @Paril @anthonywebb1 ?

**Comment by jdolan** [comment]
That's like.. the worst news I've heard all day. LOL. ;)

**Comment by WickedShell** [comment]
GeForce 760 for me.

**Comment by anthonywebb1** [comment]
Crashes occur using a Geforce 970 for me.

**Comment by jdolan** [comment]
Can you guys try disabling GLSL in the game? At the console, type

    r_programs 0
    r_restart

And see if this crash still occurs?

**Comment by WickedShell** [comment]
No problem with r_programs 1. Do we have reports of NV hardware working on
these maps under Linux? (Wondering if I can get a trace out of that)

**Comment by tapir** [comment]
works with r_programs 0 :+1:

**Comment by anthonywebb1** [comment]
This did seem to work, on Lava tomb I was able to leave the spawn area, but it did eventually crash after a few minutes of walking around the map. Fractures works fine.


I still get quetoo.exe has stopped working when I close the game.


The main problem I'm having now is getting the game to launch. Most of the time I just get a 0xc0000142 error message, but occasionally it launches normally. Very strange!


________________________________

**Comment by jdolan** [comment]
@anthonywebb1 So as to not derail your work -- I don't want to waste your time -- could you give the i686 build a test drive? While the x86_64 build also crashes on my Win10 VM, the i686 build runs.

**Comment by jdolan** [comment]
You can actually "convert" your 64 bit install into i686 by downloading the i686 snapshot from the website, and extracting it over your 64 bit install. Then run quetoo-update.exe. I *think* that will work, and save you the time of re-downloading the data. If it fails, I guess just install i686 in its own folder and update from there.

**Comment by jdolan** [comment]
@WickedShell I will test these maps in Debian on VirtualBox. My Macbook has an NVidia GPU. Not a very scientific test, but maybe it'll tell us something.

**Comment by anthonywebb1** [comment]
No problem, I'll let you know what happens


________________________________

**Comment by anthonywebb1** [comment]
OK, this runs perfectly. No crashes while playing and no problems launching the game. Still have the quetoo.exe has stopped working message when closing the game though.

________________________________

**Comment by WickedShell** [comment]
@anthonywebb1 is this perfect with shaders enabled?

**Comment by anthonywebb1** [comment]
@WickedShell sorry, not sure how to enable sharers! What do I need to do?

**Comment by WickedShell** [comment]
@anthonywebb1 

r_programs 1
r_restart

Basically the reverse of jdolans test

**Comment by anthonywebb1** [comment]
@WickedShell @jdolan OK, yes unfortunately it still crashes on Lava Tomb and Fracture with shaders enabled.

**Comment by WickedShell** [comment]
I'm trying to test my Linux machine with NV hardware but can't get it
compiled :(

**Comment by WickedShell** [comment]
Confirmed as not a problem for a NV linux machine.

**Comment by Paril** [comment]
Cannot reproduce with Visual Studio build, but I am on AMD which did not report issues. If I can source an nVidia card to test with this I will.

**Comment by jdolan** [comment]
Could someone with an Nvidia card please retest _all_ builds (MinGW i686 and x64, and VS i686 and x64) and provide an update / some feedback specifically around this crash? The renderer has been completely refactored to be OpenGL 2.0 compliant, and so there's a decent chance that this crash is gone.

**Comment by tapir** [comment]
I will do so monday when I have access to my windows machine :+1:

**Comment by jdolan** [comment]
Thank you thank you!

**Comment by tapir** [comment]
I can't reproduce crash on fractures anymore. Yay :100: 
If we get an extra confirmation we can close this.

**Comment by jdolan** [comment]
I'm closing this out for now. I think @Paril nailed it.
