### ISSUE TITLE
CGame: Allow using the cg_draw_frags/deaths/capture to control the sort

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#199]
Currently if you disable a item on the HUD the others will sit in place. It would be nice to shift the items up (if the user messes with cvars) to control where items are drawn. (Alternatively maybe we should be using the MVC to do HUD layout?)

**Comment by jdolan** [comment]
Yea, eventually I would like to replace all 2D elements with ObjectivelyMVC. The console, the HUD, everything. The cgame could create it's own Views and ViewControllers, and inject them into the MainVC, etc. It'd be tight. Probably not for 1.0, tho.

**Comment by jdolan** [comment]
Honestly, this is such a low priority at this point, I'm going to close out. Very few users will play with these cvars at all. It's not the end of the world if the HUD elements don't slide around to accommodate each other.
