### ISSUE TITLE
quemap needs an icon

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo#20]
artwork plzkthx

**Comment by jdolan** [comment]
Assigning to Pan since he's putting the finishing touches on our new logo, which will become the game icon I imagine.

**Comment by jdolan** [comment]
I'm actually going to close this. Quemap can't successfully be invoked from the Windows GUI. And it will only ever be invoked by a very small subset of our users. And when they do invoke it, it will likely be through GtkRadiant. Creating an icon for quemap.exe just isn't a priority.
