### ISSUE TITLE
Teleporter in mega room in darkzone is solid

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#200]
Self-explanatory. Rockets and whatnot will explode on it, but on the other side they pass through the teleporter. Appears that it was made solid.

**Comment by jdolan** [comment]
This is actually fixed as of last night. Pull! :)

**Comment by jdolan** [comment]
Btw for future reference, map-related bugs (especially ones that are truly maps and not code) belong in quetoo-data. But thank you for logging an issue!

**Comment by Paril** [comment]
Oh right, we have separate repos, whoops!
