### ISSUE TITLE
Tilde sometimes causes a write of backtick to the console

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#201]
Hitting tilde (on MSVC build, at least) causes a backtick to get written to the console almost every time. It seems that after the text input is initialized, it immediately registers a text input event for the backtick.

**Comment by WickedShell** [comment]
Same for the normal windows builds,a non problem on Linux however

**Comment by jdolan** [comment]
I moved the call to SDL_FlushEvent up in Cl_SetKeyDest. Hopefully that does the trick. Could you please retest?

**Comment by tapir** [comment]
Still happens for me

**Comment by Paril** [comment]
commit 355916d0059cd92f2c1c176554275ebff1867b2b did not fix it.

**Comment by jdolan** [comment]
Weird! I guess once we have a reproducible Windows build, we can investigate this more easily that way. I don't wanna continue stabbing in the dark.

**Comment by tapir** [comment]
Confirmed 959df6e fixed it.

**Comment by Panjoo** [comment]
I downloaded this snapshot, don't know if it's up-to-date  -> http://quetoo.org/files/Quetoo-BETA-i686.zip

Unzipped and replaced, then ran quetoo-update.exe
**Still seeing the backtick thing, and also the crash on quit :/......**

Maybe the link hasn't been updated yet?

**Comment by jdolan** [comment]
There should be a date stamp in the Quetoo console indicating when the executable was built. Is yours from October 2nd?

**Comment by Panjoo** [comment]
Quetoo 0.1.0 Oct 3  2016

**Comment by tapir** [comment]
Can't reproduce on that same build. Does it happen every time?

**Comment by tapir** [comment]
Maybe we should still disable TextInput at the start of the game. Just in case.

**Comment by Panjoo** [comment]
Sorry to have to reopen this. 
Damnit, I was hoping the latest updates would finally fix this but it's still happening. It's not just on hitting the tilde key, it writes that damn backtick thing at the start of anything I type and it never stops being incredibly annoying.

(i686 MingW32 xp,vista,w7)

**Comment by jdolan** [comment]
I don't suppose you could make a short video showing this? Just to see the timing of it, etc..

**Comment by kaadmy** [comment]
Yeah, Home/End go to the console backlog's top/bottom.

**Comment by jdolan** [comment]
@Paril Do you mind taking a look at this? I would imagine, since it's SDL, that it's the same on MSVC as it is with MinGW.

**Comment by MrSchism** [comment]
I can't seem to reproduce this on the current (Win64 0.1.0 MSVC 1900).  I've been attempting to get it to pop for a couple days now with no luck.

**Comment by kaadmy** [comment]
@MrSchism Only some people have managed to reproduce this, and some of the patches _did_ fix this bug for some people, it seems very random.

**Comment by MrSchism** [comment]
From just looking at the video, It seems to be buffering the keystroke while initially blocking it (to open the console).  The next key to enter the buffer just kinda drags it out on printing out to the console.

**Comment by jdolan** [comment]
The video itself might even be outdated, in terms of what's happening.

This is now specific to the MinGW build, and possibly to Win7 pre-SP1. If you have an older Win7 VM or a WinXP VM, honestly that's probably going to be the easiest / only way to practically reproduce this bug.

Might be less trouble to just mail @Panjoo a Win10 license ;)

**Comment by jdolan** [comment]
@MrSchism We do drain any pending text events when opening the console or chat, tho :/

**Comment by MrSchism** [comment]
@jdolan This may make things easier for testing:

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by Panjoo** [comment]
I don't know what the cure was but I just noticed that the _'Tilde causes a write of backtick to the console'_-thing seems to have been taken care of. This is so much better.
