### ISSUE TITLE
Add HUD icon for carrying enemy flag

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#210]
@kaadmy your changes for the quad timer are great. I'd love to see something very similar for when you're holding the enemy's flag.

**Comment by kaadmy** [comment]
Should I add it in the same place as the powerups on the left, or any other position?

**Comment by jdolan** [comment]
On the left.. probably above the quad?

**Comment by kaadmy** [comment]
Okay!
BTW, are current flag statuses drawn right now, ie. if the team flag is dropped, returned or carried?

**Comment by jdolan** [comment]
No, not yet. When you take the flag, it's drawn as any ordinary item pickup for 3 seconds in the top-right corner. That's it.

**Comment by jdolan** [comment]
We could maybe come up with a scheme where the flag icons are used to indicate flag status?

 1. Flag icons are drawn for each team, on the right of the HUD, always.
 1. Normal flag icons indicate the flag is at its base.
 1. Desaturated flag icons indicate the flag is taken.
 1. Pulsing normal flag icon indicates you are carrying the flag.

What do you think of this?

**Comment by kaadmy** [comment]
I was thinking a single flag icon per team on the right that pulses when carried/faded when dropped.
When holding the flag, there could be an additional icon in the center of the bottom edge of the screen just above the ammo counter.

**Comment by kaadmy** [comment]
BTW how do ConfigStrings work again?
I could make your own flag status not shown and instead draw both team flags with the carrier's name besides them.

**Comment by jdolan** [comment]
Heh, just realized I said "right" when I meant "left." Doh!

I'm not sure I like the idea of revealing the carrier's identity. Most of the CTF / team games I've played do not do this, and I think it's on purpose. If you know how someone plays, and you know they have the flag, you're more likely to anticipate where to head them off. It makes it that much harder to capture a flag / objective. I think I'd rather keep the `STATE_CARRYING_FLAG`, and introduce ConfigStrings (or a single, delimited config string?) for `CS_CTF_FLAG_STATE` or `CS_CTF_FLAG_GOOD` and `CS_CTF_FLAG_EVIL` or something.
