### ISSUE TITLE
Hand grenades missing all view model animations

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#213]
Hand grenades are missing all view model animations, which makes it really hard to judge what is happening, as well as just generally being broken :)

**Comment by jdolan** [comment]
We don't have any view model animations. We apply a hard-coded kick effect to the static weapon meshes in 1st person view. I don't think we will fix / improve this for 1.0.

**Comment by Paril** [comment]
Good ol Quake 3 method :) Do you think there could be a way to maybe have a timer on the HUD? Maybe the ammo icon can have some kind of charge-up?

**Comment by jdolan** [comment]
That's not a bad idea. There's actually another ticket (#175) asking for a recharge / ready state for view models. We could implement this by desaturating the HUD icon on fire, and re-saturating it when the weapon is available.
