### ISSUE TITLE
New screenshot code is tinting images

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#219]
![quetoo004](https://cloud.githubusercontent.com/assets/567688/18868773/45a8461a-845e-11e6-84a3-f84613dc0730.png)

From fractures, the scene looked correct ingame.

**Comment by jdolan** [comment]
Uh, that looks awesome. What are you bitching about?

**Comment by jdolan** [comment]
CC @tapir Must be the byte ordering between glReadPixels and IMG_Write_rw?

**Comment by WickedShell** [comment]
I know it's kinda awesome but it's not intended :) made my edge ones look
crazy :)

**Comment by tapir** [comment]
Whoops, It should be GL_BGR in glReadPixels. I guess that's what SDL expects. I'll fix it.

**Comment by jdolan** [comment]
Yep, just tested locally and that fixes. Go ahead and commit :)
