### ISSUE TITLE
Fragment armor pickup icons aren't shown

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#223]

**Comment by jdolan** [comment]
![quetoo003](https://cloud.githubusercontent.com/assets/643118/18899449/09d324bc-8507-11e6-87a4-e0e0c084c6a8.png)

**Comment by Panjoo** [comment]
I see you closed this but I've seen this behaviour too (for instance in this demo on the map Torn I don't see the icon of the small_healths when I pick them up.) 
I thought it had to do with picking up multiple items of the same kind but then it also happened with other items. Especially when they're close together with little time in between pickups it tends to ignore the icon of the last pickup. Not really a problem for now I think, but still...
[smallhealth.zip](https://github.com/jdolan/quetoo/files/504622/smallhealth.zip)
