### ISSUE TITLE
Armor max appears unlimited

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#224]
I got to 1007 armor before getting bored... (Via fragment pickups) We should at a minimum limit to say 200 armor. Should armor decay down the way health does? I'm inclined to say no to making armor decline, but I can see the arguments either way)

**Comment by jdolan** [comment]
Let's set a hard max of 200 for now. I don't recall if Q2 decayed armor.

**Comment by Panjoo** [comment]
Nope, Q2 doesn't decay armor, only thing that decays/leaks is the health from the mega, 5 seconds after you pick it up.
On a related note I've noticed that even the small_healths in Quetoo decay almost instantly, so your little extra health is gone in seconds after you collect a bunch. This pretty much makes the whole item useless as a form of protection against a railgun hit. The small_healths should not decay at all.

**Comment by WickedShell** [comment]
Everything decays back to 100. That's by design. You shouldn't be able to
be perpetually at a high health. I could see increasing the initial time
before decay kicks in though. Right now it's only 1 second, but a 5 second
delay would make a lot of sense. RG is probably going to get a slight
debuff as well (one hit kills from 100 health are pretty frustrating)

**Comment by jdolan** [comment]
No, Pan is right re: the small healths not decaying. This is a crucial element of Q2 gameplay. It's part of why the 100 dmg rail worked in Q2.

We have code for this right in my quake2 and q2pro repos.

**Comment by WickedShell** [comment]
:/ Really don't like that to be honest. It seems really inconsistent, and
worse then the armor pickups having varying conditions depending on what
armor you have.

How do I know what my health with mega will decay back down to while I have
mega?
Does damage come off the mega side first, or does it come off both stacks
evenly?

I don't think just because Q2 did it we have to do it that way.

**Comment by jdolan** [comment]
Let's try to keep these issues on-task, and save the discussion of related features for IRC. The max for armor should be `200`, and it's not necessary to add a decay to it.

**Comment by Paril** [comment]
Mega always decayed back to 100, but only after you got the mega. Stimpacks pre-mega didn't decay, but post-mega did.

**Comment by kaadmy** [comment]
I think this can be closed now since there's a decent armor cap mechanic in place?

**Comment by jdolan** [comment]
Yes, I see your commit from earlier. Nice!
