### ISSUE TITLE
Reintroduce in-game editor functionality

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#225]
...which is unfortunate as I really need that to finetune and edit materials for the maps Fractures and Lilith.

Would it be possible to make cl_editor pop up upon typing "cl_editor 1" + Enter, instead of having to press a key?

**Comment by jdolan** [comment]
Hi Pan, I know.. the editor was a casualty of the new menus. The old editor was based on AntTweakBar, which has been completely removed in favor of ObjectivelyMVC.

Eventually, I'll be replacing the entire HUD, console, etc.. with ObjectivelyMVC components, and we'll be able to have a rich in-game editor to place and tune light sources, entities, etc.. and of course, materials. But this won't happen for the 1.0 release. Your best bet for tuning materials right now is to run Quetoo in windowed mode, and edit the materials definition in a text editor -> `r_restart`. Not ideal, I know. Again, sorry about that.

**Comment by kaadmy** [comment]
Since materials can be changed run time via the old cl_editor, would it be possible to have a command like `fs_reload_materials`?

**Comment by jdolan** [comment]
Yes, it's called `r_restart` ;)

**Comment by kaadmy** [comment]
I know `r_restart` exists, but it has to reload all the models and the map too, which takes a while for me(10 seconds on a small map)

**Comment by jdolan** [comment]
The "best" way to adjust materials as of right now, is to look at the material in question, and tweak the following cvars until the material looks good:

    r_bumpmap
    r_hardness
    r_parallax
    r_specular

Jot the values down in the .mat file, reset the cvars to 1.0, rinse and repeat. I agree that this is not ideal. There is nothing I can do about it right now.

**Comment by kaadmy** [comment]
_KaadmY proceeds to add keybinds to change those CVars_

**Comment by Panjoo** [comment]
Luckily I still have a recent backup of Quetoo that still uses AntTweakBar. I'll just load that up if I want to edit materials using cl_editor.  Hah!! :P

**Comment by jdolan** [comment]
Last week, I merged a big old refactor of the UI code that moved most of the UI into cgame, but allows the engine itself to override the UI as it wishes. Therefore, I think I could actually re-introduce the same basic editor functionality that we had with a relatively small amount of work. Moving this to 1.0 release, and will address it next week.

**Comment by kaadmy** [comment]
Should the editor be implemented in cgame? It looks like it shouldn't be too hard to implement this for me..

*/me cringes*

**Comment by jdolan** [comment]
No, it should be implemented in the game engine itself (src/client/ui/{views,viewcontrollers}. Currently, there is insufficient logic to manage both the engine and cgame view hierarchies, and so this will need to be added to ui_main.c. I don't think it's a big deal, but basically, a generic mechanism that "hides" the cgame's view hierarchy is required. When `cl_editor` is set, ui_main should skip / hide the cgame's view.

**Comment by jdolan** [comment]
I could totally see the editor being a use case for JSON view binding, btw.

**Comment by kaadmy** [comment]
Does the editor ONLY change `r_bumpmap`, `r_specular`, etc. or is it too custom to implement in JSON?

**Comment by jdolan** [comment]
It doesn't change those cvars at all. It changes the material parameters for the material that is resolved by tracing through the crosshair. Here's the source to the old editor implementation:

https://github.com/jdolan/quetoo/blob/7c852d6b7a52fb0a62df01ef0823103dc9a04664/src/client/ui/ui_editor.c

**Comment by jdolan** [comment]
And here's a video of it in action:
https://www.youtube.com/watch?v=oZ_sH0zcR_Y

**Comment by kaadmy** [comment]
I've been messing with the UI/ObjectivelyMVC recently, I think I can try this again.

**Comment by jdolan** [comment]
Okay! Let me know if you get stuck. In fact, if you could branch and push as early and frequently as possible, I can try to give feedback quickly to keep you on the right path.

**Comment by kaadmy** [comment]
Okay, this is now usable in master!
20fff0e3135705add01cd6336dc56f4a550bb7f2

**Comment by jdolan** [comment]
Woo! Thanks @kaadmy :)

@Panjoo This works just like before (`cl_editor 1/0`), except now the _Save_ button overwrites your existing materials file, with formatting, and will _not_ munge or lose any stages you have defined previously. So this is actually a pretty significant improvement over the previous functionality.

**Comment by kaadmy** [comment]
With my editor, I noticed some strange things happening with invalid materials.
When you flick the mouse quickly from sky to a valid material (Wall or something), sometimes the wall surface becomes invalid. I don't have any idea how this even happens.
