### ISSUE TITLE
Use Java AWS client to update game from S3, remove rsync requirement

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#234]
https://github.com/perlundq/yajsync

**Comment by jdolan** [comment]
I know, but what else is there?

**Comment by Paril** [comment]
It is our best option, yeah.

**Comment by jdolan** [comment]
I've started work on an Amazon S3 based Java updater:
https://github.com/jdolan/quetoo-updater

More to follow.

**Comment by jdolan** [comment]
@Panjoo @anthonywebb1 @Thornation 

At long last, we're retiring our decade-old, brittle `rsync.exe / cygwin.dll` based updater. There's a new sherif in town, and he goes by the name `quetoo-installer-small.jar`. It's a 700KB universal installer / update utility with a cheeky little graphical user interface. It's included in all of the *new* snapshots, which are listed on the Downloads page of the website. Here is what you should know:

1. You can keep your current working copy, and install a new snapshot over it in order to move to the new updater. Just delete your `\bin` and `\lib` folders, extract the new snapshot, and run `\bin\quetoo-update.exe` like you always have.

1. If you're paranoid about breaking your working copy (understandable), simply download a new snapshot from the website and extract it to a new location. Then run `bin\quetoo-update.exe`.

1. We're actually going to do away with snapshots altogether very soon! The `quetoo-installer-small.jar` is actually fully capable of running on its own, and installing the entire game. This means we'll have a single, 700KB download for all platforms. Pretty awesome! But we're not quite there yet.. maybe another week or two. I'll open another ticket for that.

1. We've moved to Amazon S3 for all snapshot and game data distribution. All file transfers now take place over good old HTTP, and we're no longer constrained by my little 1GB VPS. This will help immensely if the game gets any traction after release.

1. The update process no longer prunes your install directory of foreign files! This has long been a point of frustration for users, so I've disabled this behavior by default. It's still in there, but turned off by default. **When we re-pack quetoo-001.pk3 before release**, you guys will want to prune or reinstall, etc.

1. Make sure you download the right snapshot for your platform. For @anthonywebb1 and @Thornation, that's the mainline Windows build at the top of the [Downloads](http://quetoo.org/pages/downloads) page. For @Panjoo, that's the older WinXP build (MinGW).

Here's a screenshot of the Updater. It's nothing sexy yet, but it's better than a terminal window!

![screen shot 2017-01-27 at 9 26 50 am](https://cloud.githubusercontent.com/assets/643118/22374226/6234df30-e473-11e6-8eb1-e600ace5ca3c.png)
