### ISSUE TITLE
Bug fix / potential optimization for r_shadows 2

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#237]
The planar shadows make extensive use of the stencil buffer. Each surface is rendered with a stencil value derived from its plane number. When shadows impact a plane, we draw that shadow with the stencil test for that plane number. The stencil buffer is only 8 bits, which leaves a maximum number of unique stencil values of 255. In fact, I think the way this worked out, I was only able to use 127 unique values:

```
    glStencilFunc(GL_ALWAYS, (surf->plane->num % 0xff) + 1, ~0);
```

This results in shadows sometimes hitting a false positive for surfaces (planes) across the map. If you've ever seen a stray, nonsensical shadow, this is why. Exiting the water on Edge is an easy way to see this.

So.. what if we flipped a reserved bit on `surf->flags` whenever a shadow impacts that plane, and then check that reserved bit before applying glStencilFunc? For surfaces that are not impacted by a shadow, we would write `0` to the stencil buffer (or we could even disable the stencil buffer, if that yields a performance boost). We would have to add a simple loop in R_MarkBspSurfaces to reset this flag every frame.

This should fix the stray shadows, and maybe even provide a small framerate boost.

**Comment by jdolan** [comment]
The tricky part here is, in the shadow code, when a trace yields a shadow, you must mark the _renderer's_ copy of the impacted plane, so that the renderer can easily check the plane when drawing surfaces.

We currently do not have a `r_bsp_plane_t` type, but I would add one, that is essentially a `cm_bsp_plane_t` with a bit mask field for renderer state / flags such as this.

**Comment by jdolan** [comment]
@Paril handing this one back to you. Now that the fix itself is in there, if you wanted to try optimizing stencil state management, be my guest. And if not, we can close this out.

**Comment by Paril** [comment]
Old profile: http://i.imgur.com/UHpi2WB.png
New profile: http://i.imgur.com/4G4DCD5.png

R_Stencil ops are barely noticable now. I also get about 15-20 FPS improvement on wake. Nice!
