### ISSUE TITLE
OpenGL ES 2.0 (?)

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#238]
Just opening this so we can discuss where we go from here, and if this is a good target for us for the long run. May need a plan of attack and whatnot. Might not be possible to get this done before first milestone though.

**Comment by jdolan** [comment]
I think this is worth exploring. I would prefer if we started with an audit of `r_state.c`, `r_array.c` and `r_program.c` to see how this might go. I think that will help inform a general approach, and also give some insight to level of effort, so we can decide if this is a "1.0 milestone" thing, or not.

**Comment by jdolan** [comment]
I would not be able to focus on this in the immediate future, btw. You'd have to take the lead on this branch, tho I could certainly help out with answering questions and reviewing patches. I'd like to try to stay as focused on the 1.0 milestone as possible.

**Comment by Paril** [comment]
Focusing on the easy stuff first, here's what needs to be done:

- Make sure we're using the appropriate GLSL version in the files
- Manage modelview, projection and texture matrices ourselves.
  - texture matrix is only used by material subsystem. Is it possible or feasible to make materials entirely shader-based? There's a Quake 3 shader to GLSL shader conversion system on the net somewhere, maybe we can leverage the same capability.
  - modelview and projection can be handled as simple as uniforms. I think potentially pre-multiplying these two together for the shader might be beneficial for larger batches (esp particles) but this is hard to know offhand (and may require lots of CPU multiplication if the modelview changes quite a bit).
  - glOrtho & glFrustum needs to become a local function
  - glPushMatrix/glPopMatrix, need our own stack to hold these
  - all glTranslate/glRotate/glScale moved over to Matrix4_ functions
- glPushAttrib/glPopAttrib are not supported. I think we'd benefit from some sort of state bit management here where all of our GL state is contained in a structure and can be saved/restored at any point. This seems to be limited to MVC drawing though, so might not be important to us to touch atm.
- glAlphaFunc needs to become a fragment shader routine, and enabled/disabled via either uniform or different shader files (discard statement)
- Hard to tell just by looking at it, but glClientActiveTexture might need to be a second sampler or something; I read up on this function but honestly I don't see how it does anything different than what activeTexture does already.
- The least fun bit: removing all fixed pipeline drawing.
  - glBegin/glEnds should be handled first.
  - Client arrays are slightly more complicated, with GL 3.0 we have to be sure all of the shader attributes are ready to go and hooked up properly. VAOs should make this pretty simple to manage. The biggest challenge is balancing GPU resources, making sure we have a system for creating/managing/freeing VBOs & IBOs, and hooking them up as efficiently as possible.

**Comment by jdolan** [comment]
I think we can close this one out, @Paril. There are certainly more renderer refactor / cleanup / enhancement items, but the bulk of the work is complete and merged. Really, great work. Pretty massive accomplishment, and you did it all without stomping all over the code. Impressive. Please close if you agree that this one is wrapped.
