### ISSUE TITLE
Adrenaline & quad times should be drawn on hud

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo#24]
As the title says, get the info avalible

**Comment by kaadmy** [comment]
Does adrenaline have a timer like quad damage? I haven't noticed anything that handles a timer for it in the code.

**Comment by jdolan** [comment]
I think the adren just runs the standard Item routines for pickup / reset.

**Comment by kaadmy** [comment]
Got Quad timer working, I don't think i can draw an Adrenaline timer since it's instant.

**Comment by kaadmy** [comment]
I also bumped the protocol since I changed the g_stat_t enum along with some stuff in game.

**Comment by kaadmy** [comment]
This should be now fixed in bdbdd64
