### ISSUE TITLE
fractures hits MAX_ENT_LEAFS for a rotating bmodel

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#242]
I'm not sure which bmodel does this, but it hits MAX_ENT_LEAFS. Increasing it to 256 fixes it, but won't do that since I think it might be an issue with the map or something.

Making here instead of quetoo-data since this might not be an issue with the map but moreso how linking works.

**Comment by Panjoo** [comment]
I'll be updating the new pk3 for fractures very soon and I've fixed quite some mangled brushes (cracks) including the func_rotaters. Would be a good time to re-check to see if it was map related.

**Comment by jdolan** [comment]
That's great news! I don't suppose you've taken a pass at hinting the map, or otherwise fixing its VIS inefficiencies. Gehenna has similar problems -- 40 minute VIS compile :|

**Comment by Panjoo** [comment]
[`commit 6ced5f1`]
(https://github.com/jdolan/quetoo-data/commit/6ced5f1121ac3c6f7df4845b76a1fad32560518e)

^ This is the newer Fractures map, maybe my cleaner brushwork might have also fixed that MAX_ENT_LEAFS thing? Worth a check.

**Comment by jdolan** [comment]
Yup! I just set a breakpoint in the area where this would have been triggered, and it is no longer happening. Nice job, @Panjoo.
