### ISSUE TITLE
Particle color changes (GL state leak / batching error)

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#247]
As a rocket explodes, it's smoke trail will suddenly turn the same dark charcoal color as the explosion smoke particle.

![quetoo008](https://cloud.githubusercontent.com/assets/643118/19992971/871f4f12-a218-11e6-8e7d-c7c592db3237.png)

**Comment by Paril** [comment]
Fixed in 437659e03018c0dccaf554de827fb2eaab168044
