### ISSUE TITLE
60hz bugs

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#251]
- [x] Jitter on ducking
 - [x] Jitter on stairs
 - [x] Weapon firing rates?

**Comment by jdolan** [comment]
@Paril Did you want to tune all of the weapon timings to your liking now that the server tick is locked?

**Comment by Paril** [comment]
Will do.

**Comment by jdolan** [comment]
Closing this one out for now. Other specific 60hz bugs can be reported separately.
