### ISSUE TITLE
Ensmallen buffer sizes and GLSL types

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#256]
Several of our GLSL types can be optimized on the client side. Thinking of this:

vertex & next_vertex: float[3], no change
normal & tangent: GL_INT_2_10_10_10_REV for both. Reduces vertices from (12 + 16) bytes to (4 + 4) bytes, and the encoding should not be noticable, but I will test this thoroughly before making that big of an assumption. Tangent 4th component is only ever -1 or 1, so 2 bits for that integer is perfect.
color: byte[4]
texcoord & lightmap_texcoord: short[2] each. This should be enough precision for us, but as always will verify before making any rash decisions.

This would reduce a single vertex from (12 + 12 + 12 + 16 + 16 + 8 + 8) (84) to (12 + 12 + 4 + 4 + 4 + 4 + 4) (44), assuming every component is being pulled from the client that is. In most cases, verts only contain a few of the elements.

**Comment by jdolan** [comment]
Crash on first frame in OS X
<img width="1680" alt="screen shot 2016-11-11 at 10 11 19 pm" src="https://cloud.githubusercontent.com/assets/643118/20235284/dafb5ace-a85b-11e6-8a99-4b3f6e676c02.png">

**Comment by jdolan** [comment]
All set. Feel free to close this and #257 if they're done :)
