### ISSUE TITLE
Greater fog distance?

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#259]
@jdolan - I'm not exactly sure how quetoo is doing fog but can you increase the standard fog distance so that it becomes less opaque?

Increase it by, let's say 768 units or so? At the moment the only way to have some sort of control over the fog is by lowering the `r g b` values so it becomes darker in color, but that also makes the whole map darker and blurs out the textures. 

---

I know that Q3 uses fog brushes and has a <distance toopaque> parm. (From Q3's shader manual: This is the distance, in game units, until the fog becomes totally opaque, as measured from the point of view of the observer. By making the height of the fog brush shorter than the distance to opaque, the apparent density of the fog can be reduced (because it never reaches the depth at which full opacity occurs).

**Comment by jdolan** [comment]
@Paril Wanna take a crack at tuning the fog shader?

@Panjoo Paril and I have chatted about fog volumes, and have some ideas.. We'll take this into consideration when we get there :)

**Comment by Paril** [comment]
Can always just add alpha to the color, or tunable start/end parameters.

**Comment by jdolan** [comment]
I think adding RGBA support to the code without breaking any existing maps that specify fog as 3 component RGB would be great. That will get us by until we can tackle fog volumes.

**Comment by Panjoo** [comment]
^What he said.
Does this mean that once this works you'd get 4 values, eg. 0.7 0.7 0.8 0.6(=60% opacity)?

**Comment by Paril** [comment]
Ye basically.

**Comment by Paril** [comment]
Added in eb3901e

**Comment by jdolan** [comment]
Sick! @Panjoo you should be able to provide a 4th component to the fog color of the weather worldspawn value now. I've updated entities.def and the website documentation as well.

**Comment by Panjoo** [comment]
Thanks dudes, I will definitely be using this 👍
