### ISSUE TITLE
Ambient sounds ignore volume (?)

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#261]
Go to wake, turn volume and music off. Hear computers. Why computers, why.

**Comment by WickedShell** [comment]
Can't reproduce here... Cvar file?

**Comment by Paril** [comment]
I'll play with it some more. I walked around to the big area that is worst on FPS to do some profiling, set s_music_volume to 0 and s_volume to 0, but ambient sounds (spceifically the Quake 1 beepy computer sound) was still going. s_ambient didn't seem to fix it, but I imagine s_restart would have.

**Comment by WickedShell** [comment]
Did you s_restart? It's really annoying that is (was?) required?

**Comment by jdolan** [comment]
Good catch, this is fixed.
