### ISSUE TITLE
Can uncrouch from any position, even if blocked from above

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#265]
Crouch underneath something short that you couldn't stand in, then let go of crouch. Easy bug to fix, but in case I don't get around to it, noting it here.

**Comment by kaadmy** [comment]
Can confirm this, it happened fairly recently, in the past couple months.

**Comment by jdolan** [comment]
And you end up stuck in a solid?

**Comment by Paril** [comment]
Logically if you uncrouch with your head stuck in a wall you'd be stuck, yes :)

**Comment by kaadmy** [comment]
I think in the commit that added breath puffs moved around the function to check crouching, but I think that was only used for the weapon flashes anyway.

**Comment by Paril** [comment]
Well, dead bodies still breathe for a while after you die, gasses escaping and such. Intentional.

**Comment by Paril** [comment]
Both issues fixed by a6ffd49
