### ISSUE TITLE
2 level shots are loaded

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#269]
On map loading we flash a level shot of the selected level for one frame, then swap to a different one that we leave up. It doesn't make sense to show one for as short an amount of time as we do. (Only noticed because of the 1000x penalty of valgrind).

**Comment by Paril** [comment]
It's weird that this is even possible because the levelshot is unloaded immediately when the level is done loading, haha. I notice this too in my game, though.

**Comment by Paril** [comment]
This should be fixed with some recent changes. I don't see how this is possible though since the first call to UpdateScreen will happen directly after the levelshot is loaded.. if it's still happening I'll come back to it.
