### ISSUE TITLE
Remove all the "modular plugin" stuff for rendering?

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#282]
@jdolan permission to remove modular plugin renderer stuff (specifically all of the function ptrs for DrawMeshModel, etc and remove "_default" so there's no weird distinction)? Since everything must pass through a shader now, you can easily do everything you could do in the old "pro" renderer inside shaders, so I don't think this is really required any more.

**Comment by jdolan** [comment]
Agreed. While I don't think a pure shader approach would work (still require different state management), I'm fine with removing the indirection of the function pointers. It's not something we're attempting to use for 1.0.

**Comment by Paril** [comment]
Decided to not bother with this, didn't seem to gain much by removing it and I'm sure we can find a use for it down the road without needing to re-add it.
