### ISSUE TITLE
Add third person chase cam mode

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#284]
A special command / key binding when the chase camera is active that toggles `cg_third_person` would be dope. This can all be implemented right in cgame, cg_view.c.

**Comment by kaadmy** [comment]
Can't this be done with `bind P "toggle cg_third_person"`?

**Comment by jdolan** [comment]
Not quite. As of right now `cg_third_person` is `CVAR_LO_ONLY` (offline mode) because it's a cheat in multiplayer (you can see around corners with it). So some logic needs to be introduced to ensure that it's only allowed when chasing. Also, the third person chase camera should not retain third person if you cycle to regular spectator mode, etc..

So I almost think that what we're really after here is another code path *into* the third person view, that is only available / active when chasing someone, and is easily accessible through an action that a spectator might think to take (clicking mouse 1 or mouse 2, or something like that).

**Comment by jdolan** [comment]
We could simply have a cvar for the chase camera style, and expose that in the UI as a drop-down or checkbox, e.g.:

`Case camera style:   { select }`

or 

`Third person chase camera: [X]`

**Comment by jdolan** [comment]
`cg_chase_camera_style`

**Comment by jdolan** [comment]
This is implemented now. Spectate a game, and chase a player by clicking your mouse (`+attack`). Toggle 3rd person perspective by hitting the space bar (`+move_up`).
