### ISSUE TITLE
Sound media system appears to suffer from dupes/corruption

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#288]
http://i.imgur.com/e0YP9Zj.jpg

Hard to explain currently how/why this is happening. Multiple map loads cause sounds to get pushed multiple times.

**Comment by Paril** [comment]
I believe this is the root cause for my attempt at sexed sound registration to crash, as well as null entries in the sound list.

**Comment by Paril** [comment]
Update: appears to be related to aliasing. I think an aliased sound is pointing to a freed chunk, and somehow that's causing problems.

**Comment by jdolan** [comment]
Any steps to repro?

**Comment by Paril** [comment]
This was fixed in my recent commits
