### ISSUE TITLE
Refactor BUTTON_HOOK out of engine

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#289]
I noticed that there's now `BUTTON_HOOK` in quetoo.h, cl_input.c, etc.. I'd like to avoid having mod-specific functionality in the engine, if possible. The approach I've used for things like this is to define e.g. `BUTTON_GAME` as the first button after `BUTTON_ATTACK`, and also define `BUTTON_MAX` as the maximum number of buttons the protocol supports. Then the game can freely define `BUTTON_HOOK` as `BUTTON_GAME` or whatever. The client could be adjusted to support `MAX_BUTTONS` and manage key state for them generically. This way, the engine knows nothing about the grapple hook, which feels right to me.

Thoughts?

**Comment by Paril** [comment]
Done.
