### ISSUE TITLE
CTF flag issues

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#294]
Several issues I've noticed with the flag in CTF while playing around:

- [x] The flag cannot be picked up unless it's on the ground (or similar), so dropping the flag in water makes it untouchable for several seconds since it has to slowly float down.
- [ ] After the flag returns (automatically!), you can no longer pick it up since the BBOX doesn't exist anymore, no idea how this one happens...

**Comment by Paril** [comment]
Fix first issue in #2944000

**Comment by Paril** [comment]
Fix two in fe06cd7
