### ISSUE TITLE
quetoo-update on Windows still breaks permissions.

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#301]
quetoo-update (well, the rsync) causes all written files to have read-only permissions, which is a nightmare when trying to update more than once or edit files after writing out. Have to figure out why.

**Comment by jdolan** [comment]
Is this a 1.0 release issue? Sounds bad.

**Comment by Paril** [comment]
Yeah it's super frustrating, you can't run quetooupdate more than once without manually setting permissions

**Comment by jdolan** [comment]
Keeping this ticket open, but there's work actively being done to move away from the rsync-based updater entirely. See #234

**Comment by jdolan** [comment]
This will be closed by #352
