### ISSUE TITLE
Game crashes on firing BFG

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#302]
After updating (to Dec 21 i686 mingw32 version, using quetoo-update.exe), firing the BFG immediately closes the game without message, regardless of the map. Either someone really hates the BFG or something is not right.

**Comment by jdolan** [comment]
Yep, this was a minor regression that was fixed here yesterday: 5a0b1df268214414182a2edc9960c0a62358930c

Should be able to update now for a fix. Also, you're gonna love what comes next :)

**Comment by jdolan** [comment]
Btw you should really be using Paril's MSVC build. You'll probably see improved performance and stability.

**Comment by Panjoo** [comment]
I know, and don't think I don't want to but I'm seriously not going to reinstall and update my OS right now and all my tweaked (cr4x0red) tools and shit to get SP1 in order to get that msvc build running for quetoo. I should though, and I might but can't be arsed now and so I can only contribute to something that's compatible with my current system.

**Comment by jdolan** [comment]
Ah, gotcha. I should have bought you a Win10 license for Christmas ;)

Good to know you're using the MinGW builds, and they work! For the general release, we'll be going with @Paril's builds. But I'll make sure that MinGW is maintained / supported.

**Comment by Paril** [comment]
Since the msvc build is clang it should be trivial to make sure it works with ming too, we can have that one listed as the windows xp to 7 build, and then 7 sp1 and above for the msvc one

**Comment by jdolan** [comment]
That's a possibility, yea. I haven't been able to test the MinGW build on anything less than Win10. Maybe it's more stable on XP/7.

**Comment by Paril** [comment]
I can try it in a vm and get back to you on that
