### ISSUE TITLE
Weapon jerking when moving left/right

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#307]
Appears to have been introduced in 312432ee64fe4c257c993708b82c3788276ea032 - moving left/right causes the weapon to jerk around. Moving or looking up/down works fine, it's only looking left/right that causes it.

**Comment by jdolan** [comment]
I'm not sure what to do here. I can't reproduce this. Any steps you can provide?

The suspect bit in that commit was adding Cl_UpdateView in the lazy-lerp block. This introduced the "phantom" view weapon flashing for 1 frame (among other anomalies), but has since been removed.

**Comment by Paril** [comment]
Don't know, it just happens to me - any FPS, any vsync, etc. When turning to the right, the gun seems to try to push forward, and when turning to the left it tries to pull backwards, but it's like snapped back at every step.
