### ISSUE TITLE
MG/HB/LG kick is too quick

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#310]
It only takes a couple of frames for it to reach max kick. there's gotta be some kind of ramping like there was before where it would push against the kick but keep going up.

**Comment by jdolan** [comment]
I intentionally have it raise to a set maximum and stay there. This avoids the view bouncing while you're shooting, which was difficult to balance mathematically and make look good. So I figured just incrementally raising to a pre-defined limit and staying there until you release the trigger was a good move. It worked for DOOM.

**Comment by jdolan** [comment]
That said, feel free to tweak the kick effects to your liking. I'm open to changes.

**Comment by Paril** [comment]
The problem is just that it goes up to the max height in 2 frames, not that it raises and doesn't bounce.

**Comment by Paril** [comment]
Adjusted in dab725e, see how it looks for you @jdolan

**Comment by jdolan** [comment]
This is fine with me if you like it. I was going for the classic DOOM-style kick, where you fire the plasma and it rather quickly ramps up but then stays put. But If this feels more natural / correct, I'm fine with it. @Panjoo should probably weigh in on the weapon kicks as well.

**Comment by Paril** [comment]
Doom 3 or regular doom? I never played Doom 3. I found the kick to be too easy since you just had to look down slightly and you were good to go, now it's more like it used to be before the move.

**Comment by jdolan** [comment]
Regular DOOM. I guess, you mentioned that competitive players would want to disable view kick.. so in having a kick that doesn't shake / rock your view, I thought this was a good compromise.

**Comment by Paril** [comment]
It was hard for me to play with because the view just instantly shifted up, not requiring any forward pressure at all. The plasma gun in Doom/D2 didn't have kick at all, the game didn't even have view pitching, lol.

**Comment by jdolan** [comment]
Haha, oh yea. I could see it "kicked" in my mind.. But the kick is just an after-effect and does not impact your aim:
https://www.youtube.com/watch?v=JlW83GNECQc
