### ISSUE TITLE
Small stainmaps are frequently missed on lower resolution lightmaps

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#311]
http://i.imgur.com/dIVc1DX.jpg

**Comment by Panjoo** [comment]
I'm not sure whether it's related to this but I remember when trying material stages like stretch to create continuous expanding and contracting effects on water surfaces, the effect wouldn't (like you say) traverse plane boundery lines or bsp cuts. It would just stretch seperately on all brushfaces, ruining the effect.

**Comment by Paril** [comment]
I think this issue is purely related to the stain code, because they traversed cut lines in older commits. This is a side effect of some screwery jdolan did to make the stain sizes stay consistent :)

**Comment by jdolan** [comment]
After two separate bug fixes, stains now traverse planes correctly. However, small stains (< radius 4.0) do not always impact low-resolution lightmaps. Not sure that's something we can improve on right now.

**Comment by jdolan** [comment]
Fixed!
