### ISSUE TITLE
Too many BSP representations

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#313]
So this kind of goes back to #63 - our regular usage of Quetoo and Quemap have three separate BSP implementations.

Quemap works solely in d_bsp_*, which is the "bspfile" stuff that is basically a raw representation of the BSP as it exists on the disk.

Quetoo Server works in cm_bsp_*, which is basically a copy of d_bsp_* except the structures have additions to it, certain bits are expanded/transformed, but for the most part it's exactly the same as d_bsp_*.

Quetoo Client works in r_bsp_*, which is basically a copy of cm_bsp_* except some useless lumps are dropped, some new lumps are loaded, and the structures are set up just to hold data that only pertains to rendering.

As I was doing the material subsystem, I realized that I really like the concept I had with cm_material_t which r_material holds a reference to and just contains the additions to it. I'm thinking maybe we can do this with BSP as well so that we have one global "BSP load" function living in common (honestly I think the cm_bsp_* system can be used in both server and quemap with no issues at all) and then have the renderer just tack on the stuff it needs.

The only real downside I can think of is the question of how to manage lumps that only certain systems need - for instance, cm_* doesn't need lightmap data, but Quemap and renderer do - rather, quemap needs all lumps since it could write to them.

I have some ideas for all of this, but would be nice to have some input first before I decide to do anything about this. It's more of a rainy day thing since it doesn't really affect what we have.

**Comment by jdolan** [comment]
In looking over this, I am slightly tempted to move `src/collision/cm_bsp.{c,h}` to `src/bsp.{c,h}` to build `libbsp.la`, and have collision and friends all link against it. But that's for a rainy day.

**Comment by Paril** [comment]
That is something I thought about, same for materials (libmaterial)
