### ISSUE TITLE
"Bus error" VIS compiling Gehenna

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#314]
```
The-Frag-Pipe:default jdolan$ quemap -bsp -vis -light -extra maps/gehenna.map
Quetoo Map 0.1.0 Dec 29 2016 x86_64-darwin16.3.0
Adding path /usr/local/lib/quetoo/default..
Adding path /usr/local/share/quetoo/default..
Adding path /usr/local/share/quetoo/default/map-aerowalk.pk3..
Adding path /usr/local/share/quetoo/default/map-darkzone.pk3..
Adding path /usr/local/share/quetoo/default/map-edge.pk3..
Adding path /usr/local/share/quetoo/default/map-fractures.pk3..
Adding path /usr/local/share/quetoo/default/map-fragpipe.pk3..
Adding path /usr/local/share/quetoo/default/map-gehenna.pk3..
Adding path /usr/local/share/quetoo/default/map-gym.pk3..
Adding path /usr/local/share/quetoo/default/map-hallways.pk3..
Adding path /usr/local/share/quetoo/default/map-lavatomb.pk3..
Adding path /usr/local/share/quetoo/default/map-lilith.pk3..
Adding path /usr/local/share/quetoo/default/map-pits.pk3..
Adding path /usr/local/share/quetoo/default/map-slimyplace.pk3..
Adding path /usr/local/share/quetoo/default/map-tokays.pk3..
Adding path /usr/local/share/quetoo/default/map-torn.pk3..
Adding path /usr/local/share/quetoo/default/map-trial.pk3..
Adding path /usr/local/share/quetoo/default/map-wake.pk3..
Adding path /usr/local/share/quetoo/default/map-warehouse.pk3..
Adding path /usr/local/share/quetoo/default/player-gork.pk3..
Adding path /usr/local/share/quetoo/default/player-qforcer.pk3..
Adding path /Users/jdolan/.quetoo/default..
Adding path /Users/jdolan/.quetoo/default/map-q1dm2.pak..
Adding path /Users/jdolan/.quetoo/default/sky-tramonto-tga.pk3..
Using /Users/jdolan/.quetoo/default for writing.
Quetoo Map 0.1.0 Dec 29 2016 x86_64-darwin16.3.0 initialized
Using 8 threads

----- BSP -----

0...1...2...3...4...5...6...7...8...9... (2 seconds)
0...1...2...3...4...5...6...7...8...9... (3 seconds)

BSP Time: 9 Seconds

----- VIS -----

0...1...2...3...4...5...6...7...8...9... (2 seconds)
0...1...2...Bus error: 10
```

This is a threading issue. As a workaround, `-t -1` on the command line disables threading, and the VIS is able to complete (slowly).

**Comment by Panjoo** [comment]
I had already made a start with re-VIS'ing this map and optimizing the brushwork, a while ago. But hintbrush-wise, there isn't much I can do because of its openness. It has always had poor performance and regardless of how well it's been built (visually) it's just not a good map for this engine. There's much clutter and details that can easily be reduced without affecting the look and feel of the map.

That said, cutting down on brushfaces (eg. turning round corners into corners with less sides) and better detailing (the outside rocky part with moving oil pump was set as structural...) can really add up over a map of this size and brushcount, even though something like this might sound trivial. The first compile test took 10 minutes less than before so mildly put, there's some room for improvement here.

**Comment by jdolan** [comment]
Yea, Jester's maps have often suffered from really long VIS compiles. I remember Stress Fractures taking 40 minutes on my 2008 era hardware. It's probably better now since you've tuned that one. I'm sure we could make a PVS hull for Gehenna and then make almost all internal brushwork `CONTENTS_DETAIL`, but still -- the fact that the map crashes the compiler *in threaded mode* indicates a serious bug in my code that I'd like to fix :)

**Comment by Panjoo** [comment]
@jdolan, Check this out:

I'm on old hardware so your compile times are probably a 3rd of mine :P
![optimizedvis](https://cloud.githubusercontent.com/assets/10857572/24565454/8dc02aba-1655-11e7-8785-4c0fb1e7dcf7.jpg)

https://github.com/jdolan/quetoo-data/commit/2a642b86b7f9b7759593ec2cf23e2affff6156d6

Been a big job again, took me probably 3 weeks on and off to fix and optimize this map. I can say it's now grown on me after so many hours.
I had to use every trick in the id-tech2 mapmaking book to get rid of some nasty brush and PVS errors. Even though I'm a Radiant user nowadays I still needed QuArK for its built-in error search plugins. It found a whole bunch of _microbrushes_, which you never want to have in your map. It causes the craziest errors. It's like having faulty RAM and you don't know it. Microbrushes come from all that curvy brush editing, draggin with vertices and mangling brushes by accident.
Also, I managed to bring down the brush count by a good 1100 brushes(!) without taking out too much details or change the look of the map. What I did was make curves less curved, making things flush with walls, take out some mangled pipes and replace them with simpler versions, etc.
Last but not least I used some proper Hint brushes (using the .prt file of the first long compile to actually see the portal clusters). What a mess it was.
For it to actually make a real difference I had to narrow most of the doorways and even relocate stuff. And to prevent having to wait for 45 minutes each time I wanted to try something, I used the bigblock method to block of other portions that didnt have a problem so I could focus on the trouble areas. But even then it went slow. 
I have a lot of experience with id tech2, but still... sometimes you run out tricks and it just won't work no matter what you do or try. But in the end the conclusion is that the map should just have been designed better in terms of openness and line of sight.

**Comment by jdolan** [comment]
That's awesome! Love the little changes. The Aerowalk jump pads look great. The huge panel lights look great. It sounds to me like you tweaked the ambient sounds quite a bit, too -- all good. I do miss the lava in the center atrium of the map, but the change you made is also cool. And yes, I can see at least 4 spots where you fixed mangled brushes. Nicely done, @Panjoo!

**Comment by kaadmy** [comment]
Just thinking, would this map look any better with an open roof and everything being green and growing instead of concrete/industrial theme?

**Comment by jdolan** [comment]
I think Gehenna has a very cohesive theme, and Pan just "finished" it. If you wanna go nuclear on a map, use Trial. It's rather boring and feels sort of "pointless."
