### ISSUE TITLE
Add proper muzzle flashes for machinegun/shotguns

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#315]
They currently spawn a puff of smoke in front of the player, which is weird because if you're aiming down/up it doesn't spawn anywhere near the barrel. We should see about using tags or something to have them spawn at a good spot.

**Comment by jdolan** [comment]
We could just lose the smoke puff ;)

**Comment by Paril** [comment]
We could, but having tags for weapon muzzle positions would also let us automate the lightning gun origin and have it work for new models implicitly (so long as the "barrel" tag exists), and we could use it for other effects too - could even have the server read it for weapon projectile positions down the road or something, for extra coolness.

**Comment by jdolan** [comment]
Good points!

**Comment by kaadmy** [comment]
Can .obj files have model tags?

**Comment by jdolan** [comment]
No, the tag is on the player model, not the weapon.

**Comment by kaadmy** [comment]
Ah, seems a little flaky as different weapons have different muzzle lengths.

**Comment by jdolan** [comment]
Barely. It's really not an issue if one gun is 2 units longer than another. They are aligned via tag to sit approximately the same on the player's arm, anyway.

**Comment by jdolan** [comment]
For 1.0, I think we should just remove the smoke puffs.

**Comment by jdolan** [comment]
Actually, @Paril's improvements to md3 tag orientation basically fixes this. Looks fine to me!

**Comment by Paril** [comment]
The tag system didn't change how this worked, it just gives us the ability to proper position it now :)

**Comment by jdolan** [comment]
I know, but how we rotate models (torso and head) now makes this a non-issue in my opinion. Retest for yourself. If you disagree, feel free to keep this open. But I thought it looked at least good enough.

**Comment by jdolan** [comment]
@Paril poke
