### ISSUE TITLE
Particle overdraw due to depth range hack

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#317]
https://www.youtube.com/watch?v=538hej6GTsw

The goal here is to prevent explosion particles from clipping into walls, while not screwing up other particles like in the video above.

CC @Thornation

**Comment by kaadmy** [comment]
I've also noticed this problem looking across Lilith looking towards the Mega Health ledge area while near the SSG (I think?)

**Comment by jdolan** [comment]
Yea, it's visible in a number of places.

**Comment by jdolan** [comment]
I think our options here are:

1) Remove depth range hack and just live with explosion particles clipping against walls.
2) Trace to the origin of the explosion. If the trace passes, add the particle with a flag to ignore depth. If the trace fails, add the particle without the flag.

@Paril thoughts?

**Comment by Paril** [comment]
The depth range hack is also what makes BSP flares not clip against walls. I don't think removing it is the best option.. maybe only flares should do it, though.

**Comment by jdolan** [comment]
Ah, that's right -- flares are just particles now, too.

Yes, so I wouldn't want to remove that particle flag entirely, but perhaps be more selective about the explosion particles that receive it.

**Comment by Paril** [comment]
Yeah, only coronas, flares, and any large temporary particles need them imo - not all ROLLs.
