### ISSUE TITLE
BSP submodel animation regression

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#319]
BSP submodel animations are no longer working. This probably has to do with the Cg_Interpolate refactoring. The buttons on Frag Pipe no longer use the red/green animation stages.

**Comment by jdolan** [comment]
Actually, this looks to be a regression in the materials refactor. I've confirmed in `Cg_AddEntity:369` that the animations are still being set on BSP submodels. But, for some reason, `R_UpdateMaterialStage:99` never happens. I think `r_view.current_entity` is set.

**Comment by Paril** [comment]
I saw the redness yesterday when I was testing his crash. I'll take a look though.

**Comment by jdolan** [comment]
False alarm. I'm an idiot.
