### ISSUE TITLE
Add a handicap feature (q3a-style)

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo#32]
The title says it all. Would be cool to have a handicap feature to allow people to play against others who are on a different skill level. I can't play some of my friends because it makes no sense dut to our differences in skill (match results are usually something like 30:0).

How handicap works: * each player has a handicap value that he can set in his config. It defaults to 100. * the weaker player does nothing (so he has 100) * the stronger player specifies a lower handicap value (like 70). This affects (weakens) him in several ways:

    he starts with <handycap-value> health instead of 100
    he can't pick up more than <handycap-value> health with normal medkits (but more with +5 bubbles and MH)
    if he hurts another player, he only does <handycap-value>% (per cent) of the normal damage 

There's no need to implement all of these (and others may also be introduced, of course), but a feature that does something similar to the things described here would allow me to attract a few of my friends to q2w. :)

Changed 14 months ago by jdolan

    owner changed from jdolan to wickedshell
    status changed from new to assigned

A userinfo cvar on the client could set this for the server, and the game module could then honor it in G_ClientRespawn_.

**Comment by kaadmy** [comment]
:+1: If this is still wanted, I can try implementing it.

**Comment by WickedShell** [comment]
@kaadmy go for it!
