### ISSUE TITLE
Console colors wrap lines sometimes

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#326]
Under certain circumstances, a console line ending in a color will bleed over to the next line.

**Comment by jdolan** [comment]
I think `say`ing something immediately before a `Com_Print` occurs is a good way to reproduce this one.

**Comment by Paril** [comment]
Pushed a fix, not sure if it's the most elegant thing in the world but it does work as we discussed days ago in IRC.

**Comment by jdolan** [comment]
Your subsequent fix was 🅰️ +
