### ISSUE TITLE
Secret door in Dark Zone is immune to dynamic lights

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#327]
For whatever reason, the secret door on Dark Zone will not take dynamic light. The other movers on the map work fine (e.g. the teleporters, which are `func_train`). @Paril is this something you'd mind taking a look at?

**Comment by kaadmy** [comment]
All secret doors or only that one?
Secret doors might have something funny with origins.

**Comment by jdolan** [comment]
Haven't looked yet. There's one near the Quad on Lava Tomb.

**Comment by Paril** [comment]
I'm pretty sure it used to take dynamic lights no problem, which is the weird bit. Is this something that worked before your recent pushes?

**Comment by jdolan** [comment]
I don't recall.

**Comment by jdolan** [comment]
Just a quick run-through of Q2DMX, plus Dark Zone, here are the movers I found that do not take lights:

![quetoo072](https://cloud.githubusercontent.com/assets/643118/21756948/c5ca197a-d5f5-11e6-9598-52ae0a08acd7.jpg)
![quetoo070](https://cloud.githubusercontent.com/assets/643118/21756949/c5cb99d0-d5f5-11e6-9705-17921a7b37d5.jpg)
![quetoo069](https://cloud.githubusercontent.com/assets/643118/21756950/c5cda7d4-d5f5-11e6-9ba5-762b68b48905.jpg)
![quetoo068](https://cloud.githubusercontent.com/assets/643118/21756951/c5dad594-d5f5-11e6-9eea-829945c5af4b.jpg)

**Comment by jdolan** [comment]
@Paril found the regression and it's been fixed, but a performance issue remains for R_MarkLight and R_StainNode with respect to r_view.vis_frame.
