### ISSUE TITLE
Server should log kill locations (xyz), client should support loading and rendering them

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo#33]
It would be incredibly useful to accumulate kill locations for each level, and allow designers/developers to load this information in the client to revise item placement and layout issues.

One option would be to include this information in the MySQL frags table; but a tool would be required to export the table data into a file format which the client could easily load for rendering the frags.

Ideally, the server admin would set e.g. sv_fraglog 1. The server would dump all new frags to a file, e.g. default/fraglogs/$map.log. The designer could retrieve this file and load it in their client, e.g. fraglog $map.log. The client would render frags as particles or even just points.

**Comment by kaadmy** [comment]
I think an SQL database is already handled somewhat for fraglogs, how difficult would it be to continue this?
Also, it might be nice to extend positition data to position+camera direction+attack direction+weapon.

**Comment by jdolan** [comment]
We already have a way to render kill locations: stainmaps ;) Closing this out.
