### ISSUE TITLE
Particle trails disappear with normal network latency

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#330]
`net_loop_latency 100` yields almost no particle trails at all. Interestingly, lowering `time_scale` will bring the trails back, but there's something off with the timing logic for trails.

**Comment by Paril** [comment]
The way trails get rendered causes this. If we store the last position that the trail was rendered at, and use that instead of the prev position, it'd probably work.

**Comment by jdolan** [comment]
We do that now. You added that some time ago. They're still broken :)

**Comment by Paril** [comment]
I did but reverted it because it wasn't working properly at regular FPS. Currently the game just does previous_origin -> origin, and if frames are skipped they will be the same value.

**Comment by jdolan** [comment]
That all sounds right to me, tho. I wonder if this is just a matter of using `cgi.client->time` where we should be using `cgi.client->unclamped_time`.

**Comment by Paril** [comment]
No, the issue is the way previous_origin works - it's set to origin if the entity is not delta'd, which is what happens when you miss a frame.

**Comment by jdolan** [comment]
But we're not missing server frames. We're simply receiving them with delay. `net_loop_latency` does not simulate packet loss. It only adds a delay for all packets. This is a timing issue. As I mentioned above, lowering `time_scale` in conjunction with `net_loop_latency` actually "fixes" the issue.

**Comment by Paril** [comment]
I'll try that, but the origins end up matching (as in it tries drawing trails over 0 units) so I don't think that's the problem.

**Comment by Paril** [comment]
high jitter/latency also causes this issue: https://gfycat.com/LivelyGlaringDingo
Cl_ReadDeltaEntity causes this one. I think the logic issue is in there, and is the same problem for trails.

**Comment by jdolan** [comment]
This is finally fixed.
