### ISSUE TITLE
Respawn killbox doesn't always work

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#332]
It's possible to spawn and get stuck inside of another player. Easy to see if you have bots play each other - eventually you'll come across ones that have spawned and are shooting inside of themselves.

**Comment by jdolan** [comment]
Might be missing a LinkEntity call somewhere in the AI code? I've play-tested telefrags quite a bit this winter..

**Comment by Paril** [comment]
AI doesn't ever need to link entity, it just calls the client respawn stuff. It telefrags like 90% of the time, there's an edge case it seems where the player is not fully inside another player that it happens. Usually the other player ends up half way above the other player.

**Comment by jdolan** [comment]
@kaadmy Where did you end up with this? Did you want to push something for review?

Side note: I created this gist that captures a design I think would work without the complications we're seeing now:

https://gist.github.com/jdolan/b662d86145a0336bcccaa43c6c18ffd4
