### ISSUE TITLE
Prediction error on stationary bsp inline models

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#335]
Even tho it is stationary, the secret door in Dark Zone yields a prediction error. The client should have up-to-date information for this entity, and should be able to predict against it.

**Comment by jdolan** [comment]
This may seem like a trivial bug when running around on localhost, but with `net_loop_latency 100` you can quickly see how this stinks :(

**Comment by Paril** [comment]
Hell I can even see it on localhost, which is weird.. even stepping down/up doesn't work. I wonder why this bmodel in particular is so bad.

**Comment by Paril** [comment]
This was introduced by c83a809bee7ce9960eb79ed2ea64f8530b8378d2 - specifically, BoxIntersect in Cl_ClipTraceToEntities. abs_min and abs_max don't seem to match the actual entity's abs_min/abs_max on the server.
