### ISSUE TITLE
Changing maps causes PVS to break sometimes

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#337]
Likely some sort of lerp issue, but it's pulling data from the prior server. PVS and screen flashing seem to be the most obvious things that can happen.

**Comment by jdolan** [comment]
Steps to reproduce?

**Comment by Paril** [comment]
"map edge", pick up item, "map edge", watch screen flash like you just picked up item again. If you take damage, "map edge" will cause screen to flash red.

Not sure if related, but sometimes a map switch will cause PVS to go out of wack as well. That one is much rarer.

**Comment by Paril** [comment]
Fixed the flashing, those were just static variables that never got cleared, but the PVS issue still crops up every now and then.

**Comment by jdolan** [comment]
Downgrading to minor, as you've fixed the more common problem, and frankly, I've literally never seen this before, so unless it's Windows-specific, I can't imagine it happens with great frequency.

Fwiw, I consider bugs to be critical if the game is unplayable or crashes under normal conditions. Major would be for bugs that are non-breaking, but highly reproducible. And minor for non-fatal, corner-case run of the mill bugs.

**Comment by Paril** [comment]
I saw this issue again recently when messing around, so this might not be fixed yet. I'm banking on it being some sort of areabit issue.

**Comment by kaadmy** [comment]
Has anybody been able to reproduce this recently?

**Comment by jdolan** [comment]
I've still literally never seen this. @Paril I'll leave it to you if we're going to do something here..

**Comment by kaadmy** [comment]
I've seen this once or twice, I haven't been able to reproduce ever.
