### ISSUE TITLE
Bot brainstorm - game locality sharing, etc

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#339]
Going to use this issue so we can keep track of questions/concerns with the bot system as we move forward.

So, currently, the plan is to have libai be a completely separate entity to game - like the server, it won't be game-local and as such will have a lot of opaque data pointers in g_entity_t/g_client_t. This means that libai will also need some imports/exports, which is all good.

The upsides to this is that:
- libai can essentially run on its own without an actual game going (although of course cmodel will need a BSP loaded, entities will have to be spawned, projectiles will have to function, etc for things to work right)
- little no to cross-over between the game and libai's code; the game will contain barely any ai-specific code (only the function calls and cmds, essentially) and libai won't contain any game code.
- libai can exist on any mod without requiring a rebuild, so long as the mod adjusts any game-specific AI code that might be required (item setup, weapon priorities, etc)
- libai can be DLL, and can be loaded by server - the exports/imports can be communicated over to the game via the server.
- since libai won't touch opaque structures, there's no chance that a mod changing anything in x_locals_t can cause crashes or memory corruption

The downsides:
- the game stores certain important pieces of information in the locals structs that the bot will need. In the current code, the only two that are required are angles and ground_entity. Both of these are pm_move_t, technically. We may be able to resolve this one by having a pm_move_t struct communicated back to the caller of ClientThink; only the bot needs this, though, and I'm not sure how we feel about changing signatures to satisfy the bot's needs. In the future, there will be more game-specific locals required by the bot: it will need to have knowledge of its inventory, it will need to know the velocity of entities (for projectile prediction), it should have access to "dead" (SOLID_DEAD works currently but it feels hacky to me), it will need to know about mover's states (for riding platforms), "item" for item-based entities, client stuff like current weapon, weapon state, weapon fire time, etc. How do we communicate all of these specific pieces of data to the bot when it needs them?
- the bot can't directly modify any local structs to perform actions; for instance, it can't set next_weapon to pick a weapon to change to, it will need either a special function or it can call ClientCommand with constructed args to properly simulate a player changing weapons.
- the bot won't have access to g_item_t, it will be an entirely opaque pointer to them. How do we handle this one?

We'll also need to figure out everywhere that the AI system will need notifications raised from - for instance, item pickups should ping the bot in case he needs to perform any actions (picking up flag changing nav target), player being killed should ping the bot, it may want to respond to "say" messages as well in the future.

**Comment by jdolan** [comment]
I think that libai could / should expose types for all of it's decision-making inputs (item abstraction, player state and inventory abstraction, etc). The game module can then allocate, populate and associate instances of these types to g_entity_t or g_client_t. This means that the game will depend on ai_types.h, but I think that's fine. This approach will require is to "mirror" some information that the game already knows / tracks, and place it into structs that libai will consume. But .. I don't see a way around that.

As for a generic event broadcasting system, we could probably get by with something dead-simple, like:

```c
typedef enum {
   AI_EVENT_ABC,
   AI_EVENT_XYZ,
   // ..
} ai_event_type_t;

extern void Ai_Event(const ai_event_t *event, const void *data);
```
Where `Ai_Event` just loops over active AI's and lets them act on the event via state machine.

**Comment by jdolan** [comment]
Per IRC discussion for AI / server / game interfaces / integration:

1. The server will `OpenLibrary libai.dll` on-demand, just like it does the game module, and maintain a pointer to the resulting `ai_export_t` that `libai` initializes and returns.

```c
ai_export_t *Sv_LoadAi(ai_import_t *import);
```

1. A `cvar_t` should control the directory name of the `libai` that is loaded. For the game module, we use `"game"`. Should this just be `"ai"`? Probably.
 
1. The server will extend `g_export_t` to include an entrypoint to the on-demand load routine:

```c
// game.h, g_import_t
ai_export_t *LoadAi(ai_import_t *import);

// sv_game.c, Sv_InitGame
import.LoadAi = Sv_LoadAi;
```

1. The game module can elect to call this entrypoint from `G_InitAi` to initialize libai. It's then up to the game to maintain a reference to the returned `ai_export_t`.

**Comment by jdolan** [comment]
1. The server will `CloseLibrary libai.dll` on shutdown. The game module does not have to worry about it.
