### ISSUE TITLE
Sprite functionality via materials/surface flags

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo#34]
It would be nice to be able to get textures to behave like sprites using either the material definition or a surface flag. This could be useful for sfx like flares or background/small details.

An additional feature that would be nice to have a special sprite function that restricts the sprite's rotation to its longest axis, similar to what 'deformvertexes autosprite2' does in q3 . This is especially useful for things like long animated energy beams.

Q3map2 shader manual entry for autosprite2: http://q3map2.everyonelookbusy.net/shader_manual/ch2.htm#deformvertexes

Vertex deforms have been a // TODO: for quite a while. I'll try to get these done for the beta.

**Comment by jdolan** [comment]
I think what you're describing here is really a particle emitter. I dig it.

**Comment by jdolan** [comment]
I don't think this is necessary for 1.0, but for some rainy day, this would be a nice feature to add to your particles system.

**Comment by jdolan** [comment]
In doing a little tuning on Torn Glory, I actually think we've got this functionality covered already with flares -- which are now particle emitters, thanks to @Paril. Mappers can define a surface and apply a flare to it. They can even make the surface itself `SURF_NO_DRAW` if they only want the flare. I think we actually need to start taking advantage of this in adding some interesting looking flare sprites:

![quetoo057](https://cloud.githubusercontent.com/assets/643118/21590609/6cc9e8fc-d0cb-11e6-8a22-9316e6b01ad3.jpg)
