### ISSUE TITLE
Trying to clear the console crashes game

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#342]
Yesterday while trying to find cvars for botplay(:P) I was going through cvar_list and and wanted to clear the console by doing a `/clear` or `clear`.
What happens is the console clears and you can still access the Menu but the next command you type will crash quetoo. Even `quit` will crash it.

**Comment by jdolan** [comment]
This was a regression in @Paril's fix for #333. I blame glib's rather poorly named queue API. Thanks @Panjoo!
