### ISSUE TITLE
Switching spectators causes a frame of an odd view angle/origin (lerp issue?)

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#351]

**Comment by jdolan** [comment]
Yea, when `Cg_UsePrediction` returns false (as it does when you're spectating), we always just lerp from previous to next snapshot. There should probably be some additional logic in `Cg_UpdateView` and `Cg_UpdateAngles` to disable lerp if the view origin changes by some threshold.

Perhaps a more elegant way of handling this would be to detect this condition earlier (in the client?) and force `cl.lerp = 1.0`.

**Comment by jdolan** [comment]
This is fixed.
