### ISSUE TITLE
Qforcer's visor is not drawn with blend

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#354]
The Q3 `.skin` files had a way of enabling blend for certain meshes. I think our materials system has this, too. But I don't think we act on it correctly, and we certainly don't use the right blend function for Qforcer's visor. His visor is rendered fully opaque.

I'm not sure if simply editing the skin to include an alpha channel, and then reducing alpha on the visor parts of the skin, would fix this.. but it'd be great to get those evil red eyes visible in game.

http://www.tabun.nl/3d_work_view.php?view=m_qforcer

![qforcer_preview_s](https://cloud.githubusercontent.com/assets/643118/22346157/0a4005ea-e3d1-11e6-925a-78d50bf8cd42.jpg)

**Comment by Paril** [comment]
So, currently we don't even have materials for the player models at all, and our .skin files just link groups to tga files I believe.

I think we can fix this just by having a material file for tris.md3 and setting up a material for default_v. I'll play around with it.

**Comment by kaadmy** [comment]
Any progress on this?

**Comment by jdolan** [comment]
Yes, this is fixed. Nice one @Paril
