### ISSUE TITLE
Better versioning in executables (config.h?)

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#356]
Ideally, I'd like config.h to include the name of the branch and the commit ID that the executables were built with, and then printing them at the beginning of launches (eg "Quetoo 0.1.0 Jan 27 2017 Win64 master f0e248483c8fbe8e684035b11e23f53ebffd2ffe"). This would be nice for verifying that users are on the right versions and with debugging crashes, since the PDBs will only work properly with the sources from that specific commit.

I think this could all be done in build scripts, and non-committed (working dir) builds could probably just list the commit ID as "-" or something to tell them apart from official builds.

Another reason that I'd want this is for eventual Steam distribution. Steam has branches for releases, and we may want to use a beta branch to test bleeding changes without messing with the master one. We can have the automatic build tools push to the right Steam branches.

I also think we should pin down our versioning strategy - we're currently at "0.1.0 BETA", and my guess is that at launch it'll be "1.0.0" or something. I figure this BETA tag can instead just be the branch tag, and we'd make a beta branch that we work on as our "live" branch and push to master only when it's good enough to be staged. We needa know when to change version numbers and what should qualify as a change.

Versioning is hard :(

**Comment by jdolan** [comment]
I'd like to start writing out a git SHA as part of the per-platform builds, and pushing it to S3 underneath the platform-specific directories.  Call it `version`.

    http://quetoo.s3.amazonaws.com/x86_64-apple_darwin/Quetoo.app/Contents/MacOS/Resources/version

We should then clean up the libcurl code in the client, and include a fetch-and-compare of this version file on startup. If the comparison fails, prompt the user to update and relaunch.

**Comment by jdolan** [comment]
Of course, Steam would handle a lot of this internally, wouldn't it?

**Comment by Paril** [comment]
That might work, ideally it'd be embedded in the actual executables though - that way if somebody has an outdated .exe file somehow we can actually tell, whereas the version file might be being updated properly and not the executable.

**Comment by Paril** [comment]
And yes, Steam would handle that bit internally, but having a version identifier somewhere is still handy for debugging purposes - like I said, if somebody has a crash and we're several commits ahead, having the commit ID visible in the crash dump or in their client/logs makes it easy to figure out what source files match the debug files.

**Comment by jdolan** [comment]
I agree that it'd have to be baked into the binaries, too -- but we'd want to push the file out to S3 so that the client can automatically check the remote version against its own.

**Comment by Paril** [comment]
Oh good point, sounds good!

**Comment by jdolan** [comment]
I've updated the build to include `REVISION` (renamed `COMMIT_ID`, sorry). I think we can defer the remote version compare, especially if we're going to pursue Steam anyways.

The Windows build does need some minor adjustment for the variable renaming. 

Closing this one out.
