### ISSUE TITLE
Crash during client animation

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#357]
I've ran into this bug a few times, and we were able to semi-reproduce it after a lot of recording by changing maps. The crash happens in Cg_AnimateClientEntity. With the debug data I can't exactly read the stack stuff, but it crashes here:

	const cl_client_info_t *ci = &cgi.client->client_info[ent->current.client];
	const r_md3_t *md3 = (r_md3_t *) ci->torso->mesh->data;

	Cg_AnimateClientEntity_(md3, &ent->animation1); <------

with an access violation. The exact point of crash might be the line before it, sometimes it's not precise. If Cg_AnimateClientEntity_ is being inlined, this info will be a bit useless since it won't show me what part of that inlined code is crashing.

**Comment by jdolan** [comment]
Seems plausible that, after recording / watching demos and changing maps, we could get into a state where the client_info's are pointing to stale models. This might even be compounded by the player setup menu, which also attempts to keep the user's client model loaded.

**Comment by jdolan** [comment]
To debug this further, I'd consider commenting out the guts of the player setup menu so that it's no longer attempting to resolve client_info_t. Then see if this crash still happens.

**Comment by Paril** [comment]
The menu was never used in this case, so it is unlikely to be related, but the other points are probably valid.

**Comment by jdolan** [comment]
![screen shot 2017-01-27 at 6 51 31 pm](https://cloud.githubusercontent.com/assets/643118/22404795/20973c1e-e606-11e6-83c9-f82e34983cab.png)
![screen shot 2017-01-27 at 7 17 25 pm](https://cloud.githubusercontent.com/assets/643118/22404797/22338956-e606-11e6-9958-262cd0ed56a0.png)

**Comment by jdolan** [comment]
Probably related: Spawn into the game, and change skins at the console:
![quetoo075](https://cloud.githubusercontent.com/assets/643118/22404892/2439efc2-e608-11e6-9304-cdc0a80671ad.jpg)

**Comment by jdolan** [comment]
@Paril Did you fix this bad boy?

**Comment by jdolan** [comment]
As far as I'm aware, no one hit this in last night's 2-hour 7 player game. I'm going to close out.
