### ISSUE TITLE
Crash on trying to connect to any server

### ISSUE THREAD

**Issue by adem4ik** [jdolan/quetoo#359]
OS: Windows 10 x64
GFX Card: Nvidia GTX 650 1GB
RAM: 8 GB

1) Download Windows 10, Windows 8, Windows 7 SP1 - "Installer for Windows 64 bit" from quetoo.org & unpack it
2) Start the game by Quetoo\bin\quetoo.exe
3) Click on "Multiplayer" menu button
4) Choose any server and click on "Connect"

Result: Game stops to react on any input, notification window about crash appears after pressing Alt+Tab. Dump file appears near the executable: https://yadi.sk/d/pwEICXpN3BdMeS (for some reason that zip archive can't be attached directly on github)

**Comment by jdolan** [comment]
Hi, thanks for the bug report. Did you run `quetoo-update.exe` first?

**Comment by adem4ik** [comment]
No I didn't. It was a fresh download from the site.

Just checked it:
- run quetoo-update.exe
- then tried the case again
Result: got the same crash

**Comment by jdolan** [comment]
Okay, thanks for that. @Paril can probably take a look at your crash file at some point soon. I'm on OS X and wouldn't know the first thing about a damp file.

**Comment by adem4ik** [comment]
Great, thanks for reply!

**Comment by kaadmy** [comment]
@jdolan dump file...?

**Comment by Paril** [comment]
I believe this was due to the servers being outdated. Are you able to load maps locally with "map edge" in console?
