### ISSUE TITLE
Unable to reconnect to some servers during map changes

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#360]
No details on this yet, nor steps to reproduce. But in play-testing the other night, several times my machine got into a state where it would just sit in loop trying to connect to @Paril 's server. On Paril's side, he was seeing a flood of datagrams from my host. So something is wrong in the protocol  handshake here.

**Comment by jdolan** [comment]
@Paril Do you think that this issue was wrapped up in #364's fix?

**Comment by Paril** [comment]
I think this is fixed with d69616892c85f6201f5277f6a066a69e1b7af4c7 actually - I have a feeling his qport was 0, so it was changing every time he connected causing ghost clients.
