### ISSUE TITLE
Ripples are only visible from outside water

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#361]
If you shoot up through water (and or presumably if someone else jumps in the water with you) there should be a ripple visible in the water.  It appears to only put a ripple on the top side/isn't rendered from below the water? (Tested on edge)

**Comment by kaadmy** [comment]
I don't know about (partially) opaque water on edge, but when I did the ripples I tested firing upwards through water too.

**Comment by jdolan** [comment]
*If* the water volume in question is not `MASK_BLEND` then we should spawn ripples on both sides of the face.

**Comment by Paril** [comment]
Ripples also don't work on angled water surfaces.

**Comment by kaadmy** [comment]
I couldn't find any angled water surfaces anywhere so I just stuck with a flat ripple, maybe this could be  changed.

**Comment by jdolan** [comment]
It'd be fairly straightforward to send the surface normal over the wire for each ripple.
