### ISSUE TITLE
On death view falls through the floor

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#362]
Not sure how noticeable it is at normal framerates but it stands out when valgrinding (or anything else that drops framerate to a crall), when you get killed and the camera falls sideways you get at least a frame where you are seeing through the floor as the camera clipped through it.

Not sure how long it lasts, it's hard to tell when you are running at <1 fps :)

**Comment by kaadmy** [comment]
Try moving with fps <10 or so

**Comment by jdolan** [comment]
The death view in general is a little jarring. It needs some work.
