### ISSUE TITLE
Issues with "ghost" players

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#365]
- [ ] Butane had issues with crashing and whatnot, so sometimes he'd leave a ghost in the server - it'd take like 3 minutes or so before the server would boot it.
- [ ] The ghosts seem to mess up userinfo for the client or something, as one of the three players in there were then named "newbie". Server userinfo was fine.
- [ ] Butane reconnecting did not automatically boot the other Butane, even though they have same IP. qport difference maybe? Not sure about this one.
- [ ] Changing maps with a ghost client and hitting tab caused crash at call to Cg_DrawScore (inlined)

**Comment by jdolan** [comment]
I think these things all make sense *if* sv_timeout is 300 by default.

**Comment by kaadmy** [comment]
Would a fix be to tell Butane to use the bleeding edge version?

**Comment by kaadmy** [comment]
I think this has been fixed?

**Comment by Paril** [comment]
They all should be - my only concern now is that sv_timeout is way too high. If we've stopped receiving messages from a client for 20 seconds, I think it's safe to say they can be dropped. Right now it waits 120 seconds.

**Comment by jdolan** [comment]
True.

**Comment by jdolan** [comment]
Timeout issue addressed, feel free to close.
