### ISSUE TITLE
Changing model in-game to/from guard causes invalid frames

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#371]

**Comment by jdolan** [comment]
I think I partially fixed this yesterday. If a client config string changes, I reset the corresponding entity's animations. You can see this in Cg_UpdateConfigString. I still would see a few warnings about frames, but it would recover and render the model correctly at least. 

PS I'm on an airplane.

**Comment by Paril** [comment]
I had updated to that and it still broke, so I don't think that was the fix.

**Comment by Paril** [comment]
Fixed in 70defb3
