### ISSUE TITLE
Changing to many maps eventually results in a media-related crash

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#372]
Crash happens in R_RegisterMedia_Compare attempting to read from a null "name". Seems like we got ourselves a leak of some sort.

**Comment by jdolan** [comment]
There's actually a working unit test for the media registration / unregistration. Might be worth resurrecting the test case to narrow in on this one. See `src/tests/check_r_media.c`

**Comment by kaadmy** [comment]
_TFW you decide to check Github notifications after a few hours and someone commented on an issue 30 seconds ago._

**Comment by jdolan** [comment]
Oh snap, what was the fix for this?

**Comment by Paril** [comment]
Fixed in fa4d500c139e7cd9e07bbbf22a1c6bc4929c73c3
Maps with shared materials with the map you're changing to would leave some invalid material pointers in renderer. I fixed this by making certain that all of the references are not stale when we pass them along, and freeing old ones if we're replacing the material.
