### ISSUE TITLE
QForcer player model animation warnings

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#378]
When changing to the QForcer player model, I get this warning printed twice: `R_GetMeshModelTag: players/qforcer/upper: Invalid frame: 179` (The frame number is arbitrary)

**Edit:** In the main menu only, it seems.

**Comment by jdolan** [comment]
Pretty sure this has been fixed. I was mucking with it, so was @Paril, and I can't reproduce this anymore either.

**Comment by kaadmy** [comment]
Even in the main menu?
I forgot to mention that, I filed this before I knew it was only in the menu.

**Comment by jdolan** [comment]
Ah, yes, this does still happen in the player setup menu. Thanks.
