### ISSUE TITLE
Color appears to be broken

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#380]
Any color string (green/blue) is no longer recognized and shows a red blaster trail. default still gives yellow, and then if you set it to 111111 you get a purple trail... Not sure if this is a real issue, or if the cvar docs are just out of date and everyone has old binds...

**Comment by Paril** [comment]
Color strings were never recognized, they were always integers. "color" is a hue value, from 0 to 360.

**Comment by WickedShell** [comment]
Green used to be valid... Like 5 days ago :)

**Comment by kaadmy** [comment]
Did anything other than `green` work correctly or just random chance? ;)

**Comment by jdolan** [comment]
`green`, `red`, `blue`, `yellow`, `white`, `pink`, `purple`, `orange` all used to work.. but now we've got 360 choices. Note: we did lose white, which is a shame.

**Comment by kaadmy** [comment]
Can't color just be hexidecimal, ie. FF00FF?

**Comment by Paril** [comment]
That's how it was implemented originally, but it caused issues because people could have invisible particles by getting close to black (since blaster/rail particles are additive, so 0 + 0 = 0).

By only being a hue, we can ensure that all players' effects have the same physical brightness.
