### ISSUE TITLE
Allow players to use model but force team skin

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#383]
Currently, good and evil are both qforcer/blue and qforcer/red. It'd be nice if the player could still use their model, but we force the skin name in teams.

**Comment by kaadmy** [comment]
This is related to having pant/shirt skins, then any model could have any color with almost no effort.

**Comment by Paril** [comment]
Nah, Quake 2 supported this even without pant/shirt colors. Just have to only change the skin.
