### ISSUE TITLE
HUD cleanup

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#389]
Cleanup HUD, chat, etc.

- [x] Add killfeed and add an option to also show the console killfeed.
- [x] Move player info (joining/leaving/timeout) into chat feed
- [x] Make opening the chat show a chat backlog
- [x] Fix the "Ready" text overlapping in team+matchmode on the HUD's right side.
- [x] Move spectators into a separate, more compact portion of the scoreboard (only need to show name and ping) (Related to #381)
- [x] Identify your target on the HUD (Related to #388)
- [x] Voting display (percent of yes/no votes, current vote, time left)

**Comment by jdolan** [comment]
Good bit of work here! I'm in favor of these changes, tho. I guess one thing to consider is.. do some / all of these elements become MVC components, or do we carry on with Quetoo's ad-hoc drawing routines?

**Comment by kaadmy** [comment]
I have no idea how customized ObjectivelyMVC's rendering is, I'll probably try to use it though (JSON bindings if I can figure out how)

**Comment by kaadmy** [comment]
If we're sticking with our current HUD rendering for the time being, I'd like to get this issue cleaned up.

**Comment by jdolan** [comment]
See #487

**Comment by jdolan** [comment]
I'll pick up the torch on this branch. And no @Paril, I won't rewrite the entire HUD in ObjectivelyMVC, at least right now ;) Tho, I have to say, JSON based layout with CSS probably sounds pretty attractive to modders..

**Comment by jdolan-chwy** [comment]
The only thing left here really is the respawn timer / countdown. I quite liked that feature in @kaadmy 's old branch.
