### ISSUE TITLE
quemap should support system paths in addition to game paths

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#391]
This would eliminate a lot of confusion / issues integrating with editors.

**Comment by kaadmy** [comment]
I thought it used PhysFS and might be pretty hard to implement, because you'd have to work your way around the sandbox?

**Comment by jdolan** [comment]
It does use PhysicsFS. Doesn't mean I can't call `fopen` when I want to ;)

**Comment by kaadmy** [comment]
Another thing I thought of is adding a custom load path in the directory the specified file is in.

**Comment by jdolan** [comment]
This is now fixed.
