### ISSUE TITLE
Friendly shutdown on crashes

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#393]
When Quetoo crashes (For some errors at least, like wrong GL version, couldn't load shaders), there should be a GUI friendly dialog telling the user that something happened and to report it.

[`SDL_ShowSimpleMessageBox`](https://wiki.libsdl.org/SDL_ShowSimpleMessageBox) is a fairly common way of doing this, Steam and most Steam games use this for example.

**Comment by jdolan** [comment]
Good idea! We should try to grab the backtrack and include it in the dialog.

**Comment by kaadmy** [comment]
I don't think SDL2's dialog handles anything other than a single line of text, maybe it'd be a good idea to dump the crash log to a file and push it to a remote server, although Steam possibly does this already for some stuff.

**Comment by kaadmy** [comment]
At least assertions should pop up a simple dialog telling the user what assertion failed.

**Comment by Paril** [comment]
It does on Windows because of the crash dumping, but there's no fatal error close for missing data. We def need that.

**Comment by kaadmy** [comment]
Then why did I get an assertion using latest compile? Are those debug builds or did I mess up something on my end?

**Comment by jdolan** [comment]
Better crash handling, messaging and testing of `Com_Error` handling is definitely required for 1.0

**Comment by Paril** [comment]
Windows has a dialog that appears on crash now for ERROR_FATAL/recursive errors with the option to generate a crash dump (when Sys_Backtrace is called, basically). If the game crashes by regular means, like a segfault, the game will generate a dump immediately.

It'd be nice to have these cross-platform though.

**Comment by kaadmy** [comment]
For `SIGSEGV` and other crashes that don't have a chance to call a clean shutdown, should Quetoo just run through a bat/sh script or something to catch errors and open a dialog?

**Comment by Paril** [comment]
Clean shutdown is not required to open a dialog - you do that before attempting to shut down, generally.
