### ISSUE TITLE
Hook relaunch speed - Working as intended?

### ISSUE THREAD

**Issue by Dracant** [jdolan/quetoo#396]
If you launch the offhand hook, or just tap it, there is a delay before you can launch the hook again.

Preference is no delay in sending out hook again.

Thanks!

**Comment by Paril** [comment]
This is to prevent people from spamming the hook button to create an excessive amount of sound or abuse it by doing damage to an enemy. Intentional.

**Comment by kaadmy** [comment]
Maybe just decrease the refire time? What is it right now?

**Comment by Dracant** [comment]
I certainly understand your reasoning, but man is it annoying when you miss-fie the grapple and have to wait to refire it.

Maybe just reduce the delay?

**Comment by Paril** [comment]
It's a punishment. Don't miss yer hooks! :)
