### ISSUE TITLE
func_rotating is broken, at least in relation to origin brushes in old Q2 maps

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#397]
These seem to create huge rotating brushes that don't work properly. lmctf2a has fans at the top that are all out of whack.

Another maybe-related issue is that BoxEntities returns rotating brushes, etc even if you're not actually intersecting the brush - KillBox will gib you for spawning near a func_rotating that happens to catch you in its net.

**Comment by jdolan** [comment]
It'd be great to at least resolve the origin brush issue. I think there was a hack in Quake2 for BSP entities with bad origins. This rings a bell. Probably worth reviewing the Quake2 server / collision loading code and looking for comments around "bad origins."

**Comment by Paril** [comment]
This is related to #401 as well since the rotator I saw was not rotating around the proper axis.

**Comment by kaadmy** [comment]
Does this still happen now, or has it been fixed with #401?

**Comment by Paril** [comment]
I need to find a map that was broken pre-push and test it again. I couldn't find it. It was one of the lmctf maps.

**Comment by kaadmy** [comment]
`lmctf2a`? You mentioned that in a previous comment.

**Comment by Paril** [comment]
Oh, thanks. This issue is actually fixed - lmctf02a itself is broken. I checked in Quake 2, the origin brush was not set properly (origin contents weren't applied to it).
