### ISSUE TITLE
Build failing on Arch Linux

### ISSUE THREAD

**Issue by adomas187** [jdolan/quetoo#400]
I am building quetoo from source on GitHub with help of Arch Linux AUR (yaourt tool) and when compiling code I get this error:
CC       cgame_la-cg_view.lo
CCLD     cgame.la
make[5]: Leaving directory '/tmp/yaourt-tmp-adomas/aur-quetoo-git/src/quetoo/src/cgame/default'
make[4]: Leaving directory '/tmp/yaourt-tmp-adomas/aur-quetoo-git/src/quetoo/src/cgame/default'
make[4]: Entering directory '/tmp/yaourt-tmp-adomas/aur-quetoo-git/src/quetoo/src/cgame'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/tmp/yaourt-tmp-adomas/aur-quetoo-git/src/quetoo/src/cgame'
make[3]: Leaving directory '/tmp/yaourt-tmp-adomas/aur-quetoo-git/src/quetoo/src/cgame'
Making all in main
make[3]: Entering directory '/tmp/yaourt-tmp-adomas/aur-quetoo-git/src/quetoo/src/main'
  CC       quetoo-main.o
main.c: In function ‘MemStats_f’:
main.c:284:54: warning: format ‘%zd’ expects argument of type ‘signed size_t’, but argument 3 has type ‘guint {aka unsigned int}’ [-Wformat=]
  Com_Print(" [console] approx. %zd bytes - approx. %zd blocks\n", console_state.size, console_state.strings.length);
                                                      ^
  CCLD     quetoo
../../src/client/.libs/libclient.a(libshared_la-shared.o): In function `g_stri_equal':
shared.c:(.text+0x2717): undefined reference to `stricmp'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:478: quetoo] Error 1
make[3]: Leaving directory '/tmp/yaourt-tmp-adomas/aur-quetoo-git/src/quetoo/src/main'
make[2]: *** [Makefile:869: all-recursive] Error 1
make[2]: Leaving directory '/tmp/yaourt-tmp-adomas/aur-quetoo-git/src/quetoo/src'
make[1]: *** [Makefile:454: all-recursive] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-adomas/aur-quetoo-git/src/quetoo'
make: *** [Makefile:386: all] Error 2

Make version:
GNU Make 4.2.1
Compiler version:
gcc (GCC) 6.3.1 20170109
Building on x86_64 system.

**Comment by jdolan** [comment]
The build was legitimately broken; wasn't Arch specific -- was @Paril specific ;) All set now. Thanks for catching!
