### ISSUE TITLE
Spawnflags of funcs (and others?) not matching with Q2

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#401]
For most of the spawnflags not matching, it's not been an issue (like items spawning in mid air, which is fine for Quetoo since they bounce, although they may not end up in the same spot as they do in legit Q2 since they can roll down hills), but some (esp func_door and its kin) have very specifically placed spawnflags that, when trying to load a Q2 map with them, completely break the functionality of the doors.

I know Q2 isn't a top priority to support but maybe on a rainy day it'd be worth fixing these up so they match up again.

**Comment by jdolan** [comment]
We should do it sooner, rather than later, before we have [more] Quetoo maps with doors.

**Comment by Paril** [comment]
Alright, I can do it in this branch while I'm here. I hope Pan doesn't yell at me.

**Comment by jdolan** [comment]
* darkzone
 * fragpipe
 * lavatomb

Those 3 have doors. If you could regression test them, I think that'll cover us. Thank you!

**Comment by jdolan** [comment]
Don't forget quetoo-data/target/default/scripts/entities.def as well as the source comments :)
