### ISSUE TITLE
quemap console issues on Windows

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#403]
quemap (and possibly quetoo-dedicated and quetoo-master?) have console handling issues on Windows. `stderr` is apparently not being printed anywhere. The application creates its own console window even when launched from the command line, etc..

In general, I don't think quemap should ever need to allocate a console window. If it's launched from a .bat file, Windows will allocate a console for it anyway, right? If it's launched from the command line, just use the console it inherits. If it's launched via Radiant, it's going to communicate over the socket to Radiant and no console is necessary.

quetoo-dedicated and quetoo-master should only allocate a console if they are launched from Explorer. Otherwise, they should also inherit the console they were spawned from.
 
@Paril is this something you could take a look at? I have no way to test any changes. We've got people itching to map, and our tools suck :(

**Comment by Paril** [comment]
Fixed in ae6c67fe7e7d0ec1f793f56391fa3a3e313b2a90
