### ISSUE TITLE
Console autocomplete: PhysicsFS pak enumeration skips files

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#407]
(This existed prior to my cvar change so I don't believe it's related)

There's a few issues with autocomplete when a lot of potential values are involved.
- [x] If you have a lot of maps, it can take a long time to scroll through them all in the console. It'd be nice if autocomplete could set up columns or something based on current console size.
- [ ] Some maps seem to be missing from map autocomplete. I have several mod folders set up, and for some reason several q2ctf<n> maps are missing despite "map q2ctf1" working, for instance. It's very odd.

**Comment by Paril** [comment]
Fix for point 1 is in 290c8bf.
Point 2, we have discovered, is an upstream issue with PhysFS's pak EnumerateFiles implementation.

**Comment by jdolan** [comment]
I think you grabbed the wrong commit hash, but cool!

**Comment by Paril** [comment]
#1 fixed properly in 0e0b6332924a47d010e71b0a727709bdce1bbcb5

**Comment by jdolan** [comment]
This will be addressed by #496 and therefore I'm going to close out.
