### ISSUE TITLE
armor respawn times

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#414]
(Labeled enhancement:high because this really matters to gameplay.)

I really don't see what would be wrong with having the armors respawn faster. If your timing is off it can feel like they're not respawning at all.

RedArmor = still 1.5 minutes! Geez, as long as quad. YellowArmor/GreenArmor = 1 minute!
And then Shards = 20 sec...
For armors Q2 had 20 seconds and Q3/QuakeLive had 25 seconds. Which can feel a bit fast sometimes, so I see no problem with a slower respawn but this is too slow. One lucky player gets armor(s) and you have to do without for minutes if you're unlucky.

**30 seconds for all armors will feel much better. Or RedArmor 40 (twice the Q2 time) and the others 30, including shards.**

(Also quad respawns afer 90 seconds and expires after just 20. If you'd set it to 80 seconds there will be no quad for a full minute, which probably feels more natural and is easier to time on the clock than a wait of 70 seconds.)

**Comment by jdolan** [comment]
Tried these. Let's get a game in soon and see how they feel:

 * Shard: 10s
 * Jacket: 20s
 * Combat: 30s
 * Body: 40s
 * Quad: 60s

**Comment by Panjoo** [comment]
10s is just too short for any armor or health I think. Not hard to imagine that if a map has groups of shards very close together it'll enable you to collect a considerable amount of armor. Run back and forth and they'll keep popping back up before you can turn around. But go ahead and try it ,-)

(BTW what about the small_healths, they still decay which makes them useless.)

**Comment by Paril** [comment]
Small health is on my list of things to fix, as well as mega. They need to work more like Q2 did.

**Comment by jdolan** [comment]
Nudged armor shards to 15s, gonna close this bad boy out.
