### ISSUE TITLE
Chasecam switches sometimes cause item pickup flashes

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#419]

**Comment by jdolan** [comment]
Tagging to 1.0 because, while minor, this seems like a quick fix.

**Comment by jdolan** [comment]
Uh, is it possible that the target you just switched to did in fact just pickup an item?

**Comment by Paril** [comment]
Yes and no. They have to pick up an item, then you have to switch away then back. For a few seconds after they pick up an item, every switch to them will cause a screen flash.

**Comment by kaadmy** [comment]
Isn't this fixed?
