### ISSUE TITLE
drawing order hud pics (w_select)

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#421]
I had a nice idea for the w_select image, but what looks great in photoshop looks different in quetoo. 
Apparently the HUD places the w_select pic behind the weapon pics :(

![hudpicorder](https://cloud.githubusercontent.com/assets/10857572/22984337/5a5b0794-f3a5-11e6-9151-a0e2db5c90fc.jpg)

**Comment by kaadmy** [comment]
Should be work correctly in 6b6e8c03

**Comment by Panjoo** [comment]
@kaadmy - I think you misunderstood, so just to be sure...:


In https://github.com/jdolan/quetoo/commit/6b6e8c03ab453b2e2ff38da24f43b792029c1e5a you called it: "Put w_select image **under** the selected weapon icon"

But it already is under the selected weapon icons. **I need w_select to be on top!**

**Comment by kaadmy** [comment]
Oops, wrong commit name.. I probably confused it and got it backwards...
It did show up on top when I tested it.

**Comment by Panjoo** [comment]
Yes, it's all good now! Thanks Kaadmy :) 👍
