### ISSUE TITLE
SDL_Image is lacking in support

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#423]
It lacks a lot of Write routines and can't seem to read grayscale TGAs. I'm not sure what else we have for options, but maybe we should think about it at some point?

**Comment by jdolan** [comment]
We could always contribute greyscale TGA support to SDL_Image.. Can't be that hard to implement. We benefit *a lot* from SDL. I'd love to give back a bit.

**Comment by Paril** [comment]
Could do, I dunno if they're accepting patches though. When was the last time SDL_image was updated?

**Comment by jdolan** [comment]
Last commit was 6 weeks ago. There are a shitload of games that use SDL_Image. I have high confidence that it will be maintained for the foreseeable future.

https://hg.libsdl.org/SDL_image/

**Comment by kaadmy** [comment]
Is this issue needed really?
It's not related to Quetoo since it's an SDL_Image issue.
Maybe open a bug there instead?

**Comment by Paril** [comment]
Yeah I dunno, last changes on SDL_image were just benign warnings and text file changes. I don't think it's really being maintained as far as features go. Personally I'm still on the side of replacing it with something actually being worked on for support (as in, having both read/write support for formats and supporting the majority of basic types of images, like grayscale).

I've always liked DevIL because of it's GL/AL-style API, but that's just me.

**Comment by jdolan** [comment]
I'm not in favor of replacing it. We use SDL extensively. It works.
