### ISSUE TITLE
grapple pulling SUPER fast when set past default?

### ISSUE THREAD

**Issue by Dracant** [jdolan/quetoo#424]
I Set grapple distance to 2x default.
speed set to 800.
on a long distance grapple, presumably past the default launch distance, I get up to 2000 speed for a bit before it settles back to the max of 800.

**Comment by jdolan** [comment]
I wonder if the hook pull is accelerative, and in that case, I probably broke it when I naively made the distance configurable.

**Comment by jdolan** [comment]
All set, thanks for catching this!
