### ISSUE TITLE
Hook should emit sparks when impacting structural

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#425]
From Beavugh:

hook could be more responsive with auto refire hook when hooking non-hookable object like a player, the sky, etc

as long as the hook key is being held down a hook should be firing or attaching to an object until released.

(i was pressing the hook key at a rapid pace tonight and sometimes i would hit the key expecting a hook to fire but nothing comes out and my finger is holding down the key. if i try to hit the hook key twice at a rapid pace the second time i press down it does not register.. i tested about 10 time in a row each time the 2nd key press doesn't register.)

when grappling hook hits a surface/object spark or blood particles should be seen.

the sparks help a player know when their hook connects and helps them time their moves.

**Comment by Paril** [comment]
Blood particles are there when you hook a meat entity. Auto-refire would be a little cheap since it'd make it a little too easy to use as a weapon (which is why there's a delay between firing).

**Comment by jdolan** [comment]
Nick asked for auto-refire only when you *miss* anything hookable.

I agree that rapid fire is undesirable, and I like the delay you have in there now @Paril.

Sparks on impacting structural would be cool, tho.

**Comment by Paril** [comment]
Auto-fire on missing is probably fine, but I don't know about it autofiring if you hit something legit.
Sparks are a +1

**Comment by jdolan** [comment]
I'm going to suggest that we not implement auto-refire for now, and modify the ticket description to simply call for sparks.

**Comment by Quake2Beaver** [comment]
yay for the sparks! :) 

would be nice to have a separate game type called "Railwarz"  different from "Instagib"
the Instagib game type is really only missing 3 core elements that set it apart from Railwarz.. 

1.) The auto refire hook when hitting a non-hookable object. (players and sky)
in railwarz the hook auto refires when it hits a player.. (hook damage can be turned on and off... its off by default in railwarz.. and i dont think it will auto refire if hook damage is on.. which makes the game no fun to play.)
sky hook can be enabled and disabled...  some players like it on.. some dont.. (most dont care ether way they are just happy to play so this isnt a core element but helps explain why the auto refire hook is needed when skyhook is disabled.) 

2.) being able to fire the hook rapidly ( time needs to be cut in half)

3.) railgun refire or reload wait time needs to be cut in half 

The theory behind railwarz is all about speed...while maintaining control with smooth, fluid movement. everything can be done very quickly in this mod..with precision! "It's the fastest mod you'll ever play!" thats the motto at least..  take away one of those 3 cores elements, it will disrupt the pace and flow of the game.

I can see many players loving the vanilla instagib.. i enjoy playing on tastyspleen railz time to time.. but myself and majority of railwarz community can only take so much slow speed action before we grow bored :)

also seeing how Railwarz is one of the most active Quake2 mods for the past few years. if we could get this extra game type added it would be a lot easier to appeal to the existing railwarz community and increase the number of Quetoo beta testers by quite a bit :)

**Comment by kaadmy** [comment]
Done in 92fd3fbf26053d5249fb4a9269507168100ed37c
