### ISSUE TITLE
quemap -zip should use Cm_LoadMaterials

### ISSUE THREAD

**Issue by Dracant** [jdolan/quetoo#428]
Failed to add _fx file called out in the .mat file

**Comment by jdolan** [comment]
Can you attach the .mat?

**Comment by jdolan** [comment]
A possible fix was pushed. We were previously not picking up materials defined with `diffuse` -- only `texture` was previously supported.

**Comment by kaadmy** [comment]
Is this fixed or something?

**Comment by Dracant** [comment]
Do I need to put the Cm_LoadMaterial in the command line when running the
pak generator?

**Comment by jdolan** [comment]
The bug is fixed, yes @kaadmy. But there's refactoring to do here.

@Dracant No bud, you can just run quemap like you were before :)

**Comment by kaadmy** [comment]
*Bump*

**Comment by jdolan** [comment]
Bump urself pal! ;) I'll try to get to this over the weekend.

**Comment by jdolan** [comment]
This is done.
