### ISSUE TITLE
Loading map sometimes hangs while connecting

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#434]
Sometimes when loading maps (@Arseflute and I have both has this issue in different instances), the client will just hang on `Connecting to x.x.x.x...` and not load, eventually you have to just quit and reopen the client.
Happens on localhost (`map edge`) and public servers.

**Comment by jdolan** [comment]
Hm. @Paril fixed one issue like this several weeks ago, where a `qport` of `0` (and it's randomly generated) would cause a similar problem.

**Comment by jdolan** [comment]
Any steps to reproduce this one?

**Comment by Arseflute** [comment]
It was happening about every other game yesterday, as long as you play thru
till the map changed... seems like if it was voted out it didn't do it..
could have been me imagining that tho..

**Comment by kaadmy** [comment]
I haven't seen this issue recently, should it be closed for now until someone can find/reproduce it?

**Comment by jdolan** [comment]
I haven't seen it in ages. Until we have a way to reproduce this, I'm closing this out.
