### ISSUE TITLE
Quad doesn't create a shell effect

### ISSUE THREAD

**Issue by WickedShell** [jdolan/quetoo#436]
Picking up the quad doesn't have a shell effect on the player model (with cg_third_person) or on the view model. The player does however emit light.

**Comment by kaadmy** [comment]
I got this narrowed down to commit 50efb95ace094e808d7687ef763bb92a0db9145a or the one after it (I couldn't test that exact commit because it wouldn't compile)
Didn't see anything obviously out of place with that commit regarding shell effects, but it does change them somewhat.

**Comment by Paril** [comment]
Fixed in latest commit. Was a bitwise operator mishap (&= instead of &= ~)
