### ISSUE TITLE
`make rsync-data` is outdated

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#437]
Title. `make rsync-data` still exists, and as far as I know, it's very outdated now since rsync isn't used for the data anymore, and the Java updater is favored.

**Comment by jdolan** [comment]
Yup, go ahead and remove this target and any mention to it from README.

**Comment by kaadmy** [comment]
Removed Rsync from the README and related Makefiles, @jdolan has to remove mentions of it from the Xcode projects.
3ecb2f0d
