### ISSUE TITLE
Model system improvements

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#438]
This might be unrealistic for 1.0 and is not necessary for 1.0 to function, but @Panjoo and I have discovered that the limitations of the model system are going to limit us quite heavily as to what we can do compared to what Quake 3 could do with MD3s.

- [x] r_mesh_model cleanup; r_obj_t is entirely redundant and r_md3_t is filled with data that is not necessary for rendering the model (it's used as temporary scratch space), r_types has tons of temporary types that are exposed to the public even though they are never used outside of r_mesh_model's loading procedures. To fix this, I propose the following:
  - [x] Split r_mesh_model.c/.h into r_mesh_model_obj and r_mesh_model_md3, keep their local structures contained to the source and only expose the necessary functions/structs to the public
  - [x] Instead of r_obj_t and r_md3_t storing their respective representations, we should have a single "r_model_t" which contains the data that is required for rendering. Both formats can be loaded into the same format-agnostic structures. (see points below about obj first though)
- [x] .obj file format supports grouping, but grouping is not respected in the loading of said format. They should be split into meshes exactly like what md3 does. (seems useless now, but keep reading)
- [x] ~~.skin files should be supported for *all* models, not just player models. This will allow *any* model to prescribe different materials per mesh. Currently, an entire model is forced to use a single diffuse texture. For more advanced effects (like having a single model contain both opaque and transparent components), this will make this a breeze and not bash our fillrate by having the opaque bit run through a bunch of transparent pixels. If no .skin file is there, then we can just fallback to using the skin.tga material. This'll future-proof the necessity for having models with more complex texture setups, etc.~~ This was done differently. Better than .skin files :)

This ticket is solely about model formats - see my next ticket about materials for part 2 of the problem/the fix for said problem.

**Comment by jdolan** [comment]
I like all of this.

**Comment by Paril** [comment]
This is all done since the merging of PR 476. The only thing left is that jdolan was not satisfied with the concept of R_FindMaterial, so I'll leave this ticket open to deal with that one.

**Comment by kaadmy** [comment]
Has this been resolved already?

**Comment by Paril** [comment]
No, plus we still can't do custom diffuse passes. Some day(tm).

**Comment by kaadmy** [comment]
*naggy*

**Comment by jdolan** [comment]
I'm closing this out. After the material system rewrite, I'm happy with how this all came together :)
