### ISSUE TITLE
Quetoo crash on start

### ISSUE THREAD

**Issue by Azgadel** [jdolan/quetoo#443]
Once you launch queeto.exe,after a while (5-10 seconds)a window pop up telling that Quetoo doesn't start and i'm obliged to quit. Windows 8 64 bit
![capture](https://cloud.githubusercontent.com/assets/26044600/23342074/96ffef8a-fc4b-11e6-81a6-70d2af61cbff.PNG)

**Comment by kaadmy** [comment]
I'm a Linux person so I don't know Windows well, but have you run the updater yet?
You also need OpenGL 3.3 to  run Quetoo.

**Comment by Arseflute** [comment]
have you ran quetoo-update.exe? if I recall correctly mine done that as well at first. so I had to run update and it straightened it out.

**Comment by Azgadel** [comment]
Haven't run the updater. But now when i run it it's says that Windows haven't found 'java'
![capture](https://cloud.githubusercontent.com/assets/26044600/23354195/ea44a736-fcc7-11e6-826e-5e5a8b08a718.PNG)
P.S: I have OpenGL 3.3.

**Comment by jdolan** [comment]
The updater requires Java8 to run.

**Comment by Raptor007** [comment]
It'd be nice if this *didn't* require Java, because Oracle's Java for Windows is awful.  But at least it works with OpenJDK: https://github.com/ojdkbuild/ojdkbuild/releases  Get the latest windows.x86.zip, extract it somewhere, and add its `bin` directory to your `PATH` environment variable.

**Comment by kaadmy** [comment]
Well we've been thinking about making the updater built in to the game to autoupdate while playing, but until then Quetoo will probably stick with Java 8 for the updater.
