### ISSUE TITLE
Grenades don't sink fast enough

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#445]
I think something as small, round and compact like a grenade should not have this much resistance in water. 
It's like they land in transparent jelly.

Fired from under water it makes sense to have some resistance but even then it's too much now.
Besides, rockets are not affected by water resistance at all.

**Comment by WickedShell** [comment]
ooooOOH! Now I want rockets that are affected by water....

(I know, I know, "PRs welcome") would help make falling in water less of a
stuck target feeling :)

**Comment by kaadmy** [comment]
@WickedShell just do it :)
