### ISSUE TITLE
Check for console fonts, bail out with SDL error dialog if missing

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#447]

**Comment by kaadmy** [comment]
Shouldn't the console/ObjectivelyMVC font be just bundled with the data repo?

**Comment by jdolan** [comment]
The console font is different from the MVC font (MVC uses FontConfig to resolve native, system fonts). The point of this ticket is to throw up a flag in users' faces if they have not yet run the updater.

**Comment by kaadmy** [comment]
Ah, that makes more sense, okay.
Maybe having an "important" flag for opening files that raises a fatal error if it's not found?
