### ISSUE TITLE
Materials files are not used on some occasions

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#453]
Player skins (Example `guard/default`) that were selected when the map was loaded have only that material loaded (So setting your skin to `guard/mgss` would result in the visor being opaque and no tint defaults), but other models (Example `dragoon/ctf` and `dragoon/bastard`) work correctly.

`r_restart` completely fixes this problem, nothing else I've tried does.

**Comment by jdolan** [comment]
I think @Paril just fixed this?

**Comment by Paril** [comment]
Fixed in e835a8705ecf33e43197f6af866b9f0e79372976
