### ISSUE TITLE
CVar and CCmd search function

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#456]
There should be a way to find CVars and CCmds by a string search, ie. `search sensitivity` would result in the `m_sensitivity` CVar.
Possibles names could be `find`, `search`, `apropos`, `locate`.

**Comment by Paril** [comment]
Why not fuzzy tab completion with a mouse/arrow key selector like Source? I think this should be deferred until post-ObjectivelyMVC for console.

**Comment by jdolan** [comment]
Both good ideas! Agree that some search function would be a welcome addition. Agree that fuzzy tab completion might be the way to go. Agree on deferring for a while ;)

ObjectivelyMVC *may* some day be responsible for *rendering* the console, but our console subsystem itself is not going away, and I would see this functionality living there (like how `Con_CompleteInput` and `Con_SubmitInput` already do). That way it would be available to the client and dedicated server consoles alike.

**Comment by Paril** [comment]
Adding fuzzy completion is like a one-line change, I can do that right now. Will see if it looks better.

**Comment by Paril** [comment]
Try 8a7e536

**Comment by kaadmy** [comment]
A search function would be mainly for finding aliases that have a string in their definition, descriptions, etc. more than the names themselves.

**Comment by Paril** [comment]
Honestly, we should never have to search through descriptions. If the cvar/cmd name isn't descriptive enough to deduce what it does by itself, it should be changed. I don't think having keywords and needing to search through them is a good fix to the problem. Example: r_swap_interval will mean nothing to 99% of people other than those who knew that back in like the 90s/to GPUs it was referred to it as that. Now it's called vsync, and everybody knows what vsync means. If people are searching for vsync, they should only have to type vsync and hit tab; they shouldn't have to get frustrated looking through the list of r_ cvars, not finding it, then "search vsync" and find r_swap_interval and feel dumb about it. Just my two cents on this.

**Comment by jdolan** [comment]
I think this can be closed with the most recent tab completion fixes?

**Comment by Paril** [comment]
I think so. Because of the stricter completion now I wouldn't be adverse to adding a way to search through all names and descriptions, like shift tab or something, but the initial issue is fixed.
