### ISSUE TITLE
Particle bugs

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#458]
**Edit:** apparently this only happens in the map Edge.

For some reason I'm not seeing the debris particles anymore. Instead I see white squares.

![particlebugs0](https://cloud.githubusercontent.com/assets/10857572/24322560/c92e3fae-1166-11e7-98ba-c693ab22c439.jpg)

Same happens when I fire into the water, no ripples but squares.

![particlebugs1](https://cloud.githubusercontent.com/assets/10857572/24322545/959b9a7e-1166-11e7-83df-fa5a86f709a5.jpg)

Also, as you can see the lighting bolt seems to wobble which breaks the tiling effect. (I'm thinking about making the bolt wider and less straight anyway.)
Been testing with newer debris and stains and I've made sure I updated and got my own temp stuff out of the way, so this is not something I did that's messing things up.

**Comment by kaadmy** [comment]
Using latest master for both quetoo and quetoo-data, I can't reproduce this one.

**Comment by Paril** [comment]
Try r_atlas 0 and see if that fixes issue 1.

Lightning bolt one is intentional - the bolt is split up along its path to look a little random, but unfortunately creates the effect of the bolt edges not connecting properly. I don't know how far jdolan would want us to go to fix the issue, either we need the ability to specify vertices by hand and manually set them up or have it be completely straight again.

**Comment by Panjoo** [comment]
This is with r_atlas 0 and it makes it worse;

![r-atlas0](https://cloud.githubusercontent.com/assets/10857572/24380981/4c66545e-134e-11e7-9b5b-54059e5767c7.jpg)

How can this be happening on Edge only, how's that work then?

**Comment by kaadmy** [comment]
@Panjoo how much ram/vram do you have? Could this be possibly related to loading too much data and some stuff not loading correctly?
What about more resource intensive maps like Wake and Trial?

**Comment by Panjoo** [comment]
Something around 1G DDR3. It doesn't happen on Wake and Trial, just checked it.

![wakedebris](https://cloud.githubusercontent.com/assets/10857572/24382377/1e7bc8dc-1356-11e7-84f6-b88dca25fb02.jpg)

**Comment by Paril** [comment]
Chances are that something in your view is leaking state or something over to the particles. Play around with various r_ options until it doesn't happen any more, that might narrow it down.

**Comment by Panjoo** [comment]
I played with many r_ options but no luck. It just looks like the game can't find those particle textures when Edge is loaded.
Also tried the r_dump thing but I didn't find any png called cg_particle_atlas.png

**Comment by jdolan** [comment]
What if you just open, edit and re-save the debris particles? Are they some funky flavor of PNG or TGA that MinGW's SDL struggles with, or something?

**Comment by Panjoo** [comment]
That would mean that I wouldn't be able to see any debris particles at all, right? But it's only on Edge that I don't see debris or water ripples. Don't know when exactly this started happening.

(BTW, I'm at like 98% done with a port of my old q2 map "Grunt" :) Need some shut eye now, but hope to get it ready by tomorrow. Always the same problem, finding/creating the missing textures you need...)

**Comment by jdolan** [comment]
YAAAAS I love that map!!

You're right, I had a brain fart. The fact that this is map-specific means it's almost certainly a coding error in our media system.

**Comment by Paril** [comment]
http://i.imgur.com/n2ocqIu.png

It should be here. If you don't see the atlas here then there's definitely something going wrong with the media system, but nobody else is able to repro.

**Comment by Panjoo** [comment]
> Also, r_atlas must be 1 for this file to appear

Sigh... Ok, now I see it.
![dump-images](https://cloud.githubusercontent.com/assets/10857572/24581054/50201462-1714-11e7-8f52-6f6c74c2316b.jpg)


Here's the file itself, looks okay, as do the rest of the particles.
![cg_particle_atlas](https://cloud.githubusercontent.com/assets/10857572/24581059/69e37984-1714-11e7-99f0-f0ebf28fd53a.png)

Yes, "WTF?" indeed.

**Comment by Paril** [comment]
Interesting. Alright, so it's definitely state-related, but as far as I know nobody else can reproduce this one.. so that's fun

**Comment by TenaciousTigerTrumpets** [comment]
Time to come out of lurking.
I also have this. Edge is fine tho, I get it on slimy.

**Comment by kaadmy** [comment]
Hmm. CC @Paril?
@TenaciousTigerTrumpets does disabling stainmaps fix it? `r_staimap 0` in console I think?

**Comment by TenaciousTigerTrumpets** [comment]
@kaadmy, nope. But r_restart (once per map load) apparently fixes it for me.

**Comment by TenaciousTigerTrumpets** [comment]
Apparently s_restart to fix the sounds also fixes the missing textures. After s_restart the loading screen displays the font atlas.

**Comment by Paril** [comment]
What about r_atlas? This is definitely a media system issue, but I don't understand why none of us can reproduce it on either Windows 10, Mac OSX nor Unix. :(

**Comment by Paril** [comment]
Ok so I may have found the bug. Fixing now.

**Comment by kaadmy** [comment]
Aaaand this is why having explicit types is usually a good idea.

**Comment by jdolan** [comment]
That's weird! I'm pretty sure `lengthof` *does* return `size_t`. We do use explicit types everywhere.

**Comment by Paril** [comment]
@jdolan it does - the problem is that i was size_t, which is 32-bit on 32-bit systems, but PRIuMAX is 64-bit on those builds. Mingw does not have a macro for format that is properly aligned to the integer size (PRIuPTR/PRIiPTR is the standard ones, but they don't exist on Mingw), so I just forced it to be 32-bit since that'll fix it for now.

**Comment by jdolan** [comment]
Oh, wow. That's nuts. Great find.
