### ISSUE TITLE
Fullbright maps cause signal 11

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#460]
Now that #459 has been fixed, the other issue I mentioned still stands.

Quetoo crashes with a **Sys_Signal: Received signal 11** when I try to load up a fullbright map.

Here's a small testmap compiled without light. Rename .pdf to .bsp ->  [test-nolight.pdf](https://github.com/jdolan/quetoo/files/870275/test-nolight.pdf)

**Comment by jdolan** [comment]
I'm guessing this has to do with @Paril's stainmap changes (stainmap and lightmap are closely related).

**Comment by Paril** [comment]
Can fix this soon.
