### ISSUE TITLE
`map <tab>` breakage

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#461]
Looks like a regression in the console code. Typing `map <tab>` will cause an output of:

    map map map map map map map map map map map map map map map map

Etc.. (2048 chars worth, or whatever the console input buffer length is. Hitting enter will then put you in a really bad state where the command buffer (not the console input buffer) overflows, and does not recover, leaving the game unusable and un-quit-able too. So really, this is 2 bugs in one.

**Comment by Paril** [comment]
Fixed the issue with "map " copying over a super long buffer which caused the corruption, but the corruption could still potentially happen probably.

**Comment by kaadmy** [comment]
Should I close this?

**Comment by jdolan** [comment]
Both issues are fixed now.
