### ISSUE TITLE
HUD flickers if view is sized down.

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#464]
Discovered this one by accident. When the screen is sized down using (-)`cl_view_size_down`, the HUD flickers out of control if you fire weapons. It goes nuts when gibbing a dead body. At least here on Windows.

**Comment by kaadmy** [comment]
Likely related, yesterday I noticed corpses changed brightness a bit when being shot, and people firing the hyperblaster flicker black.

**Comment by Paril** [comment]
Probably related to stains, since they change states quite a bit.

**Comment by Panjoo** [comment]
Apparently this hasn't been properly fixed yet. =/

I was doing some more tests regarding #458 and decided to completely move the Documents\My Games\Quetoo\default folder out of the way and then Update again.
HUD still does strange things. Something tells me this all has to do with each other. 

http://panjoo.tastyspleen.net/quetoo/uploaded/quetoo-viewsize-hudflick.zip

Here, I recorded a video clip showing the HUD starting to flicker when I size down the view. Notice how shooting gibs seems to stop the flickering as long as they're moving.

And check out his screenshot. Taken while playing back a flickering demo. It doesn't flicker on demo but as you can see it shows the HUD offset.

![demoview](https://cloud.githubusercontent.com/assets/10857572/24582441/3d6cc560-1730-11e7-89cd-cdc37e035c3e.jpg)

**Comment by Paril** [comment]
Yeah this was state leaking with stains. Check your commit ID in console and see if it matches the latest commit ID. r_stainmap 0 will fix it temporarily, but I can't reproduce this specific bug any more. It was just using the wrong viewport when restoring from stainmap operations.

**Comment by Panjoo** [comment]
This is all I'm seeing when I launch it;
![initialized](https://cloud.githubusercontent.com/assets/10857572/24590767/777c5590-17f3-11e7-860a-7cf64f44ac79.jpg)

**Comment by kaadmy** [comment]
You're using commit 2e8f5b2, which is from 8 days ago.

**Comment by jdolan** [comment]
... And that's because of the DNS transfer to Google Domains. The `mingw.ci.quetoo.org` and `linux.ci.quetoo.org` build slave records were not migrated by Google's automated tool. I'm fixing this now. The builds should kick off once the Jenkins agents are restarted on these nodes. Sorry!

**Comment by Panjoo** [comment]
Hmm I see... but how can this be if I ran the Updater a day ago?

I'm doing nothing wrong here, all this time that I'm trying to figure out why my shit keeps producing bugs I'm apparently not downloading the latest commits for my version or something.

And this is just venting in general, but my frustration with this game is growing. I'm aware that bugs are a normal part of developing but I don't want to have to deal with bugs that really hinder my workflow.
For instance if someone's piece of code breaks my game in a way that I can't test maps without lighting then I suddenly have a problem.
And most times after I update it breaks something else and no one can reproduce and so it puts my WIP's on hold. I mean, I'm still bothered by the console writing that back tick quote thing while typing and I'm still stuck with a quemap.exe from a mid-2016 quetoo version to compile maps because the newer ones all just crash here. I much rather like to be able to put my avaible hours to good use and produce maps and textures and whatnot. And not waste time trying to figure what could be going on.

**Comment by jdolan** [comment]
When's the last time you tried Quemap? Quite a bit has changed with it lately. Might be worth trying another build of it.

**Comment by Panjoo** [comment]
Tried the latest one (well the one from 8 days ago then) just now and it just hangs for a few seconds before "appcrashing".

**Comment by kaadmy** [comment]
Running the updated just pulls the latest build from the automatic build bot, the build bot was working incorrectly, not the updater or your end.

**Comment by Paril** [comment]
@Panjoo I don't think I added anything to the startup between now and that old build, so that's.. a fun crash. I'll look around.
