### ISSUE TITLE
quemap crash on exit, signal 11

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#465]
@Panjoo: @Paril and @kaadmy did some testing today, and they found that the MinGW quemap.exe is indeed hosed, but we wanted to determine if this matches what you're seeing:

    quemap.exe -bsp -onlyents maps/edge.map

Does this write a new `edge.bsp` to your `My Games\Quetoo\default\maps` folder, but without writing anything to the console? This is the behavior @Paril is seeing on his environment, and it's indicative of a linking issue with the build -- basically, `quemap.exe` thinks it's a Windows GUI app, not a console app, and therefore it never writes anything the the console.

Please confirm if this is what you're seeing on your end with the latest `quemap.exe`

**Comment by jdolan** [comment]
@Panjoo Just an update, we were able to resolve this issue, and the 32 bit MinGW quemap.exe is now working for @Paril where it was breaking before. Maybe you could retest?

**Comment by kaadmy** [comment]
Technically I didn't do any testing :D
Might also want to label this as platform:windows

**Comment by Paril** [comment]
Note that the 64-bit version of quetoo.exe is still busted. It's missing something, but I don't know what yet.

**Comment by kaadmy** [comment]
64-bit quetoo.exe specifically, not quemap.exe or quetoo-dedicated.exe?

**Comment by jdolan** [comment]
@Paril Do you want to track 64 bit `quetoo.exe` in a separate ticket, or just keep this open? It would be great if you could get that build working as well. And, just to clarify, 64 bit `quemap.exe` is working?

**Comment by Paril** [comment]
Yes, 64-bit Quemap works. It's just the exe that doesn't.

**Comment by Panjoo** [comment]
Nice! I appreciate that the 32bit quemap is finally going to get fix0red.

@jdolan: _`Does this write a new edge.bsp to your My Games\Quetoo\default\maps folder, but without writing anything to the console?`_


No, it writes a new bsp _and_ it writes to console, like this:

```
----- BSP -----

BSP Time: 1 Seconds
Total Time: 1 Seconds
Press any key to close..
```

That's good right?

**Comment by Paril** [comment]
Yes it's fixed now :) The old build you tried would print nothing but still
work, it wasn't crashing just not printing.

**Comment by kaadmy** [comment]
> jdolan `Does this write a new edge.bsp to your My Games\Quetoo\default\maps folder, but without writing anything to the console?`

I think he was referring to the version of Quemap that _was_ "crashing" before.

**Comment by Panjoo** [comment]
Oh man for crying out loud, I really hoped and thought this got fixed...

The "test" with: 
_quemap.exe -bsp -onlyents maps/edge.map_  

...didn't produce any errors, but the soon as I try to compile anything else like:

_quemap.exe -bsp -vis -light maps/edge.map_

...or any other map like: _quemap.exe -bsp -onlyents maps/grunt.map_

... then it's back to: 
![signal11](https://cloud.githubusercontent.com/assets/10857572/24761403/84763edc-1aeb-11e7-98dd-6667ffad516e.jpg)

```
APPCRASH
  Application Name:		quemap.exe
  Application Version:		0.0.0.0
  Application timestamp:	58e5289f
  Fault Module Name:		ntdll.dll
  Fault Module Version:	6.1.7600.16385
  Fault Module Timestamp:	4a5bdadb
  Exception Code:		c0000005
  Exception Offset:		00052bf8

```

**Comment by Paril** [comment]
onlyents is known to crash on some maps atm, I have the same issue on MSVC. The crash is only on shutdown though, so the map it outputs should be completely fine.

**Comment by Panjoo** [comment]
Erm, no. 
Unfortunately it's not just about onlyents. Only time it doesn't crash so far is when I do -onlyents on edge.map. And it's also not only on shutdown here, it just won't compile or output a bsp;
```
----- BSP -----
0...
```
...and then it crashes and I have to close it.

**Comment by Paril** [comment]
Oh, well that's even worse. What does the crash say when that happens?

**Comment by Panjoo** [comment]
What I posted above^ is what the crash says, it keeps hanging with an appcrash.

I thought quemap itself takes care of the threading? I mean, I don't set -t2 anymore in the .bat files, I'm on an older dualcore so it always only uses 2 threads.

**Comment by Paril** [comment]
It does, but I may have found the problem after poking around. Going to try the build when it deploys and I'll get back to you.

**Comment by Paril** [comment]
Fixed @Panjoo. It still crashes on exit *rarely*, but that is after it outputs the BSP so don't worry about it + it happens on all builds, not just Ming.

**Comment by Panjoo** [comment]
Well it wasn't the crashing-on-exit that I was worried about, it was the crashing-almost-immediatley-after-starting-it-without-compiling-at-all that got me worried :P

**Comment by Paril** [comment]
Yeah, it was related to libxml + the monitor system that communicates to Radiant. The version of libxml that we are using in the ming build requires us to call a certain function otherwise it crashes - ain't that nice :)

**Comment by Panjoo** [comment]
It's alive!
I did some more compile tests with different kinds of maps and this thing is working like it's supposed to.
Alright now we're cooking with gas again!

Close? Yes I wanna close this.

**Comment by Paril** [comment]
Glad to hear @Panjoo!

**Comment by kaadmy** [comment]
Nice to see this finally fixed ;)
