### ISSUE TITLE
Thread system is really a Promise API

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#470]
So, I've run into a small issue in that the music subsystem needs its own thread that is long-running (potentially for the duration of the entire program), but our Thread_ subsystem isn't suitable for it.

I'm thinking that maybe our Thread_ subsystem should be either adjusted to support such long-running threads, or split into two systems. My rationale is that the only uses of our Thread system currently are not what most people would think of as being threads, and instead are more akin to promises - instead of "I am completing these tasks alongside the main thread without interfering with it", the usage is more "I will begin performing this task immediately and will signal when I am finished and potentially give you back a return value". I think this would be more suited to calling them Promises or something.

My current idea to "fix" this is just to directly use SDL thread routines inside music so that it always has a thread regardless of Thread subsystem, but that seems hacky.

**Comment by jdolan** [comment]
Yea, the current thread system is a thread pool. I don't see anything wrong with it as such. Many frameworks offer a thread pool for async task execution, and what we have now works well for that use case. For the music stuff, I don't see anything wrong with just using `SDL_thread` directly. We use `SDL_mutex` and `SDL_semaphore` directly in other parts of the code that warrant it. We don't have to wrap everything :)

**Comment by Paril** [comment]
Nothing wrong with a thread pool, just that it can't be used for long-running threads since doing "threads -1" waits for them all to end, which in that case would cause it to never end.

It just needs to be noted that it can't be used for threads that run alongside the main thread and that you'd need to do something else to handle that use-case.

**Comment by jdolan** [comment]
I've demoted this and removed it from the milestone. I don't feel this is high priority or a requisite for 1.0. Thoughts?

**Comment by Paril** [comment]
Honestly this issue is just about the wording/semantics of our thread pool. We only use them as what most people think of as promises (a one-off thread that performs an operation and, at some point in the future, "returns" data back to the caller), and can't actually use them as what a lot of people would consider making threads for (a separate thread that is continuously running/processing which other threads poll for).
