### ISSUE TITLE
Demos incorrectly handling full servers

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#471]
`sv_max_clients` doesn't work with demos (or something similar).
If `sv_max_clients` is 1, loading a map, disconnecting, then playing a demo of a game that had `sv_max_clients` at 1 just says the server is full.

Either the client list/number isn't reset on starting demos or disconnecting, or demos somehow take up too many player slots.

`sv_max_clients` should probably also be saved in the demo, so issues don't arise later when viewing demos with more players than the local CVar.

**Edit:** if I set `sv_max_clients` to 4, loading a 1-player demo 5 times also says the server is full. This very likely indicates that servers or demos don't reset player state properly.

**Comment by jdolan** [comment]
There should be no need to encode `sv_max_clients` in demos. The server is just feeding pre-recorded packets to the connected client.

While in theory, a server could publicly host a demo allowing `sv_max_clients` connections, I believe currently the server uses a single statically allocated buffer for demo packets, and therefore really only supports a single connected client. We could consider this a very low priority enhancement if we wish to modify that behavior.

Fixing the playback of demos for the common use case of localhost is definitely in-scope for 1.0, tho.

**Comment by jdolan** [comment]
Hm. I actually just tried exactly what you describe here, and I can't reproduce:

    sv_max_clients 1
    map edge
    record foo
    disconnect
    demo foo

Loads and plays fine. One thing we should address is the "error" state introduced by normal demo playback. See `Cl_ParseServerMessage` for `SV_CMD_DISCONNECT` and `Sv_ShutdownMessage`. I think the right thing to do here is to introduce a new command for error cases called `SV_CMD_DROP`, which yields an `ERR_DROP` on the client, versus `SV_CMD_DISCONNECT` which we can retain for "normal" clean disconnects.

**Comment by kaadmy** [comment]
Can you do the same thing but play the demo twice in a row? That triggers it.

**Comment by Paril** [comment]
Yeah, Kaad's issue is that playing a demo causes the state of the internal server to add 1 to player count, so the next time you play a demo it thinks the internal server already has a player connected.

**Comment by jdolan** [comment]
I think this is fixed now. The server was relying on stale game state (`ent->client->connected`) that is not cleared when starting a demo. Because the server can check the `sv_client_state` of the client, I don't believe this check was required / helpful. @Paril please let me know if you disagree. The commit is referenced above.
