### ISSUE TITLE
OpenAL sound crash when changing maps

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#473]
I just hit a crash when changing maps:

    map edge
    map torn

The crash is in S_FreeSample. Screenshots of backtrace and frozen game attached:

![screen shot 2017-05-12 at 8 06 50 am](https://cloud.githubusercontent.com/assets/643118/25997601/ac05a62a-36ea-11e7-91bc-2d345de0f1fa.png)
![screen shot 2017-05-12 at 8 07 03 am](https://cloud.githubusercontent.com/assets/643118/25997603/ad5d8f56-36ea-11e7-9e6b-c4830adf90e6.png)

**Comment by kaadmy** [comment]
Doesn't happen for me

**Comment by Paril** [comment]
Fixed in 0aea5539d957c943afbfaced444c8fea8e342b96
