### ISSUE TITLE
Hard crash/segfault if you define a material twice

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#474]
https://pastebin.com/EvckBBFh Here's the info for the material loading phase. Is definitely "ribs1a_mat". It is defined twice in the .mat file, which causes a crash.

System does not likey likey.

**Comment by Paril** [comment]
https://pastebin.com/EvckBBFh Here's the info for the material loading phase.

**Comment by kaadmy** [comment]
What would be good behavior for redefining the same material multiple times? Override?

**Comment by jdolan** [comment]
Yea, probably last definition wins.

**Comment by Paril** [comment]
Not only that, but warn the console. It may be very frustrating if an author can't figure out why his changes aren't working.

**Comment by jdolan** [comment]
Fixed. First definition wins, later definitions result in a warning about redefining the material. Like C.
