### ISSUE TITLE
r_caustics glitch

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#478]
The r_caustics effect is producing black blobs in all liquids. (MinGW 32bit)

Looks like someone really scared the crap out of an octopus.

![blackblobs1](https://cloud.githubusercontent.com/assets/10857572/26180359/517df292-3b69-11e7-9efe-498fe34e1be4.jpg)
![blackblobs2](https://cloud.githubusercontent.com/assets/10857572/26180362/54ff1f2c-3b69-11e7-9894-c6928982c294.jpg)

**Comment by Paril** [comment]
Closed: Won't Fix
Project taken over by octopuses.

We'll try to track this one down, I've not seen this one personally.

**Comment by kaadmy** [comment]
I don't see this either; I'll try just adding more safety checks on shaders and hope it's fixed.

**Comment by kaadmy** [comment]
@Panjoo after the next autobuild is out, can you try this again?

**Comment by Panjoo** [comment]
Sure, getting too late here for me now but I'll get back to you, just let me know when I should update.

**Comment by kaadmy** [comment]
The autobuild is usually less than half hour, it should be up now.

**Comment by Paril** [comment]
We definitely need to do the versioning of an automated version file to the build paths so we can download it and check for differences on game run. We're using semver, right?

**Comment by jdolan** [comment]
I suppose eventually we *will* but for now, we could just use the last commit hash. I don't think we need to bother with parsing versions and determining greater than or less than. If your version is anything -but- the reported version from S3, you need to run the installer / updater.

**Comment by Panjoo** [comment]
i686-mingw32 d31e0e5 - I don't see any improvement as to the caustics.

Out of curiosity, how is this effect created, do you use one of the existing textures like envmap_3.tga?

**Comment by kaadmy** [comment]
No, it's a a realtime perlin noise system that just has a color ramp.

**Comment by Paril** [comment]
It seems to be related to your GPU somehow, Panjoo. Looking at the problem, it only seems to be in certain areas, which leads me to believe the alpha value of those pixels is either below 0 or above 1, which might cause this problem. The "bubbles" are also only between caustic lines, again leading me to believe it's an alpha value out of range.

**Comment by kaadmy** [comment]
@Panjoo does this still happen in the latest version?

**Comment by Panjoo** [comment]
Sorry been away for a while. I just checked with version 46ce8e3 and the issue seems fixed, no more blackness. Nice:)

(Probably need to open another issue for this but I noticed some error messages the first time I loaded after updating. 
![quetoo069](https://cloud.githubusercontent.com/assets/10857572/26563299/630cdca6-44d0-11e7-8649-1d6753ea6b98.png)

So far it only showed up once though.)

**Comment by kaadmy** [comment]
Hmm, @Paril is this related to coronas being broken on occasion?

**Comment by Paril** [comment]
This is corona-related, yes.

**Comment by kaadmy** [comment]
Well I was thinking about the hyperblaster coronas in specific.

**Comment by kaadmy** [comment]
Is this specific issue closed now?

**Comment by Panjoo** [comment]
Yes sir.
