### ISSUE TITLE
bad lighting on models

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#479]
First I noticed it on the SSG barrel, but apparently it's happening on a lot of models;

![badlighting](https://cloud.githubusercontent.com/assets/10857572/26217318/35b92592-3c07-11e7-8cd2-742d2bc4c917.jpg)

(the normal for the adren you see in this pic hasn't been uploaded yet but the black spots weren't there before)

It kind of reminds me of the "phong shading" problem I've had before while skinning them with normals. Sometimes re-welding vertices made it go away but usually it's not something that I can fix. 

Nothing has been changed in the models themselves so it has to be something else.

**Comment by kaadmy** [comment]
Does it look like an always-on envmap?
Could this be related to shaders in the same way as caustics?
Try disabling shaders (`r_lighting 0`), if it fixes this it's probably a shader issue.

**Comment by Panjoo** [comment]
You could say it looks like a bad envmap but it's more like the materials suddenly have much too strong values for hardness, bump and specular. 

It's not visible with r_lighting 0 but that makes everything fullbright of course,

**Comment by kaadmy** [comment]
Did this also start recently?
It's possibly a shader issue then, I'll try to push another fix that might fix *something* with shaders :)

**Comment by kaadmy** [comment]
Hm, I can reproduce this although it didn't happen before.
No clue what's happening, but setting `r_hardness` to 0 fixes it...
Probably materials using invalid defaults for some values.

**Comment by Panjoo** [comment]
Oops, went afk for awhile. Yeah this also started recently.

**Comment by Paril** [comment]
Seems to only affect .obj models, likely related to model_cleanup branch. Will investigate.
