### ISSUE TITLE
ominous_bwah spatialized but is a global sound?

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#480]
http://i.imgur.com/AprURTi.png
Since it only warnings once, my guess is this is a bug only on the first frame of playing this sound.

**Comment by jdolan** [comment]
Whatever code plays this sample should set it's attenuation to `ATTEN_NONE`.

**Comment by jdolan** [comment]
(I think this is G_Intermission)

**Comment by kaadmy** [comment]
This still reliably happens.

**Comment by Paril** [comment]
Guessing this was fixed with the calloc majigger?

**Comment by kaadmy** [comment]
Yeah, it fixes it and didn't seem to cause any regressions but it might happen sometime later.
