### ISSUE TITLE
Crash after dark zone after fraglimit hit

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#481]
http://i.imgur.com/AprURTi.png
7 bots, 1 player, lots of gibs. No idea why this happened.

**Comment by jdolan** [comment]
Each giblet is an entity. It's conceivable that you blew through 1024 of them if they weren't set to expire (?)

**Comment by Paril** [comment]
The thing is, if you see "server initialization", this happened *after* the next map had loaded. It failed to spawn them on the new map, not the previous map. I doubt that all 1024 were allocated at the beginning of a new map.

**Comment by kaadmy** [comment]
What's the `item_tech_resist` from anyway? Were you playing CTF?

**Comment by Paril** [comment]
Regular DM with techs enabled.

**Comment by Paril** [comment]
Fixede.d.
