### ISSUE TITLE
ObjectivelyMVC regression causes menus to break

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#482]
With this change to MVC:
https://github.com/jdolan/ObjectivelyMVC/commit/042f35625cd2e2ac8c897ff07cd88e9aeb914118

The MainViewController (a NavigationViewController) has trouble popping to its root VC. The top menu bar, which is a subview of the MainViewController itself, disappears after pushing / popping twice.

As a workaround, I have temporarily commented out line 46 in MainViewController.c.

**Comment by jdolan** [comment]
CC @kaadmy

**Comment by jdolan** [comment]
This is fixed via upstream. We have working menus, and we're not leaking VC's like it's going out of style anymore.

**Comment by kaadmy** [comment]
Yisss.
