### ISSUE TITLE
Ingame sounds not working with MSVC Windows build

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#486]
Basically the title.
A user on Discord is having issues with sound in the MSVC build, and that all ingame sound is silent, including ambient sound. However, music works fine.
He tried the MinGW build, which works correctly.
**Edit:** 64-bit for both builds, if it makes any difference.

**Comment by jdolan** [comment]
Have multiple users reported this?

**Comment by kaadmy** [comment]
Only one person so far I think. Could it by any chance be due to not having OpenAL? It should give an error though if it was missing.

**Comment by jdolan** [comment]
Can anyone confirm / deny this one? A fluke? Possible PEBKAC?

**Comment by Paril** [comment]
Most likely missing oal. I will bundle it with the DLLs when I get home.

**Comment by jdolan** [comment]
Is this one all set now @Paril ?

**Comment by jdolan** [comment]
@Paril I believe you added OpenAL to the distribution now, right?

**Comment by jdolan** [comment]
OpenAL now part of Windows distribution, resolves this.
