### ISSUE TITLE
Dedicated server bundle for Linux

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#49]
It'd be really nice to offer a dedicated server binary for Linux that includes all of the required libs and uses `LD_PRELOAD` or something to make it a universal, drop-and-go install. Maybe what we really want to do here is add some library discovery / bundling magic to the existing Linux build so that we can provide all of our Linux builds this same way. Currently, the Linux build assumes that users have or can install a compatible version of libSDL and libPNG. It'd be great if instead our Linux builds were self-contained, self-reliant bundles.

**Comment by jdolan** [comment]
Do you think you'd have any time to look into this @maci0 ?

**Comment by jdolan** [comment]
We should rethink how we build the dedicated server. It should always be built as `quake2world-ded`. It takes all of 2 seconds to link the additional binary. That way, you can crank out both dedicated server builds and client builds in one go.

**Comment by jar3817** [comment]
It would be really handy if it were static. But if the required libs could
be bundled to work on any distro that would work too.

**Comment by maci0** [comment]
currently we already bundle the libs for the client..
shouldnt be too hard to link an additional binary and ship it alongside in our package.
i wouldnt go so far as to build a separate package tho.

**Comment by jdolan** [comment]
I'm fine with that, @maci0. You're right. A separate package to save a few MB would be silly. Good call.

**Comment by jdolan** [comment]
So what I'd like to do here is change how we flex `BUILD_CLIENT` throughout the code base. `BUILD_CLIENT` will still be defined, but only really used in `src/client/Makefile.am`. If `BUILD_CLIENT` is true, we build the real `libclient.a` libtool library from `cl_*.c`. In any case, we will also always build `libclient-null.a`, which will come from `cl_null.c`. This will include stubs for all client-related functions the server or common code must call (e.g. `Cl_Frame, Cl_Disconnect`, etc..). Then, in `src/main/Makefile.am`, we will declare two `bin_PROGRAMS`: `quake2world` and `quake2world-dedicated`. The former will only be built if `BUILD_CLIENT` is set, and we will link it with `libclient.a`. The latter is always built, and linked against `libclient-null.a`. Tada.

**Comment by jdolan** [comment]
In providing both binaries from a single build, we could do away with the separate packaging and rsync repository for Linux, which would be sweet.

**Comment by maci0** [comment]
do we really need separate packages and rsync repos ?
i dont see the benefit, except for saving a few lousy megabytes when installed either client or server bundle.

**Comment by jdolan** [comment]
Rub your eyes bud. I'm in complete agreement with you :)

**Comment by maci0** [comment]
ok, sorry. guess i was tired :D after reading again i see it

**Comment by maci0** [comment]
ok.. it really looks like miscommunication here.
My idea was to provide a single package and a single rsync repo containing both the client as well as the dedicated server build.
But it looks like you created a second rsync repo and a quetoo-dedicated target folder in the source tree. I hoped we could avoid maintaining 2 distinct versions of update.sh etc..

**Comment by jdolan** [comment]
Nope, we're on the same page. I have a branch called jdolan/quetoo-dedicated that is moving in this direction.

**Comment by jdolan** [comment]
So just an update on this one:

 * The quetoo-dedeicated branch has been merged into master.
 * It produces quetoo(.exe) and quetoo-dedicated(.exe) on all platforms and architectures in a single pass.
 * The dedicated server binary is always linked against ncurses (Linux and Mac) or pdcurses (Mingw) and has a halfway-decent interactive console.
 * Bundling the Linux build from Fedora has proven problematic for users of Debian-based distros.
 * On the contrary, bundling from Debian produces a build that runs fine on Fedora.
 * At the same time, Fedora is the easiest Mingw cross-compile host.

I propose that we add a Debian Jenkins slave into the mix to handle automated Linux builds, while retaining the Fedora slave (and perhaps updating it to 23?) to handle Mingw. What are your thoughts @maci0?

**Comment by jdolan** [comment]
Well.. ci.quetoo.org died (and perhaps @maci0 did as well ). Just kidding buddy. 

So I'm updating the Windows and Linux builds from my own Fedora and Debian VMs, respectively. The Linux client/server/master bundle works fine on Debian based distros. I'm seeing weird dragons when trying to run that build on Fedora. But at this point, I don't know what do say about it. Either we maintain separate Debian and Fedora Linux repositories, or we just say "fuck it" and pick one. I'm throwing my hat in with Debian. I think we'll cover the most ground that way.

So with all of that in mind, I'm closing this one out!

It'd be great to get ci.quetoo.org working again at some point, with both a Fedora (mingw) and Debian (linux) build slave. But I'll just continue using my VMs until we can get to that.

**Comment by maci0** [comment]
Sorry, about that. Looking into it now.
