### ISSUE TITLE
Dedicated server does not disable ncurses when unsupported

### ISSUE THREAD

**Issue by Calinou** [jdolan/quetoo#495]
I'm trying to run a Quetoo dedicated server as a systemd service, which means it will run without a TTY (ncurses won't work there). However, it will always try to use ncurses even if unsupported by the current environment, which means the server will crash upon starting. The error message appears below:

```
quetoo-dedicated[16055]: Error opening terminal: unknown.
```

Running the server directly (e.g. within a `screen` session) works perfectly, but this doesn't automatically benefit from systemd's service management features.

**Comment by jdolan** [comment]
This seems straightforward. We should be able to detect `istty` in `sv_console.c` and simply configure a stdout / stderr `console_t` rather than the `ncurses` one. Let's get this into 1.0 so that folks running dedicated servers for us have options.

**Comment by Paril** [comment]
Is there a way I can replicate this behavior in Windows? Maybe attempting to run it as a service or something?

**Comment by jdolan** [comment]
Hm, I dunno. Sounds plausible.

Another option (I do this, and I bet you'd find it really handy, too) is to just create a Debian / Ubuntu VM in VirtualBox. Setting up the Quetoo build in Linux is trivial (it's literally 1 command, and 5 minutes of waiting while it installing packages). Then you're free to test / fix any of your changes on Linux, client or server.

**Comment by jdolan** [comment]
This is now fixed in 275318a176626e7ec2a94f97bba6f110b5c4b0ec. You'll want to set an rcon password to interact with non-TTY quetoo-dedicated instances.
