### ISSUE TITLE
Player model pitching is applied to corpses

### ISSUE THREAD

**Issue by Calinou** [jdolan/quetoo#497]
When a player dies, their pitch is retained and applied to the corpse, which can cause them to clip through floors (see the picture below).

This is easily reproduced by looking straight up or down, then suiciding using any method.

![Corpse pitch bug](https://user-images.githubusercontent.com/180032/30989844-748975d2-a49f-11e7-8203-1cff9d3a45a4.png)
.

**Comment by jdolan** [comment]
Hah, that's pretty funny.

**Comment by Paril** [comment]
I almost just want to leave it because it looks hilarious.

**Comment by kaadmy** [comment]
Might as well leave it :P
