### ISSUE TITLE
Particle amount depends on framerate

### ISSUE THREAD

**Issue by Calinou** [jdolan/quetoo#498]
The higher your framerate is, the more particles will be emitted (which can make some visual effects look strange). This is especially noticeable with grenades or the Lightning Gun – compare `cl_max_fps 60` to `cl_max_fps 0` on an high-end machine.

**Comment by kaadmy** [comment]
I tested with this a few days ago, it seemed anything >40 looked identical to me.

**Comment by Paril** [comment]
This is technically not a huge issue @jdolan but it is valid; higher framerates have less stable particle effects (high being > 300).
