### ISSUE TITLE
Add a splash effect for rain and entering/leaving water

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo#5]
Add a water splash effect for when rain hits the ground, and for when players enter or leave a body of water.

**Comment by jdolan** [comment]
@kaadmy If you want to revive your water ripples branch for object entry / exit into water, we could reuse that effect here so that rain drops make a ripple when they hit water too.

**Comment by kaadmy** [comment]
That branch was just way too buggy, too much entity state is broken in terms of liquid volumes, like the ability to figure out the water surface's height when an entity enters water, or entities thinking they entered water when they spawn in water, etc.

**Comment by kaadmy** [comment]
Um, this is fixed now?

**Comment by jdolan** [comment]
No. There's no ripple for rain, and honestly, I'm fine with that for now. But this has not been fixed.

**Comment by jdolan** [comment]
@Paril fixed in 2e8f5b2054439722614db1f04d4ee9f34e09a76d
