### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#510]
- If you use textures that have more than 19 characters in the name it stops with an error and the map refuses to compile.
![texname2long](https://user-images.githubusercontent.com/10857572/32351752-c8ce57a8-c01e-11e7-8b41-404922a64df1.jpg)

- If the maptitle message is too long (62 chars max?) the map will crash with:
_G_ParseEntity: EOF in entity definition
SDL_main Error detected, recovering.._
The color coding in the title makes you reach the max even faster.
- 'bsp -onlyents' doesn't seem to be working at all.

**Comment by jdolan** [comment]
@Panjoo You realize you've just tipped your hand, right? We now know you are working on a new map :P

Both character limits are trivial to relax, and I'll go ahead and do that right now.

The `-bsp -onlyents` thing is concerning. I'll have a look and report back.

**Comment by jdolan** [comment]
Actually, shoot. The max texture name length is, unfortunately, part of the Quake2 BSP spec. The limit is `32` characters. That's 32 chars for the directory and texture name. I can't relax this one easily without breaking support for legacy maps.

**Comment by jdolan** [comment]
The map title parsing has been fixed.

**Comment by jdolan** [comment]
Confirmed that `-onlyents` is broken. This pisses me off because it was broken a year ago, too, and I spent quite a while sorting it out so that it worked again. Stay tuned..

**Comment by jdolan** [comment]
`-bsp -onlyents` has been fixed (again). Sorry Pan.

**Comment by Paril** [comment]
I didn't do it! :eyes:

**Comment by jdolan** [comment]
Let me know what you want to do about the texture name length. If moving to 64 characters would be a huge help, we can do it. It'll just require managing a couple different data structures for textures as we read / write BSP files (Quake2 vs Quetoo).

**Comment by jdolan** [comment]
@Paril I know you didn't. Chances are very good that *I* did it after I fixed it the last time. 🦆

**Comment by Panjoo** [comment]
That was fast, cool beans!

> Let me know what you want to do about the texture name length.

Well it can be a bit of a bother when you're saving textures and don't always pay attention to the length, and then having to go back to shorten the names, search&replace the textures in the map and then recompile. But that doesn't happen often and now that I'm aware of the length of the names it's not hard to deal with. I'd say leave it at 32 characters for now, it was just something I noticed.

**Comment by jdolan** [comment]
Ok, cool! If you find the other issues are resolved, please close this one out :)

**Comment by Panjoo** [comment]
U fix0red.
