### ISSUE TITLE
Option to color crosshair by health

### ISSUE THREAD

**Issue by Calinou** [jdolan/quetoo#514]
As offered in some id Tech 3-based games or Q2PRO, coloring the crosshair depending on the player's health (taking armor into account) would be an useful addition, so that you can look at your crosshair and get a rough estimate of how much damage you can take.

Health values above 100 could also tint the crosshair in green.

**Comment by jdolan** [comment]
I like it. 👍

**Comment by kaadmy** [comment]
FYI I just checked, Xonotic colors only by health and does not take into account how much armor you haave.

**Comment by jdolan** [comment]
There's also a checkbox in the user interface for this now. The [tentative] cvar name is `cg_draw_crosshair_health`.

**Comment by SpineyPete** [comment]
Iirc in some games the crosshair "jumps" (scale) or changes appearance when you succesfully hit something. I quite like that as an alternative/addition to hitsounds. I'm not sure color is the best way to do the crosshair thing as it would change visibility? Maybe display a tiny shield icon just below the crosshair when health+armor > 100 and a tiny skull icon for health < 35? Could also do something like that for low-ammo warnings (like in Q3) or multikills.

**Comment by Calinou** [comment]
A good way to display hits is to overlay an additional crosshair on top of the default one for a short duration after hitting. This is what Doom 3 and Sauerbraten do.

**Comment by kaadmy** [comment]
Added in 65b894f2c49ebd4dc7bb1fecd937319a2c81ea90, multiple health-based color styles are a possibility later on to add health+armor, different hue ranges, etc.
I think this issue can be closed now even though more work can be done in terms of the crosshair.

**Comment by jdolan** [comment]
Once we add different color schemes, we should update the UI to use a select instead of (currently) a checkbox.

**Comment by kaadmy** [comment]
#533 related.

**Comment by kaadmy** [comment]
Closing since the functionality is there. The UI dropdown not working is a universal issue and not directly related this issue.
