### ISSUE TITLE
XDG Conformance

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo#518]
https://github.com/jdolan/quetoo/blob/1d823b8733822f9b2f6d0a2d57f60a42a223ef83/src/sys.c#L114-L115

See: https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html

Also https://github.com/flathub/org.quetoo.Quetoo/issues/3

**Comment by jdolan** [comment]
I wouldn't really consider making this change until GtkRadiant and NetRadiant are both patched to support this kind of scheme as well. Sure, we could make this change. And then no one would be able to make maps for Radiant on Linux without a bunch of symlinks.

**Comment by jdolan** [comment]
Marking this as wontfix for now. I'm happy to keep the issue open in case both GtkRadiant and NetRadiant suddenly support XDG. It's a trivial change, but.. I don't feel like breaking editor support, or upsetting users who have configs and custom files floating around in the "old" directory.

**Comment by jdolan** [comment]
lol @ the thumbsdown.
