### ISSUE TITLE
OS X: Crash in OpenAL ambient sound playback

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#519]
The map Penumbral Wake still has some stereo samples. In addition to annoying warnings spamming the console, these will actually crash the game on OS X.

<img width="1680" alt="screen shot 2018-01-31 at 7 34 07 am" src="https://user-images.githubusercontent.com/643118/35623322-2ed411d4-0659-11e8-9481-3c24998c9798.png">

![screen shot 2018-01-31 at 7 34 07 am 2](https://user-images.githubusercontent.com/643118/35623388-6d51f5a2-0659-11e8-98bd-d19948d2ca70.png)

@ptrvrhvn Would you mind fixing that sample, if you have a minute?
@Paril Thoughts on why this might actually crash? Do you think this is on us, or perhaps it's a legitimate bug in OpenAL on Mac?

**Comment by jdolan** [comment]
Btw, the crash is not instant, but does occur within a few seconds of spawning into the map.

**Comment by SpineyPete** [comment]
I opened the file and it appears to be mono. There's also a siren_old file that's stereo. Could it be you're running an old version of the map?

**Comment by jdolan** [comment]
Very well could be! I need to purge `~/.quetoo`, but there are also a lot of gems in there!

**Comment by jdolan** [comment]
I'm actually seeing this crash mixing mono sounds, too. On _Torn Glory_, I can reliably reproduce a crash by entering the teleporter. The same line as above (the random sample offset for ambient sounds) throws the crash.

In debugging through it, it looks like the sample count for some sound files is off. For example, the crash on Torn is due to `sounds/torn/thunder.wav`. That sound file is 44.1KHz mono, and a little over 9 seconds in length. However, inspecting the variable shows that our mixing code thinks the file is exactly 441000 samples long (10.0 seconds). It is not.

Is this libsndfile or something? @Paril could you debug the code on your system and get a sample count for `sounds/torn/thunder.wav` ?

**Comment by jdolan** [comment]
I might have had the sample wrong. It appears to be crashing on `sounds/torn/ambient.wav`, which I noticed is re-sampled (by us) to 44.1KHz. Maybe a bug in our resampling code, or not correcting the sample count?

**Comment by jdolan** [comment]
I built OpenAL-soft from source, linked against that, and this problem is resolved. I've re-enabled the offset code for ambient sounds as well.
