### ISSUE TITLE
Sound Improvements

### ISSUE THREAD

**Issue by SpineyPete** [jdolan/quetoo#526]
These are mostly my observations, but everyone's free to give his/her opinions.

### Occlusion
I feel right now the sound "bleeds" through the map too much.
- Use PHS for culling sounds. It seems like it's not doing anything atm?
- Raycast to entity to determine whether the sound should be muffled -- volume and/or low-pass.
- Shape falloff curve to be inverse-square-ish for localized sounds?

### Attenuation
These would be great for fine tuning when there's multiple static sound sources in a scene.
- Sound entity *min_radius* and *max_radius* parameters.
- Sound entity *power* parameter for shaping falloff.

### Effects
- Use low-pass filter for distant sounds. (Maybe even a delay based on the speed of sound?)

### Other
- "Big area" ambient sounds, like reverberating drones and such, might sound more natural if they are not stereo-ized. I don't think there's a way to specify this easily?
- Mix stereo channels together some more when really close to a sound? E.g. treat the sound source not as a point without size. I find this easier on the ears. Maybe it's already doing some of that?

**Comment by jdolan** [comment]
Server-side sounds (`target_speaker`) are PHS-culled, as they always have been. Client-side sounds (`misc_emit`) are also PHS-culled, see `Cg_UpdateEmit`.

**Comment by jdolan** [comment]
- [ ] Use a trace per-frame to determine if a source is occluded, add low-pass filter and reduce volume if trace fails.
 - [ ] Apply a low-pass filter scaled by source distance beyond some threshold (512-1024 units?)
 - [ ] Apply low-pass filter and greatly reduce volume for sound sources that are underwater while listener is not in water.

**Comment by jdolan** [comment]
I believe this is done now, since we moved to OpenAL? I know @Paril spent some time adding filters and things to water sounds, for example.

**Comment by SpineyPete** [comment]
This is all done.
