### ISSUE TITLE
quemap Quake2 "lightstyles" support

### ISSUE THREAD

**Issue by WatIsDeze** [jdolan/quetoo#527]
Having discussed this over Discord/IRC with @Paril we figured this is best left out here as an issue. A welcome one obviously for anyone who intends to do any singleplayer stuff for Q2.

Personally I'd say, if nothing stops you, to even actually add it to Quetoo itself since it does bring a unique kind of feel in pretty much any Q2 games in general. (Modern dynamic lights are kind of wacky for this purpose sometimes.)

**Comment by Paril** [comment]
Some day I'll tackle this, I'd love to see Quemap be the de-facto Q2 map compiler!

**Comment by jdolan** [comment]
Given that we have moved to an entirely new BSP format, and dropped Quake2 support, I'm going to close this issue. Quemap will (sadly) never be the de factor Quake2 map compiler.
