### ISSUE TITLE
Customizable crosshair

### ISSUE THREAD

**Issue by kaadmy** [jdolan/quetoo#533]
What if there were multiple (2 at least, preferably 3 or more) crosshair layers with their own unique settings? Then custom hitmarkers would be easily possible as well as a plethora of other user options.

**Comment by jdolan** [comment]
We could expand the `cg_crosshair_t` struct to have images for damage_inficted, damage_received, item_picked_up, etc.. Could be cool. Up to you if you want to make this a little pet project :)

**Comment by kaadmy** [comment]
I was thinking just keep all our existing code and have an array of 3 `cg_crosshair_t` structs and accompanying cvars such as `cg_draw_crosshair2_color`.
