### ISSUE TITLE
Error starting game in flatpak

### ISSUE THREAD

**Issue by kazysmaster** [jdolan/quetoo#534]
The game fails to start when it is installed via flatpak from flathub.com. The error is:
quetoo: Constraint.c:251: initWithDescriptor: Assertion `self->multiplier' failed.

[quetoo.txt](https://github.com/jdolan/quetoo/files/1776111/quetoo.txt)

I'm running fedora 27.

**Comment by jdolan** [comment]
We don't support Flatpak yet. Someone thought it'd be fun to push a one-time build (now hundreds of commits out of date) to Flatpak and then leave it there. Please install our official snapshots, or build from source.
