### ISSUE TITLE
`cl_console_height` should be capped to sensible values

### ISSUE THREAD

**Issue by Calinou** [jdolan/quetoo#535]
`cl_console_height` can currently be set to 0 (which hides the console but does not disable it, requiring the user to type blindly to enable it again) and values above 1 (which won't display text at the bottom of the console, again requiring the user to type blindly to revert to a sane value).

It should be capped to a value between 0.1 and 1.0.

**Comment by kaadmy** [comment]
Just leaving this here: https://github.com/jdolan/quetoo/blob/master/src/client/cl_console.c#L132
