### ISSUE TITLE
Quad Countdown sound plays at the wrong time

### ISSUE THREAD

**Issue by SpineyPete** [jdolan/quetoo#540]
According to Henry the Quad countdown plays *after* the Quad Damage runs out rather than before it.

**Comment by Calinou** [comment]
I can confirm this in https://github.com/jdolan/quetoo/commit/b3efb7a918b21b67255073012dfdb64701a096b6.

**Comment by kaadmy** [comment]
Closed in 50590cbad9372b994a1bd5a69ce1b86e94048c9a (requires https://github.com/jdolan/quetoo-data/commit/5cfdb6b479a4dc3722926787e1bf345ff9c144a2 or later)
