### ISSUE TITLE
Crashing when using the main menu

### ISSUE THREAD

**Issue by UrInternetGF** [jdolan/quetoo#542]
Everytime I click play, controls, or settings it crashes my game. I put the dmp file in a zip so I could attach it to the post.
[quetoo_2018-03-08_18-54-47.zip](https://github.com/jdolan/quetoo/files/1794395/quetoo_2018-03-08_18-54-47.zip)

**Comment by kaadmy** [comment]
What does the version in the bottom-left corner of the main menu say?

**Comment by Paril** [comment]
Could you include ObjectivelyMVC.dll and ObjectivelyMVC.pdb in a zip for me? I'll check what the dump says with that.

**Comment by UrInternetGF** [comment]
It says "Quetoo 0.1.0 Win32 MSVC 1900 using Clang 3.8.0". And here's that zip you wanted
[objectively.zip](https://github.com/jdolan/quetoo/files/1794547/objectively.zip)

**Comment by kaadmy** [comment]
@Paril is that even the correct version string? It's supposed to have a commit hash but it doesn't...
