### ISSUE TITLE
View model rendering is lackluster

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#543]
Mesh entities and in particular view models (first person weapons) don't have very interesting lighting. In many cases, you can't even really tell that they have normalmaps -- altho they do.

Perhaps the BSP light sources could be tweaked to produce a better looking effect, or maybe we just need to crank up the materials for these models. At any rate, we should see if we can improve their appearance and make them look more high-poly and gritty.

**Comment by SpineyPete** [comment]
Sorry, I broke broke the bumpmapping on models, it's fixed now.

**Comment by kaadmy** [comment]
Linky commit/close?

**Comment by SpineyPete** [comment]
Yeah I was wondering if anything else needed to be done, but I guess not.

**Comment by jdolan** [comment]
Awesome, much better!
