### ISSUE TITLE
Parallax self-shadow would benefit from horizon map technique

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#544]
The self shadowing we have now is expensive, and therefore limited in terms of its accuracy. Apparently horizon mapping would yield per-pixel accurate shadows for nominal cost. We should wait to implement this until #522 (which adds texture arrays support) is merged.

**Comment by Paril** [comment]
Would this allow dynamic lights to do shadow too?

**Comment by SpineyPete** [comment]
Yes, horizon mapping is just a big precomputed 3d lookup texture. You can choose how many directions you want to precompute, usually 8 are sufficient, which means it costs about two additional rgba textures. You can also store at lower resolution and it’ll work just fine.

**Comment by jdolan** [comment]
Just curious.. how do we bake horizon maps from our existing normalmaps and heightmaps?

**Comment by SpineyPete** [comment]
Here's an example including preprocessing source code:
http://www.humus.name/index.php?page=3D&ID=38

**Comment by jdolan** [comment]
@SpineyPete is this still something we want to pursue? Our map formats and lighting are pretty close to final. This would be the right time to introduce a preprocessing tool.

**Comment by jdolan** [comment]
Let's cancel this one and instead just not do parallax mapping :)
