### ISSUE TITLE
Post-processing shader support

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#545]
For features like bloom, tonemapping, etc.. we should introduce a post-processing shader system. The system should allow an arbitrary number of programs to run on the framebuffer in sequence.

**Comment by kaadmy** [comment]
We already have render-to-texture for supersampling, and since shaders are pretty modular it shouldn't be too hard.

**Comment by jdolan** [comment]
So, the idea would be to clean up the code so that the render-to-texture / supersample path becomes the default path -or- we introduce a new cvsar `r_post_effects` that governs that code path, and make all post-effects (supersample, bloom, tonemapping) dependent on that cvar.

So the question is: does it warrant keeping both render-to-texture and a traditional framebuffer path in place? Is there a performance impact we need to be mindful of for low-end systems?

**Comment by SpineyPete** [comment]
Having the ability to render the hud at native resolution and sub or supersample the world seems like a good idea. Could lower resolution without text getting blurry. Resolution could automatically be dropped on fps dips. Ui could be re-rendered only when it’s required to, maybe even async.

**Comment by kaadmy** [comment]
Uh `r_supersample` already does exactly that, hence my previous comment.

**Comment by SpineyPete** [comment]
Derp. I’m an idiot.

**Comment by jdolan-chwy** [comment]
Hah, ironically, this is done now (bloom) and works great.
