### ISSUE TITLE
In-game menus for Join, Vote, etc

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#546]
As a player, I want to use a menu system for joining teams, voting, etc. As a modder, I want to be able to easily extend the default in-game menus.

**Comment by kaadmy** [comment]
The buttons are in the menu already while ingame, they just don't open the corresponding options/dialogs yet.

**Comment by jdolan** [comment]
Yea. I think there's still a little bit of work to figure out how to communicate available votes and whatnot from the server. Config strings are currently used, and that probably makes. But we might need to expand on them (all available teams and their skins and their names, for example?)

Agreed this won't be brain surgery, but we just need to do the work. It'll make a huge difference to the experience.

**Comment by jdolan** [comment]
Also I'd like to get your HUD stuff merged down in before we muck with this too much, as I could see some potential conflicts otherwise.

**Comment by jdolan** [comment]
I decided to kill off the spaghetti that was our voting code, rather than try to slap a UI on it (nightmare).

We could introduce intermission time next_map voting, which is the only thing players would ever actually use, with an entirely different approach.
