### ISSUE TITLE
No sound on macOS Catalina 10.15.4

### ISSUE THREAD

**Issue by marekkaczkowski** [jdolan/quetoo#569]
Hey Jay,
I just installed Quetoo for first time and can't get sound on Catalina :(

OS: macOS Catalina 10.15.4
Quetoo 0.1.0 x86_64-darwin18.2.0

https://developer.apple.com/documentation/macos_release_notes/macos_catalina_10_15_release_notes

> Deprecations
The OpenAL framework is deprecated and remains present for compatibility purposes. Transition to AVAudioEngine for spatial audio functionality.

**Comment by jdolan** [comment]
The current builds from the master branch are very out of date. A new build from the `brave-new-world` branch is forthcoming and uses OpenAL-soft built from MacPorts. Sit tight for the release of this branch.
