### ISSUE TITLE
Bullet tracer particles look like ass

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#573]
These have not yet been updated since the sprites overhaul. Let's make these look nice.

**Comment by Panjoo** [comment]
Something like this perhaps? It's not very visible ingame anyway but at least it resembles the shape of a moving bullet:

![bullertracer](https://user-images.githubusercontent.com/10857572/99196578-9ba3b000-278d-11eb-8bda-1d5edf3d12a3.jpg)

--> [tracer.zip](https://github.com/jdolan/quetoo/files/5543099/tracer.zip)

**Comment by jdolan** [comment]
Oh, sweet! I was anticipating just a code-level fix, but more particles are always welcome!

**Comment by Paril** [comment]
Yeah the issue is just that we didn't have beams at the time so our tracer in BNW doesn't exist at all, lol. The new image looks good though, can thin in out in code and it should work well.

**Comment by jdolan** [comment]
Tracers are better, but bullet impacts are still lackluster.

**Comment by jdolan** [comment]
Closing in favor of #583
