### ISSUE TITLE
Sprite system cleanup and polishing

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#583]
The new sprite system is the balls. But it's currently about halfway done, from a finished effects perspective. @Paril or @SpineyPete I'd imagine this would best be left to one of you to handle:

- [x] All weapon effects should look nice and not tank framerates
- [x] All blood and gib effects, same deal
- [x] CTF trails, has anyone looked at those since BNW?
- [x] Grapple hook beam
- [x] Better weather sprites?
- [x] Bubble trail
- [ ] Clean up the data dir and move unused assets to src

**Comment by SpineyPete** [comment]
I also had these items in my todo file.

#### particle code and artwork

* bullet impacts are still a bit lackluster
* bfg needs a higher resolution projectile sprite
* rail needs a smoother fade-out
* water impacts could be better
* dust particles for fog volumes and such
* blood sprite animation could use some more frames

#### particle system code

* have a simple way for defining particles that exist for *exactly* one server frame
* prevent spawning too many alpha blended particles right in front of the camera as this creates massive overdraw
* interpolated animations should not swap between textures -- this can be done by duplicating the last and first frame for animations that span multiple atlasses and accounting for it in the interpolation code.
* we might need tighter culling for some particle effects as some effects seem to stress the system a bit currently?
* we could use muzzle flashes on the guns for some more oomph, this would require new code for positioning

**Comment by jdolan** [comment]
The sparks effect (used on Torn Glory, Lilith, probably others) currently uses some non-directional, very small additive sprites. It looks quite shitty. Some sparks like the bullet impact ones, with longer life and more bounce, would look great. The dynamic light flash for the sparks effect could probably also be juiced up a bit.

**Comment by jdolan** [comment]
Related #643 #642
