### ISSUE TITLE
Parallax maps have stitching at a certain extreme

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#599]
When parallax textures have an extreme component (depth all the way in, it seems), the parallax is instead projected as if it was no distance out.

It's hard to explain but here's a video: https://streamable.com/9i7can

These pixels all have an alpha of 0 in their normalmap, so at least that's where we gotta look. Probably related to shader changes.

**Comment by Paril** [comment]
Okay, so I looked up the issue on Google because this seemed very specific.
It brought me to: https://stackoverflow.com/questions/46975125/sdl2-pre-multiplying-alpha-channel-when-loading-surface-on-os-x

Lo and behold, not only is this the same image I've been testing on, this is literally the question JD asked. Except now it's happening on Windows, too. Woohoo.

**Comment by Paril** [comment]
Out of curiosity, I tried stb_image to see if it would help, and then copied the pixels back to SDL. No dice. Same stitching. Does not seem to be an SDL_Image issue, then.

**Comment by Paril** [comment]
Well I've at least narrowed it down to somewhere inside `parallax` in the fragment shader. Setting r_parallax_samples to 0 shows the issue quite clearly: ![](https://i.imgur.com/uQuLVyW.png)

**Comment by jdolan** [comment]
Nice catch. I'm sure @SpineyPete will sort this out pretty quickly now that you've pinpointed it.

**Comment by jdolan** [comment]
@Paril I believe @SpineyPete fixed this one? Mind closing out.
