### ISSUE TITLE
Quemap -zip filename issue

### ISSUE THREAD

**Issue by SpineyPete** [jdolan/quetoo#610]
map-fractures.bat:

`C:\Users\Spoiney\Documents\GitHub\quetoo-build\bin\Quemap.exe -p "C:\Users\Spoiney\Documents\My Games\Quetoo\default" -bsp -vis -light -antialias -mat -zip fractures`

It's outputting the pk3 with the filename "map-fractur"
rather than "map-fractures.pk3" at least on Windows 10, haven't checked Mac.

**Comment by jdolan** [comment]
qzip.c, line 346, change MAX_QPATH to MAX_OS_PATH.
