### ISSUE TITLE
Pmove regression breaking riding func_plats down

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#623]
With the latest pmove changes, players no longer ride plats down. Instead, they leave the ground and fall repeatedly. This is hopefully a straightforward fix. It's not jittery: it's a proper fall, even with a landing event. Probably just not adding gravity if a ground entity is set, when we instead should always be adding it, or something like that.

**Comment by Paril** [comment]
Fixed in 255a8449179a4d48cdb4c5d99204159128330fa1
