### ISSUE TITLE
Flare Fixups

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#626]
Flares are a bit odd at the moment and need a bit of work.

- [x] They seem to only look "right" if you are looking upwards? It's hard to explain, check the flares on edge. The big white lamp ones don't seem to appear at all (or very faintly), and the ceiling ones appear "underneath" the light itself and are only fully opaque if you look up.
- [x] They kill FPS if they are all on-screen at once, even if they aren't anywhere near the player. Cg_AddFlares does not seem to respect culling, and it does not seem to respect frame times (it will do a per-vertex trace on every flare every frame; I regained ~50 fps in map corners just by limiting the traces to every 100 ms, but the exposure/alpha algorithm right now relies on it being per-frame so some more care is required here)

**Comment by jdolan** [comment]
@Paril Did you address everything you wanted to with flares?

**Comment by Paril** [comment]
They still don't look great, and most surfaces have two or more flares on them, either intersecting or duplicating, so that needs to be investigated/fixed.

**Comment by jdolan** [comment]
Right. Okay. I'll tackle deduping / merging them if you wanna handle the visuals once that's done.

**Comment by Paril** [comment]
Most of this is done now visually. Maps still have quite a few issues though; edge has some flares that are offset incorrectly (on ceiling near lg), some are using small flares when they should be big (several wall lights)

**Comment by jdolan** [comment]
This is now fixed with https://github.com/jdolan/quetoo/pull/641
