### ISSUE TITLE
Make quemap more material-aware

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#63]
I think it'd make sense for things like SURF_LIGHT, SURF_ALPHATEST, etc.. to move into the material definitions, and to let q2wmap resolve them from there. For compatibility with older levels, and to make porting them easier, we could keep all of the existing functionality, and just combine anything set in the material definition with whatever is set on the surface. In fact, the logic would have to allow surfaces to override the material definition anyway.

This way, for new maps, level designers don't have to interact nearly as much with the Surface Inspector in Radiant. Instead, they can just add a couple lines to their material definitions and recompile.

**Comment by jdolan** [comment]
All of this will require extracting the material definition and parsing facilities into a libtool library (`src/material.c`) so that other subsystems can read and write materials.

**Comment by jdolan** [comment]
I've noticed recently that quemap doesn't seem to correctly auto-flag for known shaders like common/caulk, common/playerclip, etc.

**Comment by jdolan** [comment]
This would be required for (or would greatly help with) #95.

**Comment by jdolan** [comment]
I think the first thing to start with here is the surface and contents flags, as described above. It'd be great if there were friendly ways to specify these in the material definition, something like:

```
{
    material e1u3/water1_1
    ...
    surface warp trans33
    contents water
    light 100
}
```

What do you think?

**Comment by jdolan** [comment]
Side note, I'll eventually have to patch Radiant to support reading our materials definitions in order to affect these flags in the editor.. Whee!

**Comment by jdolan** [comment]
Oh! Another thing to consider here is introducing new `CONTENTS` for snow, dirt, metal, etc, yea?

**Comment by Paril** [comment]
I don't think snow/dirt/metal should be a CONTENTS, it should be a separate material property like physical properties or something. CONTENTS should be reserved for stuff that could affect the brush directly.

**Comment by jdolan** [comment]
Hm, I guess I could buy that argument. I thought Q3 had `CONTENTS` masks for this sort of thing, but I think you make a good case for leaving this in the materials definition.

I guess a general rule of thumb might be: if it could affect the compile of the map, then do it with CONTENTS. If it's purely a collision / renderer concern, then use the material. The CONTENTS masks that we have now all augment the BSP. Snow versus mud versus metal really do not.

**Comment by Paril** [comment]
Yeah, we'd run out of CONTENTS bits pretty quick if we did that :)

**Comment by jdolan** [comment]
@Paril Do you plan on adding some support for material flags (`SURF_LIGHT`, `SURF_BLEND_*`, `SURF_ALPHATEST`), etc.. before the release?

**Comment by Paril** [comment]
I'll see what I can do. I think my only concern  is how to approach overrides -  should material take priority even if the mapper wants to specify a light value on the face?

**Comment by jdolan** [comment]
Having materials available to quemap really makes me want to bring back radiosity.. We could bounce light based on hardness, change how colors are reflected, etc. Could be really cool.

**Comment by jdolan** [comment]
Here are the parameters we could safely expose via materials:

 * `light` Emit light, and use material value when surface has no value (`""`). Mapper can override the light value per-surface (and `0` to effectively disable).
 * `blend_33` Forces `SURF_BLEND_33` on all surfaces, no per-surface override.
 * `blend_66` Forces `SURF_BLEND_66` on all surfaces, no per-surface override.
 * `alpha_test` Forces `SURF_ALPHA_TEST` on all surfaces, no per-surface override.
 * `no_draw` Forces `SURF_NO_DRAW` on all surfaces, no per-surface override.

Alph-atest and no-draw will be really useful for mappers. Creating effect-only brush work (decals, under-item texture animations, etc..) will be a lot easier this way. You can just tag your solid black or solid alpha material as `no_draw` and be done with it. Also, small surface lights that are repeated throughout the map can be tuned quickly in one place with the light parameter.

A small downside here is that Radiant will not be aware of the blend flags if they are implicitly set via materials, and so Radiant will not apply the blend in the camera view. Maybe someday, we can port some basic materials functionality to GtkRadiant.

I think this should be implemented as a single parsed line for surface flags:

```
{
    material e1u1/lite1
    surface light 400
}
{
    material common/black
    surface no_draw
}
{
    material edge/ferns
    surface alpha_test
}
{
    material torn/decal
    surface blend_33 blend_66
}
```

If we decide to expose contents flags in a similar fashion, I think this approach would work well for that, too.

**Comment by kaadmy** [comment]
How difficult would it be to support Quake3 shaders enough so radiant can read them?

Content/surface flags (except visual changes like blend) can just be implicitly enabled and not shown in the editor.

**Comment by jdolan** [comment]
Quetoo materials basically replace Q3 shaders. They do most of what Q3 shaders did, plus stuff they don't. I have no problem eventually porting materials support into GtkRadiant, but we're not going to refactor Quetoo to use Q3 shaders.

**Comment by kaadmy** [comment]
The (more) difficult part would probably be to fork GTKRadiant/NETRadiant to support Quetoo shaders, or get support in the official versions.

**Comment by jdolan** [comment]
Since I'm a maintainer for GtkRadiant and have contributed to NetRadiant several times before, .. not really.

**Comment by jdolan** [comment]
@Panjoo Thoughts on this?

**Comment by Panjoo** [comment]
Hmm, no not really:P As long as I know how it works and there's no confusion as to when materials can override the surface value it's all good.

> small surface lights that are repeated throughout the map can be tuned quickly in one place with the light parameter.

This sounds like it could be really useful for tweaking but for some reason I think that I'd rather have the right light values 'baked' into the map/bsp than have it added via a seperate .mat file for anyone to play with.

**Comment by jdolan** [comment]
Tweaking the material file after the map is compiled would have no effect. These surface flags would only affect the compilation phase. So it's not like someone could change the .mat file and make the map look any different. The material file would simply be a shortcut for you to avoid interacting with the Radiant surface inspector a million times.

**Comment by Panjoo** [comment]
Okay I see. Having control over the surface flags using the materials is pretty cool. But thinking about this some more and looking at it from the mapper's perspective: I'm not sure how useful this would really be in practice. Flagging many surface lights on small light textures is preferably not done in Quetoo anyway so I already avoid this as much as I can. And there usually aren't that many special surface flags like blends on decals in a map. Also, accidentally leaving surface flag stuff the .mat file could cause confusion if you're trying to change flags using the surface inspector. So this seems to be more applicable in the last fine tuning stage or to quickly fix some stuff.

Speaking of avoiding frequent interacting with the Radiant surface inspector, a more likely scenario for me is having to change the keyvalues of many pointlight entities if I want to adjust them, which I still have to do manually through the Entity window. Anyway my main point is if you want to change a surface or contents value you're better of doing this directly in Radiant. You're not going to switch to your material in notepad and set some flags there while leaving the actual brushes untouched and unflagged in Radiant, that's not very logical in my opinion. 
Once you tune surface properties (outside of Radiant) via the material file, won't that mean that the mapfile is then no longer entirely up-to-date with the final compiled bsp?

**Comment by jdolan** [comment]
I'm surprised!

You don't think being able to set e.g. `alpha_test` on a material once is easier than having to specify it on every single face in Radiant?

Or, say you have a bunch of decals to lay.. each instance of the decal requires a paper-thin brush, with 5 sides requiring `no_draw` and one side requiring `blend_33 blend_66`. You could set `no_draw` once in the material definition for the non-visible decal brush sides, and never have to fuss with it in Radiant. This would be particularly useful when your decals are not just copy-paste.

And while surface lights are discouraged from a `quemap -light` performance perspective, there are some maps that will use them -- especially maps that have long, skinny "strip" lights (e.g. The Rage). Being able to light them, and globally tune their intensity, with a single entry in the material file seems like it'd be very handy (?)

.. Anyway, I agree with you on tuning lights. Super annoying.. I spend lots of time revising lights in Radiant. I think we could introduce the concept of light "classes" or "tags" in the materials file:

    {
        light torches
        color 0.9 0.6 0.6
        radius 300
    }

In Radiant, you would simply add "tag" "torches" to your light entities, and then `quemap` would look to the materials definition for default lighting parameters. This way, you could override these parameters per-light where needed. But, if unspecified, we'd use the material tag. We could capture all existing light properties, including direction and cone size for spotlights, as well as new attributes like decay or specular color etc.. Could be really cool!

**Comment by Panjoo** [comment]
Hehe surprising isn't it. I understand what you're getting at and I certainly don't oppose to having more material parameters, but especially when it comes to lighting a map you don't always want global tuning by script. In my own experience mapping has always been about fiddling and tweaking until it feels right, almost like a digital handicraft. Often times I still need to edit values because some lights are closer to a nearby wall than others. And once I specifiy a light intensity of a lightstrip I can no longer adjust that lightstrip in one or two places that would look better with a different intensity.

> Paril: I think my only concern is how to approach overrides - should material take priority even if the mapper wants to specify a light value on the face?

My answer would be no. In Q3 and similar games I always hated how you had to make your own shaders with renamed textures just to change one light value or surface property.

> You don't think being able to set e.g. alpha_test on a material once is easier than having to specify it on every single face in Radiant?

I do, but it also depends on how many faces we're talking about here. I've always liked how you could basicly use every texture you wanted and make it behave like any material just by checking the desired surface flags in Radiant.

**Comment by jdolan** [comment]
Yay, this is finally implemented.
