### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by Mailaender** [jdolan/quetoo#645]
https://github.com/flathub/org.quetoo.Quetoo/blob/master/org.quetoo.Quetoo.appdata.xml#L46 mentions version 0.1.0, but I can't find the tag. http://quetoo.org/pages/downloads also has no versioned source code download.

**Comment by jdolan** [comment]
Hi,

That's a "rolling release" tag for now. We are not yet at a stable general release. When we do have a general release, we'll be using Flatpak for Linux. We do not encourage, and will not be supporting, any other packaging for Linux.

For now, you can expect the Flatpak build to be updated whenever we merge from `develop` to `master`. There will likely be a new build available after the holidays. If you're looking to test / play before then, you should download the source code and game data from Github, checkout the `develop` branches in each, and build from source.

Hope this helps!
