### ISSUE TITLE
Only megahealth over-health should countdown

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#653]
Health stims should not erode over time, as they currently do. Only the megahealth over-health should degrade, and it should do so more slowly than it currently does (this is according to Pan).

Similarly, we should re-introduce separate armor banks for the different armor types so that they can absorb damage differently, as in Quake2.

**Comment by Paril** [comment]
It's currently set to 750ms, Q2's timing was 1000ms.

**Comment by jdolan-chwy** [comment]
Hah, yea, I never paid too much attention to it, but I was also never particularly good at Quake.

I think there are a couple of ways to implement this, but the most robust way might be to use separate inventory slots for each armor type, and for the health stims, and the mega health. Then they can easily be acted on independently. The changes will be centered in G_Damage, which will have to check if it is a client taking damage, and then decrement from each inventory bin in order, according to the type and amount of damage.

I think that, in Quake2, yellow and green armor didn't protect against energy weapons, but red armor did, or something like that?

**Comment by jdolan-chwy** [comment]
1. https://quake.fandom.com/wiki/Jacket_Armor
2. https://quake.fandom.com/wiki/Combat_Armor
3. https://quake.fandom.com/wiki/Body_Armor

This is a bit complicated, but could be refactored out into a few helper functions and would add some interesting dynamics and strategy to the gameplay. I should have never removed this code.. I just got too eager with my scalpel.

**Comment by joe0x04** [comment]
I have a vague recollection of making the armor classes work like they do in Q2 years ago:
https://github.com/jdolan/quetoo/commit/801d5e14f6b85afa4fbb55119f43e3bd9ab8bf4c

Basically energy weapons make a particular armor class act like the class below it. If vicitim has red armor, it acts like yellow when hit with an energy weapon. Yellow like green, green like nothing...etc.

You also get "credit" when upgrading armor classes. If you have 50 yellow and pickup a red, you get the 100 red + a percentage of the yellow (ending up with 125 or whatever) base on the scaling factor between yellow and red.

**Comment by jdolan** [comment]
Oh, wow. Nice! So maybe the bulk of the work here is just for healths. That's great news. Thanks Joe. Good memory btw! 6 years.. damn.

**Comment by Paril** [comment]
This is now close to parity with Q2.
