### ISSUE TITLE
Console background is not positioned correctly for all resolutions

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#654]
Odd resolutions will cut off the background, making it hard to read the input message:

![](https://i.imgur.com/FY6Qoz8.png)

This regression was somewhere around https://github.com/jdolan/quetoo/compare/b15dd0e97ecb...6ce65281d7e7

**Comment by jdolan** [comment]
What would you consider an odd resolution?

**Comment by jdolan** [comment]
<img width="1590" alt="Screen Shot 2022-01-14 at 10 23 30 AM" src="https://user-images.githubusercontent.com/643118/149540048-8e3222ac-a633-4d8f-8dd8-87f6af67cf85.png">
Nevermind. Found one 😁

**Comment by Paril** [comment]
Hasn't been fixed:

![](https://i.imgur.com/fqjAIqj.png)

**Comment by jdolan** [comment]
Fixee-d
