### ISSUE TITLE
UI Bug in the server creation menu

### ISSUE THREAD

**Issue by gugus2000** [jdolan/quetoo#656]
After creating a server, the menu interface to create game breaks

# Spec
On Windows 10, this [build](http://quetoo.s3.amazonaws.com/snapshots/Quetoo-BETA-x86_64-pc-windows.zip) (download button on qetoo.org)

# Screenshot:
first creation ![](https://pic.infini.fr/aNXMJ4X7/zANWxT99.png)
after ![](https://pic.infini.fr/hXqhCqif/I6mJOPIT.jpg)

**Comment by jdolan** [comment]
Can confirm this still happens on the `develop` branch. Thanks.

**Comment by jdolan** [comment]
This is fixed with latest ObjectivelyMVC https://github.com/jdolan/ObjectivelyMVC/commit/6fca17d459d6d1d89fa8b82d2d1ed06268e66784
