### ISSUE TITLE
Add CONTENTS_ATMOSPHERIC for misc_dust, misc_fog, etc.

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#659]
It is problematic for misc_fog to use `CONTENTS_MIST`, as that will often eat other `CONTENTS_MIST` brushes like decals and foliage. Luckily, it shouldn't be too difficult to add `CONTENTS_FOG`, and adjust `LAST_VISIBLE_CONTENTS` to `CONTENTS_FOG`.

Remember to edit Radiant and TrenchBroom project files for this change.

**Comment by Paril** [comment]
VISIBLE contents are for things that actually appear in-game and have surfaces. Special brushes (such as Q2's func_areaportal which have their own contents type that isn't in the visible list) shouldn't be in there. (The main exception of course is SOLID | CLIP, but CLIP is kind of a special hint that just means not to generate visible surfaces but still be in the brush list and collidable)

**Comment by jdolan** [comment]
Good call @Paril. This was surprisingly easy. Rebaked Gehenna to confirm the new type is working correctly.
