### ISSUE TITLE
Dedicated runs by default in the background

### ISSUE THREAD

**Issue by Paril** [jdolan/quetoo#663]
This might only need to be a Windows-only change, but, the default behavior for queded is to have zero user feedback and spin away eating CPU in the background. It's already bit me a few times during testing where I have to end the process, and I have no doubt we're going to have users opening it once or multiple times trying to figure out how to get a console open like the original Quake dedicated executables did.

**Comment by jdolan** [comment]
Is this related to #636 maybe? Perhaps I'm never seeing the ncurses console because the server is spin-locking?

**Comment by Paril** [comment]
Oh, maybe, actually..

**Comment by jdolan** [comment]
If you comment out the call to `Sv_InitConsole` do you at least get a working, non-CPU destroying server? That's what I get on macOS. It's something curses-specific, I think. But it's difficult to debug curses, because it requires a proper terminal (can't run in Xcode).

**Comment by jdolan** [comment]
I think you should retest this with #636 now fixed.

**Comment by Paril** [comment]
Still an issue on Windows, will keep digging.

**Comment by Paril** [comment]
`Sv_CheckForUpdates` just gets stuck in a loop on Windows, with no UI visible
