### ISSUE TITLE
Crash when shooting func_door_secret with certain weapons.

### ISSUE THREAD

**Issue by M-Ro** [jdolan/quetoo#666]
Shooting a func_door_secret with any of the following weapons triggers a crash (missing sound?): **SG, SSG, MG**
Other weapons do not appear to trigger crash (**blaster, LG, HPB, RG, RL, GL, BFG**) .

```
Disconnecting from localhost...
quetoo: cg_sound.c:50: Cg_ParseSound: Assertion `play.sample' failed.
Sys_Signal: Received signal 6
```

**Comment by Paril** [comment]
Can you post a bsp I can load up to test this?

**Comment by kaadmy** [comment]
Not to be that guy, but this is issue #666

**Comment by M-Ro** [comment]
I created a testcase boxmap (attached), but the behaviour is different. Instead of crashing with the above assertion, it simply reloads the map when fired at with the SG/SSG/MG, but not other weapons.

[666.zip](https://github.com/jdolan/quetoo/files/8019918/666.zip)

**Comment by Paril** [comment]
> Not to be that guy, but this is issue #666

banned

**Comment by Paril** [comment]
This seems to be network corruption @jdolan - SV_CMD_FRAME ends up turning into an SV_CMD_DISCONNECT message after some kind of state changes in the bmodel. Not sure what, though.

**Comment by M-Ro** [comment]
Before I create separate issue threads, would this be related to a crash I get when pressing F11? (Not reliable, often takes > 1 trigger)

```
Video initialization...
  Trying 1913x1074..
  Setting up OpenGL context..
  Renderer:   NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
  Vendor:     NVIDIA Corporation
  Version:    3.3.0 NVIDIA 470.94
Video initialized 1920x1080 (1920x1080) fullscreen
libpng warning: iCCP: known incorrect sRGB profile
quetoo: s_mix.c:162: S_MixChannels: Assertion `ch->play.sample->buffer' failed.
Sys_Signal: Received signal 6
```
Sometimes it's a SIGABRT, sometimes it just segfaults.

Additionally I reliably segfault on `quit`, always.

```
thorn wants some
> quit
Server quit
Server shutdown...
Ai shutdown...
  Ai module shutdown...
Ai down
Game shutdown...
Game module shutdown...
Game down
Sys_Signal: Received signal 11
Sys_Signal: Received signal 11
Server shutdown...
Server down
Client shutdown...
Disconnecting from localhost...
Client game shutdown...
Client game module shutdown...
Client game down
Client console shutdown
Client down
```
The segfault on exit never occurs if I run the binary in gdb, which is fun.

**Comment by Paril** [comment]
Known issue that the game acts weird/sounds often drop out when you vid_restart. Probably a media issue. Should be a separate issue, though.
