### ISSUE TITLE
Lithium-style grappling hook

### ISSUE THREAD

**Issue by maci0** [jdolan/quetoo#8]
Title says it all. Have speed of hook and player hook speed variables to a server-side cvar (speed of which hook travels to wall and how fast player moves once grappled). Also server side cvar for enabling/disabling hook, default disabled

**Comment by kaadmy** [comment]
Should this be closed and kept to one issue?
#107 seems to have more conversation and is more recent.

**Comment by jdolan** [comment]
Yar. Thanks!
