### ISSUE TITLE
Script hooks for misc_emit

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#94]
It'd be nice to bind client side emits to entity events. So that, for example, on Frag Pipe, the activator buttons for the lava chamber could emit small lights (red / green) depending on the state of the button. There may be other use cases, and perhaps a server-side solution is easiest. But more thinking should go into client-side scripting first.

**Comment by WickedShell** [comment]
Client side scripting? What? Is there an interest in client side scripting systems?

**Comment by jdolan** [comment]
Maybe. I've actually not yet had any grand ideas of an elegant solution. One approach here would be that on certain `entity_state_t` transitions (e.g. for `frame` on BSP models, which the server sends us to indicate that a BSP mover has reached a waypoint in its path), scripts could be fired. The script names could be a key-value field on the entity. As for the dialect of the scripts, I'd actually assume we just roll our own DSL. I'm not sure that adding a binding system to Lua or Python would be practical or worthwhile.

Another dumber approach would be to simply add a targetable server-side light entity. That would allow mappers to create and trigger lights at will. This is why we've retained `target_speaker`, for example. It can be triggered by other entities, unlike `misc_emit`. And as I'm writing this, I'm thinking it'd be trivial to ask the server to retain `misc_emit` entities that have a target name (it currently ignores all `misc_emit`). Idk, some more food for thought. I'd like to come up with something here before we put The Frag Pipe and The Pits to bed, tho. Both have your classic Quake2 buttons in them.

**Comment by jdolan** [comment]
This is now implemented. I decided that a target_light entity on the server was the best approach, and I have to say, I'm pretty happy with it.

`target_light` should be targeted by another entity (e.g. a button or relay). The user can specify one or two colors to cycle through, and can opt to include an "off" state as part of the cycle as well. So this will work for creating switched lights as well as for creating atmospheric lights to accompany buttons and things. The "wait" key can be used to synchronize accompanying target_lights with their activators. Here's the entity definition:

```
/*QUAKED target_light (0 1 0) (-8 -8 -8) (8 8 8) start_on toggle
 Emits a user-defined light when used. Lights can cycle between two colors,
 and also be toggled on and off.

 -------- Keys --------
 colors : The color(s) to cycle through (1 - 255 paletted, "red", "green", etc..)
 delay : The delay before activating, in seconds (default 0).
 dmg : The radius of the light in units.
 targetname : The target name of this entity.
 wait : If specified, an additional cycle will fire after this interval.

 -------- Spawn flags --------
 start_on : The light starts on, with the first configured color.
 toggle : The light will include an off state in its cycle.

 -------- Notes --------
 Use this entity to add switched lights (toggle). Use the wait key to synchronize
 color cycles with other entities.
*/
```

And here's an example from The Frag Pipe:

```
{
"classname" "target_light"
"origin" "658 1054 88"
"spawnflags" "1"
"colors" "green red"
"targetname" "button1"
"dmg" "20"
"wait" "5"
}
```

**Comment by jdolan** [comment]
Just pushed updated pk3s for Frag Pipe, Pits and Slimy Place, adding `target_lights` for all `func_buttons`. Really ties the button material animations together, having the effect textures appear to glow :+1:
