### ISSUE TITLE
Fog volumes / underwater fog

### ISSUE THREAD

**Issue by jdolan** [jdolan/quetoo#95]
Translucent water looks 100 times better than opaque water. Unfortunately, it also puts swimmers at a tremendous disadvantage that compromises gameplay. A way to mitigate this would be fog volumes, in other words `CONTENTS_FOG`. This flag could easily be added to any water brush to enable fog within it. Players would be more difficult to see when swimming, and fog volumes could add nice ambience to non-water areas too.

**Comment by jdolan** [comment]
The fog volumes themselves would have to be entities, in order to support key-value pairs for color and density, etc. It kinda stinks to eat an entity slot, but there are only likely to be a few of these per map. All volumes sharing the same material and behavior could be grouped into a single entity, too.

So brush entities of class `misc_fog` would consist of brushes that are denoted as `CONTENTS_FOG`. We would need to add that contents flag into the code, update the Radiant scripts, extend `quemap` to automatically `OR` the flag onto brushes in said entities, etc.

I guess the big question, then, is how to render them. Is it possible to render the fog volume itself using a fog texture, as one of the last passes in the pipeline? Or do we have to calculate a fog coordinate for every vertex that resides within the fog, and then render those elements "fogged"? The former sounds way easier..just not sure it will look right.

**Comment by kaadmy** [comment]
Instead of using an entity, could this use surface shaders?

**Comment by jdolan** [comment]
You might be right. It might be possible to simply extend the materials system to support all fog attributes.

**Comment by kaadmy** [comment]
Could fog "volumes" be done by stencilling (or something) fog surfaces, then make the shader change fog parameters depending on the stencil?

**Comment by jdolan** [comment]
I'm not sure. I've never seen the stencil buffer used for fog. Stenciling works well for binary operations, but where things need attenuation over distance, etc.. it falls short. There are a handful of well documented fog rendering techniques out there. I think we need to pick the simplest one that aligns with Quake's BSP scheme, and go with it.

**Comment by jdolan** [comment]
I just found that KMQuake2 has a `CONTENTS_FOG` -- I wonder if there's a fog implementation we could study there.

**Comment by kaadmy** [comment]
Just to bring up this discussion again, does anybody have ideas for this?
Someone's already made a working volumetric fog demo with OpenGL's fixed pipeline rendering without any shaders. Fog also works if the camera is inside it.
http://nothings.org/computer/vfog/shots.html

**Comment by jdolan** [comment]
Yea, I've studied this demo a bit. It'd be much harder to pull off with irregular geometry like arbitrary brushes. Tho, we do have some of this logic already, in how `quemap` removes shared internal faces amongst water brushes. That's basically what we would also need to do for fog.

**Comment by kaadmy** [comment]
Well if I'm not mistaken, that demo works with any (convex?) meshes.

**Comment by jdolan** [comment]
Maybe it'll work, then. Let's finish indirect lighting first, since it's 95% done, and then tackle fog :)

**Comment by kaadmy** [comment]
Sure :P

**Comment by jdolan** [comment]
4 years later...

![quetoo005](https://user-images.githubusercontent.com/643118/100821128-bcbb0080-341d-11eb-8c4f-945ddf7e28e3.jpg)
![quetoo003](https://user-images.githubusercontent.com/643118/100821138-c17fb480-341d-11eb-86f5-3d347add05c9.jpg)

We now have fog volumes via a brush entity called `misc_fog`. Brushes within this entity should be non-solid (lava, slime, water, mist). The entity takes a couple keys: `_color` and `density`. I introduced a back-reference `bsp_brush_t::entity_num`, which allows these entities to be merged into `worldspawn`, but still connected back to their key-value pair definitions at level load. In this way, these brush entities do not burn an entity slot, do not generate a separate inline model, do not incur their own rendering matrix, and _do_ get CSG-subtracted against the world, just like you would want water brushes to.

Fog is calculated during the lighting compile step, and baked into the lightgrid. You must `-light` your map in order to see fog. Soon, I think we'll experiment with multiplying fog by static lighting, so fog will be less visible in dark areas, and more visible in light areas. The lightgrid is now bound and active for the entire 3D rendering pipe, and everything from walls to mesh models to sprites and shadows are fogged with it.

I'm going to close this one out, finally :) I'll be updating the q2dm maps first, and will get those into brave-new-world soon.
